// This file was autogenerated by PeakRDL-verilog
module test #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register TEST1
    output logic                     [31: 0] test1_test1_q,              //! Current field value

    // Register TEST2
    output logic                             test2_test2_swmod,          //! Indicates SW has modified this field
    output logic                     [31: 0] test2_test2_q,              //! Current field value

    // Register TEST3
    input  logic                             test3_test2_hwclr,          //! Set all bits low
    output logic                     [31: 0] test3_test2_q,              //! Current field value

    // Register TEST4
    input  logic                     [31: 0] test4_test3_wdata,          //! HW write data

    // Register TEST5
    input  logic                             test5_test3_we,             //! Control HW write (active high)
    input  logic                     [31: 0] test5_test3_wdata,          //! HW write data

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [31: 0] test1_test1_next;
    logic                             test1_test1_anded;
    logic                             test1_test1_ored;
    logic                             test1_test1_xored;
    logic                           [31: 0] test2_test2_next;
    logic                             test2_test2_anded;
    logic                             test2_test2_ored;
    logic                             test2_test2_xored;
    logic                           [31: 0] test3_test2_next;
    logic                             test3_test2_anded;
    logic                             test3_test2_ored;
    logic                             test3_test2_xored;
    logic                           [31: 0] test4_test3_q;
    logic                           [31: 0] test4_test3_next;
    logic                             test4_test3_anded;
    logic                             test4_test3_ored;
    logic                             test4_test3_xored;
    logic                           [31: 0] test5_test3_q;
    logic                           [31: 0] test5_test3_next;
    logic                             test5_test3_anded;
    logic                             test5_test3_ored;
    logic                             test5_test3_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [DATA_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] test1_rdata;
    logic                     [DATA_WIDTH-1:0] test2_rdata;
    logic                     [DATA_WIDTH-1:0] test3_rdata;
    logic                     [DATA_WIDTH-1:0] test4_rdata;
    logic                     [DATA_WIDTH-1:0] test5_rdata;

    assign sw_rdata = // or of each register return (masked)
                   test1_rdata | 
                   test2_rdata | 
                   test3_rdata | 
                   test4_rdata | 
                   test5_rdata;
            
        
    // ============================================================
    // Register: TEST1
    //    [31: 0]                test1: hw=r     sw=rw    reset=0x0
    // ============================================================
    logic                  test1_decode;
    logic                  test1_sw_wr;
    logic                  test1_sw_rd;
    logic [DATA_WIDTH-1:0] test1_q;

    assign test1_decode = (addr == (ADDR_OFFSET+'h0+'h4));
    assign test1_sw_wr = sw_wr && test1_decode;
    assign test1_sw_rd = sw_rd && test1_decode;

    always_comb begin
        test1_q = '0;
        test1_q[31: 0] = test1_test1_q;
    end

    // masked version of return data
    assign test1_rdata = test1_sw_rd ? test1_q : 'b0;

    // ------------------------------------------------------------
    // Field: test1
    // ------------------------------------------------------------
    assign test1_test1_anded = & test1_test1_q;
    assign test1_test1_ored  = | test1_test1_q;
    assign test1_test1_xored = ^ test1_test1_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        test1_test1_q <= 0;
    end else begin
        // Software write
        if (test1_sw_wr) begin
            test1_test1_q <=  sw_masked_data[31: 0] | (test1_test1_q & ~sw_mask[31: 0]);
        end
    end
            
        
    // ============================================================
    // Register: TEST2
    //    [31: 0]                test2: hw=r     sw=rw    reset=0x0
    // ============================================================
    logic                  test2_decode;
    logic                  test2_sw_wr;
    logic                  test2_sw_rd;
    logic [DATA_WIDTH-1:0] test2_q;

    assign test2_decode = (addr == (ADDR_OFFSET+'h0+'h8));
    assign test2_sw_wr = sw_wr && test2_decode;
    assign test2_sw_rd = sw_rd && test2_decode;

    always_comb begin
        test2_q = '0;
        test2_q[31: 0] = test2_test2_q;
    end

    // masked version of return data
    assign test2_rdata = test2_sw_rd ? test2_q : 'b0;

    // ------------------------------------------------------------
    // Field: test2
    // ------------------------------------------------------------
    assign test2_test2_anded = & test2_test2_q;
    assign test2_test2_ored  = | test2_test2_q;
    assign test2_test2_xored = ^ test2_test2_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        test2_test2_q <= 0;
        test2_test2_swmod <= 1'b0;
    end else begin
        test2_test2_swmod <= 1'b0;
        // Software write
        if (test2_sw_wr) begin
            test2_test2_swmod <= 1'b1;
            test2_test2_q <=  sw_masked_data[31: 0] | (test2_test2_q & ~sw_mask[31: 0]);
        end
    end
            
        
    // ============================================================
    // Register: TEST3
    //    [31: 0]                test2: hw=r     sw=rw    reset=0x0
    // ============================================================
    logic                  test3_decode;
    logic                  test3_sw_wr;
    logic                  test3_sw_rd;
    logic [DATA_WIDTH-1:0] test3_q;

    assign test3_decode = (addr == (ADDR_OFFSET+'h0+'hc));
    assign test3_sw_wr = sw_wr && test3_decode;
    assign test3_sw_rd = sw_rd && test3_decode;

    always_comb begin
        test3_q = '0;
        test3_q[31: 0] = test3_test2_q;
    end

    // masked version of return data
    assign test3_rdata = test3_sw_rd ? test3_q : 'b0;

    // ------------------------------------------------------------
    // Field: test2
    // ------------------------------------------------------------
    assign test3_test2_anded = & test3_test2_q;
    assign test3_test2_ored  = | test3_test2_q;
    assign test3_test2_xored = ^ test3_test2_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        test3_test2_q <= 0;
    end else begin
        // Hardware Clear
        if (test3_test2_hwclr) begin
            test3_test2_q <= { 32 {1'b0} };
        end
        // Software write
        if (test3_sw_wr) begin
            test3_test2_q <=  sw_masked_data[31: 0] | (test3_test2_q & ~sw_mask[31: 0]);
        end
    end
            
        
    // ============================================================
    // Register: TEST4
    //    [31: 0]                test3: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  test4_decode;
    logic                  test4_sw_wr;
    logic                  test4_sw_rd;
    logic [DATA_WIDTH-1:0] test4_q;

    assign test4_decode = (addr == (ADDR_OFFSET+'h0+'h10));
    assign test4_sw_wr = sw_wr && test4_decode;
    assign test4_sw_rd = sw_rd && test4_decode;

    always_comb begin
        test4_q = '0;
        test4_q[31: 0] = test4_test3_q;
    end

    // masked version of return data
    assign test4_rdata = test4_sw_rd ? test4_q : 'b0;

    // ------------------------------------------------------------
    // Field: test3 (wire)
    // ------------------------------------------------------------
    assign test4_test3_anded = & test4_test3_q;
    assign test4_test3_ored  = | test4_test3_q;
    assign test4_test3_xored = ^ test4_test3_q;

    // next hardware value
    assign test4_test3_next = test4_test3_wdata;
    assign test4_test3_q = test4_test3_next;
            
        
    // ============================================================
    // Register: TEST5
    //    [31: 0]                test3: hw=w     sw=rw    reset=0x0
    // ============================================================
    logic                  test5_decode;
    logic                  test5_sw_wr;
    logic                  test5_sw_rd;
    logic [DATA_WIDTH-1:0] test5_q;

    assign test5_decode = (addr == (ADDR_OFFSET+'h0+'h14));
    assign test5_sw_wr = sw_wr && test5_decode;
    assign test5_sw_rd = sw_rd && test5_decode;

    always_comb begin
        test5_q = '0;
        test5_q[31: 0] = test5_test3_q;
    end

    // masked version of return data
    assign test5_rdata = test5_sw_rd ? test5_q : 'b0;

    // ------------------------------------------------------------
    // Field: test3
    // ------------------------------------------------------------
    assign test5_test3_anded = & test5_test3_q;
    assign test5_test3_ored  = | test5_test3_q;
    assign test5_test3_xored = ^ test5_test3_q;

    // next hardware value
    assign test5_test3_next = test5_test3_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        test5_test3_q <= 0;
    end else begin
        // Hardware Write
        if (test5_test3_we) begin
            test5_test3_q <= test5_test3_next;
        end
        // Software write
        if (test5_sw_wr) begin
            test5_test3_q <= ~sw_masked_data[31: 0] &  test5_test3_q;
        end
    end

endmodule: test
