// This file was autogenerated by PeakRDL-verilog
module tlp_adap_arbiter_reg_dfx #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register ARBITER_SCH_WEIGHT_WR
    output logic                     [63: 0] arbiter_sch_weight_wr_arbiter_sch_weight_wr_q,              //! Current field value

    // Register ARBITER_SCH_WEIGHT_RD
    output logic                     [63: 0] arbiter_sch_weight_rd_arbiter_sch_weight_rd_q,              //! Current field value

    // Register MAX_SHAPING_TOKEN
    output logic                     [11: 0] max_shaping_token_max_shaping_token_q,              //! Current field value

    // Register ARBITER_ERR
    input  logic                             arbiter_err_arbiter_err_we,             //! Control HW write (active high)
    input  logic                     [63: 0] arbiter_err_arbiter_err_wdata,          //! HW write data
    output logic                     [63: 0] arbiter_err_arbiter_err_q,              //! Current field value

    // Register ARBITER_STATUS
    input  logic                     [63: 0] arbiter_status_arbiter_status_wdata,          //! HW write data

    // Register ARBITER_CNT
    input  logic                             arbiter_cnt_arbiter_cnt_we,             //! Control HW write (active high)
    input  logic                     [63: 0] arbiter_cnt_arbiter_cnt_wdata,          //! HW write data
    output logic                     [63: 0] arbiter_cnt_arbiter_cnt_q,              //! Current field value

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [63: 0] arbiter_sch_weight_wr_arbiter_sch_weight_wr_next;
    logic                             arbiter_sch_weight_wr_arbiter_sch_weight_wr_anded;
    logic                             arbiter_sch_weight_wr_arbiter_sch_weight_wr_ored;
    logic                             arbiter_sch_weight_wr_arbiter_sch_weight_wr_xored;
    logic                           [63: 0] arbiter_sch_weight_rd_arbiter_sch_weight_rd_next;
    logic                             arbiter_sch_weight_rd_arbiter_sch_weight_rd_anded;
    logic                             arbiter_sch_weight_rd_arbiter_sch_weight_rd_ored;
    logic                             arbiter_sch_weight_rd_arbiter_sch_weight_rd_xored;
    logic                           [11: 0] max_shaping_token_max_shaping_token_next;
    logic                             max_shaping_token_max_shaping_token_anded;
    logic                             max_shaping_token_max_shaping_token_ored;
    logic                             max_shaping_token_max_shaping_token_xored;
    logic                           [63: 0] arbiter_err_arbiter_err_next;
    logic                             arbiter_err_arbiter_err_anded;
    logic                             arbiter_err_arbiter_err_ored;
    logic                             arbiter_err_arbiter_err_xored;
    logic                           [63: 0] arbiter_status_arbiter_status_q;
    logic                           [63: 0] arbiter_status_arbiter_status_next;
    logic                             arbiter_status_arbiter_status_anded;
    logic                             arbiter_status_arbiter_status_ored;
    logic                             arbiter_status_arbiter_status_xored;
    logic                           [63: 0] arbiter_cnt_arbiter_cnt_next;
    logic                             arbiter_cnt_arbiter_cnt_anded;
    logic                             arbiter_cnt_arbiter_cnt_ored;
    logic                             arbiter_cnt_arbiter_cnt_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [ADDR_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] arbiter_sch_weight_wr_rdata;
    logic                     [DATA_WIDTH-1:0] arbiter_sch_weight_rd_rdata;
    logic                     [DATA_WIDTH-1:0] max_shaping_token_rdata;
    logic                     [DATA_WIDTH-1:0] arbiter_err_rdata;
    logic                     [DATA_WIDTH-1:0] arbiter_status_rdata;
    logic                     [DATA_WIDTH-1:0] arbiter_cnt_rdata;

    assign sw_rdata = // or of each register return (masked)
                   arbiter_sch_weight_wr_rdata | 
                   arbiter_sch_weight_rd_rdata | 
                   max_shaping_token_rdata | 
                   arbiter_err_rdata | 
                   arbiter_status_rdata | 
                   arbiter_cnt_rdata;
            
        
    // ============================================================
    // Register: ARBITER_SCH_WEIGHT_WR
    //    [63: 0] arbiter_sch_weight_wr: hw=r     sw=rw    reset=0x1111111111111118
    // ============================================================
    logic                  arbiter_sch_weight_wr_decode;
    logic                  arbiter_sch_weight_wr_sw_wr;
    logic                  arbiter_sch_weight_wr_sw_rd;
    logic [DATA_WIDTH-1:0] arbiter_sch_weight_wr_q;

    assign arbiter_sch_weight_wr_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign arbiter_sch_weight_wr_sw_wr = sw_wr && arbiter_sch_weight_wr_decode;
    assign arbiter_sch_weight_wr_sw_rd = sw_rd && arbiter_sch_weight_wr_decode;

    always_comb begin
        arbiter_sch_weight_wr_q = '0;
        arbiter_sch_weight_wr_q[63: 0] = arbiter_sch_weight_wr_arbiter_sch_weight_wr_q;
    end

    // masked version of return data
    assign arbiter_sch_weight_wr_rdata = arbiter_sch_weight_wr_sw_rd ? arbiter_sch_weight_wr_q : 'b0;

    // ------------------------------------------------------------
    // Field: arbiter_sch_weight_wr
    // ------------------------------------------------------------
    assign arbiter_sch_weight_wr_arbiter_sch_weight_wr_anded = & arbiter_sch_weight_wr_arbiter_sch_weight_wr_q;
    assign arbiter_sch_weight_wr_arbiter_sch_weight_wr_ored  = | arbiter_sch_weight_wr_arbiter_sch_weight_wr_q;
    assign arbiter_sch_weight_wr_arbiter_sch_weight_wr_xored = ^ arbiter_sch_weight_wr_arbiter_sch_weight_wr_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        arbiter_sch_weight_wr_arbiter_sch_weight_wr_q <= 64'd1229782938247303448;
    end else begin
        // Software write
        if (arbiter_sch_weight_wr_sw_wr) begin
            arbiter_sch_weight_wr_arbiter_sch_weight_wr_q <=  sw_masked_data[63: 0] | (arbiter_sch_weight_wr_arbiter_sch_weight_wr_q & ~sw_mask[63: 0]);
        end
    end
            
        
    // ============================================================
    // Register: ARBITER_SCH_WEIGHT_RD
    //    [63: 0] arbiter_sch_weight_rd: hw=r     sw=rw    reset=0x1111111111111111
    // ============================================================
    logic                  arbiter_sch_weight_rd_decode;
    logic                  arbiter_sch_weight_rd_sw_wr;
    logic                  arbiter_sch_weight_rd_sw_rd;
    logic [DATA_WIDTH-1:0] arbiter_sch_weight_rd_q;

    assign arbiter_sch_weight_rd_decode = (addr == (ADDR_OFFSET+'h0+'h8));
    assign arbiter_sch_weight_rd_sw_wr = sw_wr && arbiter_sch_weight_rd_decode;
    assign arbiter_sch_weight_rd_sw_rd = sw_rd && arbiter_sch_weight_rd_decode;

    always_comb begin
        arbiter_sch_weight_rd_q = '0;
        arbiter_sch_weight_rd_q[63: 0] = arbiter_sch_weight_rd_arbiter_sch_weight_rd_q;
    end

    // masked version of return data
    assign arbiter_sch_weight_rd_rdata = arbiter_sch_weight_rd_sw_rd ? arbiter_sch_weight_rd_q : 'b0;

    // ------------------------------------------------------------
    // Field: arbiter_sch_weight_rd
    // ------------------------------------------------------------
    assign arbiter_sch_weight_rd_arbiter_sch_weight_rd_anded = & arbiter_sch_weight_rd_arbiter_sch_weight_rd_q;
    assign arbiter_sch_weight_rd_arbiter_sch_weight_rd_ored  = | arbiter_sch_weight_rd_arbiter_sch_weight_rd_q;
    assign arbiter_sch_weight_rd_arbiter_sch_weight_rd_xored = ^ arbiter_sch_weight_rd_arbiter_sch_weight_rd_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        arbiter_sch_weight_rd_arbiter_sch_weight_rd_q <= 64'd1229782938247303441;
    end else begin
        // Software write
        if (arbiter_sch_weight_rd_sw_wr) begin
            arbiter_sch_weight_rd_arbiter_sch_weight_rd_q <=  sw_masked_data[63: 0] | (arbiter_sch_weight_rd_arbiter_sch_weight_rd_q & ~sw_mask[63: 0]);
        end
    end
            
        
    // ============================================================
    // Register: MAX_SHAPING_TOKEN
    //    [11: 0]    max_shaping_token: hw=r     sw=rw    reset=0x100
    // ============================================================
    logic                  max_shaping_token_decode;
    logic                  max_shaping_token_sw_wr;
    logic                  max_shaping_token_sw_rd;
    logic [DATA_WIDTH-1:0] max_shaping_token_q;

    assign max_shaping_token_decode = (addr == (ADDR_OFFSET+'h0+'h10));
    assign max_shaping_token_sw_wr = sw_wr && max_shaping_token_decode;
    assign max_shaping_token_sw_rd = sw_rd && max_shaping_token_decode;

    always_comb begin
        max_shaping_token_q = '0;
        max_shaping_token_q[11: 0] = max_shaping_token_max_shaping_token_q;
    end

    // masked version of return data
    assign max_shaping_token_rdata = max_shaping_token_sw_rd ? max_shaping_token_q : 'b0;

    // ------------------------------------------------------------
    // Field: max_shaping_token
    // ------------------------------------------------------------
    assign max_shaping_token_max_shaping_token_anded = & max_shaping_token_max_shaping_token_q;
    assign max_shaping_token_max_shaping_token_ored  = | max_shaping_token_max_shaping_token_q;
    assign max_shaping_token_max_shaping_token_xored = ^ max_shaping_token_max_shaping_token_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        max_shaping_token_max_shaping_token_q <= 64'd256;
    end else begin
        // Software write
        if (max_shaping_token_sw_wr) begin
            max_shaping_token_max_shaping_token_q <=  sw_masked_data[11: 0] | (max_shaping_token_max_shaping_token_q & ~sw_mask[11: 0]);
        end
    end
            
        
    // ============================================================
    // Register: ARBITER_ERR
    //    [63: 0]          arbiter_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  arbiter_err_decode;
    logic                  arbiter_err_sw_wr;
    logic                  arbiter_err_sw_rd;
    logic [DATA_WIDTH-1:0] arbiter_err_q;

    assign arbiter_err_decode = (addr == (ADDR_OFFSET+'h0+'h80));
    assign arbiter_err_sw_wr = sw_wr && arbiter_err_decode;
    assign arbiter_err_sw_rd = sw_rd && arbiter_err_decode;

    always_comb begin
        arbiter_err_q = '0;
        arbiter_err_q[63: 0] = arbiter_err_arbiter_err_q;
    end

    // masked version of return data
    assign arbiter_err_rdata = arbiter_err_sw_rd ? arbiter_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: arbiter_err
    // ------------------------------------------------------------
    assign arbiter_err_arbiter_err_anded = & arbiter_err_arbiter_err_q;
    assign arbiter_err_arbiter_err_ored  = | arbiter_err_arbiter_err_q;
    assign arbiter_err_arbiter_err_xored = ^ arbiter_err_arbiter_err_q;

    // next hardware value
    assign arbiter_err_arbiter_err_next = arbiter_err_arbiter_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        arbiter_err_arbiter_err_q <= 64'd0;
    end else begin
        // Hardware Write
        if (arbiter_err_arbiter_err_we) begin
            arbiter_err_arbiter_err_q <= arbiter_err_arbiter_err_next;
        end
        // Software write
        else if (arbiter_err_sw_wr) begin
            arbiter_err_arbiter_err_q <= ~sw_masked_data[63: 0] &  arbiter_err_arbiter_err_q;
        end
    end
            
        
    // ============================================================
    // Register: ARBITER_STATUS
    //    [63: 0]       arbiter_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  arbiter_status_decode;
    logic                  arbiter_status_sw_wr;
    logic                  arbiter_status_sw_rd;
    logic [DATA_WIDTH-1:0] arbiter_status_q;

    assign arbiter_status_decode = (addr == (ADDR_OFFSET+'h0+'h100));
    assign arbiter_status_sw_wr = sw_wr && arbiter_status_decode;
    assign arbiter_status_sw_rd = sw_rd && arbiter_status_decode;

    always_comb begin
        arbiter_status_q = '0;
        arbiter_status_q[63: 0] = arbiter_status_arbiter_status_q;
    end

    // masked version of return data
    assign arbiter_status_rdata = arbiter_status_sw_rd ? arbiter_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: arbiter_status (wire)
    // ------------------------------------------------------------
    assign arbiter_status_arbiter_status_anded = & arbiter_status_arbiter_status_q;
    assign arbiter_status_arbiter_status_ored  = | arbiter_status_arbiter_status_q;
    assign arbiter_status_arbiter_status_xored = ^ arbiter_status_arbiter_status_q;

    // next hardware value
    assign arbiter_status_arbiter_status_next = arbiter_status_arbiter_status_wdata;
    assign arbiter_status_arbiter_status_q = arbiter_status_arbiter_status_next;
            
        
    // ============================================================
    // Register: ARBITER_CNT
    //    [63: 0]          arbiter_cnt: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  arbiter_cnt_decode;
    logic                  arbiter_cnt_sw_wr;
    logic                  arbiter_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] arbiter_cnt_q;

    assign arbiter_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h200));
    assign arbiter_cnt_sw_wr = sw_wr && arbiter_cnt_decode;
    assign arbiter_cnt_sw_rd = sw_rd && arbiter_cnt_decode;

    always_comb begin
        arbiter_cnt_q = '0;
        arbiter_cnt_q[63: 0] = arbiter_cnt_arbiter_cnt_q;
    end

    // masked version of return data
    assign arbiter_cnt_rdata = arbiter_cnt_sw_rd ? arbiter_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: arbiter_cnt
    // ------------------------------------------------------------
    assign arbiter_cnt_arbiter_cnt_anded = & arbiter_cnt_arbiter_cnt_q;
    assign arbiter_cnt_arbiter_cnt_ored  = | arbiter_cnt_arbiter_cnt_q;
    assign arbiter_cnt_arbiter_cnt_xored = ^ arbiter_cnt_arbiter_cnt_q;

    // next hardware value
    assign arbiter_cnt_arbiter_cnt_next = arbiter_cnt_arbiter_cnt_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        arbiter_cnt_arbiter_cnt_q <= 64'd0;
    end else begin
        // Hardware Write
        if (arbiter_cnt_arbiter_cnt_we) begin
            arbiter_cnt_arbiter_cnt_q <= arbiter_cnt_arbiter_cnt_next;
        end
        // Software write
        else if (arbiter_cnt_sw_wr) begin
            arbiter_cnt_arbiter_cnt_q <= ~sw_masked_data[63: 0] &  arbiter_cnt_arbiter_cnt_q;
        end
    end

endmodule: tlp_adap_arbiter_reg_dfx
