// This file was autogenerated by PeakRDL-verilog
module beq_rxq_dfx #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register DFX_ERR
    input  logic                             dfx_err_dfx_err_we,             //! Control HW write (active high)
    input  logic                     [40: 0] dfx_err_dfx_err_wdata,          //! HW write data
    output logic                     [40: 0] dfx_err_dfx_err_q,              //! Current field value

    // Register DFX_STATUS
    input  logic                     [44: 0] dfx_status_dfx_status_wdata,          //! HW write data

    // Register DFX_STATUS_QID
    input  logic                     [31: 0] dfx_status_qid_dfx_status_qid_wdata,          //! HW write data

    // Register BEQ2USER_CNT
    input  logic                     [31: 0] beq2user_cnt_beq2user_cnt_wdata,          //! HW write data

    // Register DMA_CNT
    input  logic                     [23: 0] dma_cnt_dma_cnt_wdata,          //! HW write data

    // Register RD_NDESC_CNT
    input  logic                     [39: 0] rd_ndesc_cnt_rd_ndesc_cnt_wdata,          //! HW write data

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [40: 0] dfx_err_dfx_err_next;
    logic                             dfx_err_dfx_err_anded;
    logic                             dfx_err_dfx_err_ored;
    logic                             dfx_err_dfx_err_xored;
    logic                           [44: 0] dfx_status_dfx_status_q;
    logic                           [44: 0] dfx_status_dfx_status_next;
    logic                             dfx_status_dfx_status_anded;
    logic                             dfx_status_dfx_status_ored;
    logic                             dfx_status_dfx_status_xored;
    logic                           [31: 0] dfx_status_qid_dfx_status_qid_q;
    logic                           [31: 0] dfx_status_qid_dfx_status_qid_next;
    logic                             dfx_status_qid_dfx_status_qid_anded;
    logic                             dfx_status_qid_dfx_status_qid_ored;
    logic                             dfx_status_qid_dfx_status_qid_xored;
    logic                           [31: 0] beq2user_cnt_beq2user_cnt_q;
    logic                           [31: 0] beq2user_cnt_beq2user_cnt_next;
    logic                             beq2user_cnt_beq2user_cnt_anded;
    logic                             beq2user_cnt_beq2user_cnt_ored;
    logic                             beq2user_cnt_beq2user_cnt_xored;
    logic                           [23: 0] dma_cnt_dma_cnt_q;
    logic                           [23: 0] dma_cnt_dma_cnt_next;
    logic                             dma_cnt_dma_cnt_anded;
    logic                             dma_cnt_dma_cnt_ored;
    logic                             dma_cnt_dma_cnt_xored;
    logic                           [39: 0] rd_ndesc_cnt_rd_ndesc_cnt_q;
    logic                           [39: 0] rd_ndesc_cnt_rd_ndesc_cnt_next;
    logic                             rd_ndesc_cnt_rd_ndesc_cnt_anded;
    logic                             rd_ndesc_cnt_rd_ndesc_cnt_ored;
    logic                             rd_ndesc_cnt_rd_ndesc_cnt_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [ADDR_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] dfx_err_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_status_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_status_qid_rdata;
    logic                     [DATA_WIDTH-1:0] beq2user_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dma_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] rd_ndesc_cnt_rdata;

    assign sw_rdata = // or of each register return (masked)
                   dfx_err_rdata | 
                   dfx_status_rdata | 
                   dfx_status_qid_rdata | 
                   beq2user_cnt_rdata | 
                   dma_cnt_rdata | 
                   rd_ndesc_cnt_rdata;
            
        
    // ============================================================
    // Register: DFX_ERR
    //    [40: 0]              dfx_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  dfx_err_decode;
    logic                  dfx_err_sw_wr;
    logic                  dfx_err_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_err_q;

    assign dfx_err_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign dfx_err_sw_wr = sw_wr && dfx_err_decode;
    assign dfx_err_sw_rd = sw_rd && dfx_err_decode;

    always_comb begin
        dfx_err_q = '0;
        dfx_err_q[40: 0] = dfx_err_dfx_err_q;
    end

    // masked version of return data
    assign dfx_err_rdata = dfx_err_sw_rd ? dfx_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_err
    // ------------------------------------------------------------
    assign dfx_err_dfx_err_anded = & dfx_err_dfx_err_q;
    assign dfx_err_dfx_err_ored  = | dfx_err_dfx_err_q;
    assign dfx_err_dfx_err_xored = ^ dfx_err_dfx_err_q;

    // next hardware value
    assign dfx_err_dfx_err_next = dfx_err_dfx_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        dfx_err_dfx_err_q <= 0;
    end else begin
        // Hardware Write
        if (dfx_err_dfx_err_we) begin
            dfx_err_dfx_err_q <= dfx_err_dfx_err_next;
        end
        // Software write
        else if (dfx_err_sw_wr) begin
            dfx_err_dfx_err_q <= ~sw_masked_data[40: 0] &  dfx_err_dfx_err_q;
        end
    end
            
        
    // ============================================================
    // Register: DFX_STATUS
    //    [44: 0]           dfx_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_status_decode;
    logic                  dfx_status_sw_wr;
    logic                  dfx_status_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_status_q;

    assign dfx_status_decode = (addr == (ADDR_OFFSET+'h0+'h40));
    assign dfx_status_sw_wr = sw_wr && dfx_status_decode;
    assign dfx_status_sw_rd = sw_rd && dfx_status_decode;

    always_comb begin
        dfx_status_q = '0;
        dfx_status_q[44: 0] = dfx_status_dfx_status_q;
    end

    // masked version of return data
    assign dfx_status_rdata = dfx_status_sw_rd ? dfx_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_status (wire)
    // ------------------------------------------------------------
    assign dfx_status_dfx_status_anded = & dfx_status_dfx_status_q;
    assign dfx_status_dfx_status_ored  = | dfx_status_dfx_status_q;
    assign dfx_status_dfx_status_xored = ^ dfx_status_dfx_status_q;

    // next hardware value
    assign dfx_status_dfx_status_next = dfx_status_dfx_status_wdata;
    assign dfx_status_dfx_status_q = dfx_status_dfx_status_next;
            
        
    // ============================================================
    // Register: DFX_STATUS_QID
    //    [31: 0]       dfx_status_qid: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_status_qid_decode;
    logic                  dfx_status_qid_sw_wr;
    logic                  dfx_status_qid_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_status_qid_q;

    assign dfx_status_qid_decode = (addr == (ADDR_OFFSET+'h0+'h48));
    assign dfx_status_qid_sw_wr = sw_wr && dfx_status_qid_decode;
    assign dfx_status_qid_sw_rd = sw_rd && dfx_status_qid_decode;

    always_comb begin
        dfx_status_qid_q = '0;
        dfx_status_qid_q[31: 0] = dfx_status_qid_dfx_status_qid_q;
    end

    // masked version of return data
    assign dfx_status_qid_rdata = dfx_status_qid_sw_rd ? dfx_status_qid_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_status_qid (wire)
    // ------------------------------------------------------------
    assign dfx_status_qid_dfx_status_qid_anded = & dfx_status_qid_dfx_status_qid_q;
    assign dfx_status_qid_dfx_status_qid_ored  = | dfx_status_qid_dfx_status_qid_q;
    assign dfx_status_qid_dfx_status_qid_xored = ^ dfx_status_qid_dfx_status_qid_q;

    // next hardware value
    assign dfx_status_qid_dfx_status_qid_next = dfx_status_qid_dfx_status_qid_wdata;
    assign dfx_status_qid_dfx_status_qid_q = dfx_status_qid_dfx_status_qid_next;
            
        
    // ============================================================
    // Register: BEQ2USER_CNT
    //    [31: 0]         beq2user_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  beq2user_cnt_decode;
    logic                  beq2user_cnt_sw_wr;
    logic                  beq2user_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] beq2user_cnt_q;

    assign beq2user_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h100));
    assign beq2user_cnt_sw_wr = sw_wr && beq2user_cnt_decode;
    assign beq2user_cnt_sw_rd = sw_rd && beq2user_cnt_decode;

    always_comb begin
        beq2user_cnt_q = '0;
        beq2user_cnt_q[31: 0] = beq2user_cnt_beq2user_cnt_q;
    end

    // masked version of return data
    assign beq2user_cnt_rdata = beq2user_cnt_sw_rd ? beq2user_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: beq2user_cnt (wire)
    // ------------------------------------------------------------
    assign beq2user_cnt_beq2user_cnt_anded = & beq2user_cnt_beq2user_cnt_q;
    assign beq2user_cnt_beq2user_cnt_ored  = | beq2user_cnt_beq2user_cnt_q;
    assign beq2user_cnt_beq2user_cnt_xored = ^ beq2user_cnt_beq2user_cnt_q;

    // next hardware value
    assign beq2user_cnt_beq2user_cnt_next = beq2user_cnt_beq2user_cnt_wdata;
    assign beq2user_cnt_beq2user_cnt_q = beq2user_cnt_beq2user_cnt_next;
            
        
    // ============================================================
    // Register: DMA_CNT
    //    [23: 0]              dma_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dma_cnt_decode;
    logic                  dma_cnt_sw_wr;
    logic                  dma_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dma_cnt_q;

    assign dma_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h108));
    assign dma_cnt_sw_wr = sw_wr && dma_cnt_decode;
    assign dma_cnt_sw_rd = sw_rd && dma_cnt_decode;

    always_comb begin
        dma_cnt_q = '0;
        dma_cnt_q[23: 0] = dma_cnt_dma_cnt_q;
    end

    // masked version of return data
    assign dma_cnt_rdata = dma_cnt_sw_rd ? dma_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dma_cnt (wire)
    // ------------------------------------------------------------
    assign dma_cnt_dma_cnt_anded = & dma_cnt_dma_cnt_q;
    assign dma_cnt_dma_cnt_ored  = | dma_cnt_dma_cnt_q;
    assign dma_cnt_dma_cnt_xored = ^ dma_cnt_dma_cnt_q;

    // next hardware value
    assign dma_cnt_dma_cnt_next = dma_cnt_dma_cnt_wdata;
    assign dma_cnt_dma_cnt_q = dma_cnt_dma_cnt_next;
            
        
    // ============================================================
    // Register: RD_NDESC_CNT
    //    [39: 0]         rd_ndesc_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  rd_ndesc_cnt_decode;
    logic                  rd_ndesc_cnt_sw_wr;
    logic                  rd_ndesc_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] rd_ndesc_cnt_q;

    assign rd_ndesc_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h110));
    assign rd_ndesc_cnt_sw_wr = sw_wr && rd_ndesc_cnt_decode;
    assign rd_ndesc_cnt_sw_rd = sw_rd && rd_ndesc_cnt_decode;

    always_comb begin
        rd_ndesc_cnt_q = '0;
        rd_ndesc_cnt_q[39: 0] = rd_ndesc_cnt_rd_ndesc_cnt_q;
    end

    // masked version of return data
    assign rd_ndesc_cnt_rdata = rd_ndesc_cnt_sw_rd ? rd_ndesc_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: rd_ndesc_cnt (wire)
    // ------------------------------------------------------------
    assign rd_ndesc_cnt_rd_ndesc_cnt_anded = & rd_ndesc_cnt_rd_ndesc_cnt_q;
    assign rd_ndesc_cnt_rd_ndesc_cnt_ored  = | rd_ndesc_cnt_rd_ndesc_cnt_q;
    assign rd_ndesc_cnt_rd_ndesc_cnt_xored = ^ rd_ndesc_cnt_rd_ndesc_cnt_q;

    // next hardware value
    assign rd_ndesc_cnt_rd_ndesc_cnt_next = rd_ndesc_cnt_rd_ndesc_cnt_wdata;
    assign rd_ndesc_cnt_rd_ndesc_cnt_q = rd_ndesc_cnt_rd_ndesc_cnt_next;

endmodule: beq_rxq_dfx
