// This file was autogenerated by PeakRDL-verilog
module dirty_log_dfx #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register DIRTY_LOG_STATUS
    input  logic                     [31: 0] dirty_log_status_dirty_log_status_wdata,          //! HW write data

    // Register DIRTY_LOG_ERR
    input  logic                     [31: 0] dirty_log_err_dirty_log_err_wdata,          //! HW write data

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [31: 0] dirty_log_status_dirty_log_status_q;
    logic                           [31: 0] dirty_log_status_dirty_log_status_next;
    logic                             dirty_log_status_dirty_log_status_anded;
    logic                             dirty_log_status_dirty_log_status_ored;
    logic                             dirty_log_status_dirty_log_status_xored;
    logic                           [31: 0] dirty_log_err_dirty_log_err_q;
    logic                           [31: 0] dirty_log_err_dirty_log_err_next;
    logic                             dirty_log_err_dirty_log_err_anded;
    logic                             dirty_log_err_dirty_log_err_ored;
    logic                             dirty_log_err_dirty_log_err_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [ADDR_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] dirty_log_status_rdata;
    logic                     [DATA_WIDTH-1:0] dirty_log_err_rdata;

    assign sw_rdata = // or of each register return (masked)
                   dirty_log_status_rdata | 
                   dirty_log_err_rdata;
            
        
    // ============================================================
    // Register: DIRTY_LOG_STATUS
    //    [31: 0]     dirty_log_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dirty_log_status_decode;
    logic                  dirty_log_status_sw_wr;
    logic                  dirty_log_status_sw_rd;
    logic [DATA_WIDTH-1:0] dirty_log_status_q;

    assign dirty_log_status_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign dirty_log_status_sw_wr = sw_wr && dirty_log_status_decode;
    assign dirty_log_status_sw_rd = sw_rd && dirty_log_status_decode;

    always_comb begin
        dirty_log_status_q = '0;
        dirty_log_status_q[31: 0] = dirty_log_status_dirty_log_status_q;
    end

    // masked version of return data
    assign dirty_log_status_rdata = dirty_log_status_sw_rd ? dirty_log_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: dirty_log_status (wire)
    // ------------------------------------------------------------
    assign dirty_log_status_dirty_log_status_anded = & dirty_log_status_dirty_log_status_q;
    assign dirty_log_status_dirty_log_status_ored  = | dirty_log_status_dirty_log_status_q;
    assign dirty_log_status_dirty_log_status_xored = ^ dirty_log_status_dirty_log_status_q;

    // next hardware value
    assign dirty_log_status_dirty_log_status_next = dirty_log_status_dirty_log_status_wdata;
    assign dirty_log_status_dirty_log_status_q = dirty_log_status_dirty_log_status_next;
            
        
    // ============================================================
    // Register: DIRTY_LOG_ERR
    //    [31: 0]        dirty_log_err: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dirty_log_err_decode;
    logic                  dirty_log_err_sw_wr;
    logic                  dirty_log_err_sw_rd;
    logic [DATA_WIDTH-1:0] dirty_log_err_q;

    assign dirty_log_err_decode = (addr == (ADDR_OFFSET+'h0+'h8));
    assign dirty_log_err_sw_wr = sw_wr && dirty_log_err_decode;
    assign dirty_log_err_sw_rd = sw_rd && dirty_log_err_decode;

    always_comb begin
        dirty_log_err_q = '0;
        dirty_log_err_q[31: 0] = dirty_log_err_dirty_log_err_q;
    end

    // masked version of return data
    assign dirty_log_err_rdata = dirty_log_err_sw_rd ? dirty_log_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: dirty_log_err (wire)
    // ------------------------------------------------------------
    assign dirty_log_err_dirty_log_err_anded = & dirty_log_err_dirty_log_err_q;
    assign dirty_log_err_dirty_log_err_ored  = | dirty_log_err_dirty_log_err_q;
    assign dirty_log_err_dirty_log_err_xored = ^ dirty_log_err_dirty_log_err_q;

    // next hardware value
    assign dirty_log_err_dirty_log_err_next = dirty_log_err_dirty_log_err_wdata;
    assign dirty_log_err_dirty_log_err_q = dirty_log_err_dirty_log_err_next;

endmodule: dirty_log_dfx
