// This file was autogenerated by PeakRDL-verilog
module virtio_desc_engine_dfx #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register SLOT_MGMT_TX_DFX_ERR
    input  logic                             slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_we,             //! Control HW write (active high)
    input  logic                     [27: 0] slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_wdata,          //! HW write data
    output logic                     [27: 0] slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_q,              //! Current field value

    // Register SLOT_MGMT_TX_DFX_STATUS
    input  logic                     [19: 0] slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_wdata,          //! HW write data

    // Register SLOT_MGMT_TX_ALLOC_SLOT_CNT
    input  logic                     [23: 0] slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_wdata,          //! HW write data

    // Register SLOT_MGMT_TX_AVAIL_ID_CNT
    input  logic                     [39: 0] slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_wdata,          //! HW write data

    // Register SLOT_MGMT_TX_SLOT_CNT
    input  logic                     [23: 0] slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_wdata,          //! HW write data

    // Register SLOT_MGMT_TX_RD_DESC_CNT
    input  logic                     [23: 0] slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_wdata,          //! HW write data

    // Register SLOT_MGMT_TX_DESC_CNT
    input  logic                     [23: 0] slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_wdata,          //! HW write data

    // Register SLOT_MGMT_RX_DFX_ERR
    input  logic                             slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_we,             //! Control HW write (active high)
    input  logic                     [27: 0] slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_wdata,          //! HW write data
    output logic                     [27: 0] slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_q,              //! Current field value

    // Register SLOT_MGMT_RX_DFX_STATUS
    input  logic                     [19: 0] slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_wdata,          //! HW write data

    // Register SLOT_MGMT_RX_ALLOC_SLOT_CNT
    input  logic                     [23: 0] slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_wdata,          //! HW write data

    // Register SLOT_MGMT_RX_AVAIL_ID_CNT
    input  logic                     [39: 0] slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_wdata,          //! HW write data

    // Register SLOT_MGMT_RX_SLOT_CNT
    input  logic                     [23: 0] slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_wdata,          //! HW write data

    // Register SLOT_MGMT_RX_RD_DESC_CNT
    input  logic                     [23: 0] slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_wdata,          //! HW write data

    // Register SLOT_MGMT_RX_DESC_CNT
    input  logic                     [23: 0] slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_wdata,          //! HW write data

    // Register CORE_RX_DFX_ERR
    input  logic                             core_rx_dfx_err_core_rx_dfx_err_we,             //! Control HW write (active high)
    input  logic                     [44: 0] core_rx_dfx_err_core_rx_dfx_err_wdata,          //! HW write data
    output logic                     [44: 0] core_rx_dfx_err_core_rx_dfx_err_q,              //! Current field value

    // Register CORE_RX_DFX_STATUS
    input  logic                     [62: 0] core_rx_dfx_status_core_rx_dfx_status_wdata,          //! HW write data

    // Register CORE_RX_DMA_CNT
    input  logic                     [15: 0] core_rx_dma_cnt_core_rx_dma_cnt_wdata,          //! HW write data

    // Register CORE_RX_SCH_OUT_CNT
    input  logic                     [23: 0] core_rx_sch_out_cnt_core_rx_sch_out_cnt_wdata,          //! HW write data

    // Register CORE_RX_DESC_BUF_CNT
    input  logic                     [15: 0] core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_wdata,          //! HW write data

    // Register CORE_RX_WAKE_UP_CNT
    input  logic                     [ 7: 0] core_rx_wake_up_cnt_core_rx_wake_up_cnt_wdata,          //! HW write data

    // Register CORE_TX_DFX_ERR
    input  logic                             core_tx_dfx_err_core_tx_dfx_err_we,             //! Control HW write (active high)
    input  logic                     [44: 0] core_tx_dfx_err_core_tx_dfx_err_wdata,          //! HW write data
    output logic                     [44: 0] core_tx_dfx_err_core_tx_dfx_err_q,              //! Current field value

    // Register CORE_TX_DFX_STATUS
    input  logic                     [62: 0] core_tx_dfx_status_core_tx_dfx_status_wdata,          //! HW write data

    // Register CORE_TX_DMA_CNT
    input  logic                     [15: 0] core_tx_dma_cnt_core_tx_dma_cnt_wdata,          //! HW write data

    // Register CORE_TX_SCH_OUT_CNT
    input  logic                     [23: 0] core_tx_sch_out_cnt_core_tx_sch_out_cnt_wdata,          //! HW write data

    // Register CORE_TX_DESC_BUF_CNT
    input  logic                     [15: 0] core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_wdata,          //! HW write data

    // Register CORE_TX_WAKE_UP_CNT
    input  logic                     [ 7: 0] core_tx_wake_up_cnt_core_tx_wake_up_cnt_wdata,          //! HW write data

    // Register RX_DMA_RD_REQ_CNT
    input  logic                     [63: 0] rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_wdata,          //! HW write data

    // Register RX_DMA_RD_RSP_CNT
    input  logic                     [31: 0] rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_wdata,          //! HW write data

    // Register TX_DMA_RD_REQ_CNT
    input  logic                     [63: 0] tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_wdata,          //! HW write data

    // Register TX_DMA_RD_RSP_CNT
    input  logic                     [31: 0] tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_wdata,          //! HW write data

    // Register USED_SLOT_NUM
    input  logic                     [31: 0] used_slot_num_used_slot_num_wdata,          //! HW write data

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [27: 0] slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_next;
    logic                             slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_anded;
    logic                             slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_ored;
    logic                             slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_xored;
    logic                           [19: 0] slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_q;
    logic                           [19: 0] slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_next;
    logic                             slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_anded;
    logic                             slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_ored;
    logic                             slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_xored;
    logic                           [23: 0] slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_q;
    logic                           [23: 0] slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_next;
    logic                             slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_anded;
    logic                             slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_ored;
    logic                             slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_xored;
    logic                           [39: 0] slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_q;
    logic                           [39: 0] slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_next;
    logic                             slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_anded;
    logic                             slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_ored;
    logic                             slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_xored;
    logic                           [23: 0] slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_q;
    logic                           [23: 0] slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_next;
    logic                             slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_anded;
    logic                             slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_ored;
    logic                             slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_xored;
    logic                           [23: 0] slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_q;
    logic                           [23: 0] slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_next;
    logic                             slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_anded;
    logic                             slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_ored;
    logic                             slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_xored;
    logic                           [23: 0] slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_q;
    logic                           [23: 0] slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_next;
    logic                             slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_anded;
    logic                             slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_ored;
    logic                             slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_xored;
    logic                           [27: 0] slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_next;
    logic                             slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_anded;
    logic                             slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_ored;
    logic                             slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_xored;
    logic                           [19: 0] slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_q;
    logic                           [19: 0] slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_next;
    logic                             slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_anded;
    logic                             slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_ored;
    logic                             slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_xored;
    logic                           [23: 0] slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_q;
    logic                           [23: 0] slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_next;
    logic                             slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_anded;
    logic                             slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_ored;
    logic                             slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_xored;
    logic                           [39: 0] slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_q;
    logic                           [39: 0] slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_next;
    logic                             slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_anded;
    logic                             slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_ored;
    logic                             slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_xored;
    logic                           [23: 0] slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_q;
    logic                           [23: 0] slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_next;
    logic                             slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_anded;
    logic                             slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_ored;
    logic                             slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_xored;
    logic                           [23: 0] slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_q;
    logic                           [23: 0] slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_next;
    logic                             slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_anded;
    logic                             slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_ored;
    logic                             slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_xored;
    logic                           [23: 0] slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_q;
    logic                           [23: 0] slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_next;
    logic                             slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_anded;
    logic                             slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_ored;
    logic                             slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_xored;
    logic                           [44: 0] core_rx_dfx_err_core_rx_dfx_err_next;
    logic                             core_rx_dfx_err_core_rx_dfx_err_anded;
    logic                             core_rx_dfx_err_core_rx_dfx_err_ored;
    logic                             core_rx_dfx_err_core_rx_dfx_err_xored;
    logic                           [62: 0] core_rx_dfx_status_core_rx_dfx_status_q;
    logic                           [62: 0] core_rx_dfx_status_core_rx_dfx_status_next;
    logic                             core_rx_dfx_status_core_rx_dfx_status_anded;
    logic                             core_rx_dfx_status_core_rx_dfx_status_ored;
    logic                             core_rx_dfx_status_core_rx_dfx_status_xored;
    logic                           [15: 0] core_rx_dma_cnt_core_rx_dma_cnt_q;
    logic                           [15: 0] core_rx_dma_cnt_core_rx_dma_cnt_next;
    logic                             core_rx_dma_cnt_core_rx_dma_cnt_anded;
    logic                             core_rx_dma_cnt_core_rx_dma_cnt_ored;
    logic                             core_rx_dma_cnt_core_rx_dma_cnt_xored;
    logic                           [23: 0] core_rx_sch_out_cnt_core_rx_sch_out_cnt_q;
    logic                           [23: 0] core_rx_sch_out_cnt_core_rx_sch_out_cnt_next;
    logic                             core_rx_sch_out_cnt_core_rx_sch_out_cnt_anded;
    logic                             core_rx_sch_out_cnt_core_rx_sch_out_cnt_ored;
    logic                             core_rx_sch_out_cnt_core_rx_sch_out_cnt_xored;
    logic                           [15: 0] core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_q;
    logic                           [15: 0] core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_next;
    logic                             core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_anded;
    logic                             core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_ored;
    logic                             core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_xored;
    logic                           [ 7: 0] core_rx_wake_up_cnt_core_rx_wake_up_cnt_q;
    logic                           [ 7: 0] core_rx_wake_up_cnt_core_rx_wake_up_cnt_next;
    logic                             core_rx_wake_up_cnt_core_rx_wake_up_cnt_anded;
    logic                             core_rx_wake_up_cnt_core_rx_wake_up_cnt_ored;
    logic                             core_rx_wake_up_cnt_core_rx_wake_up_cnt_xored;
    logic                           [44: 0] core_tx_dfx_err_core_tx_dfx_err_next;
    logic                             core_tx_dfx_err_core_tx_dfx_err_anded;
    logic                             core_tx_dfx_err_core_tx_dfx_err_ored;
    logic                             core_tx_dfx_err_core_tx_dfx_err_xored;
    logic                           [62: 0] core_tx_dfx_status_core_tx_dfx_status_q;
    logic                           [62: 0] core_tx_dfx_status_core_tx_dfx_status_next;
    logic                             core_tx_dfx_status_core_tx_dfx_status_anded;
    logic                             core_tx_dfx_status_core_tx_dfx_status_ored;
    logic                             core_tx_dfx_status_core_tx_dfx_status_xored;
    logic                           [15: 0] core_tx_dma_cnt_core_tx_dma_cnt_q;
    logic                           [15: 0] core_tx_dma_cnt_core_tx_dma_cnt_next;
    logic                             core_tx_dma_cnt_core_tx_dma_cnt_anded;
    logic                             core_tx_dma_cnt_core_tx_dma_cnt_ored;
    logic                             core_tx_dma_cnt_core_tx_dma_cnt_xored;
    logic                           [23: 0] core_tx_sch_out_cnt_core_tx_sch_out_cnt_q;
    logic                           [23: 0] core_tx_sch_out_cnt_core_tx_sch_out_cnt_next;
    logic                             core_tx_sch_out_cnt_core_tx_sch_out_cnt_anded;
    logic                             core_tx_sch_out_cnt_core_tx_sch_out_cnt_ored;
    logic                             core_tx_sch_out_cnt_core_tx_sch_out_cnt_xored;
    logic                           [15: 0] core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_q;
    logic                           [15: 0] core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_next;
    logic                             core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_anded;
    logic                             core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_ored;
    logic                             core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_xored;
    logic                           [ 7: 0] core_tx_wake_up_cnt_core_tx_wake_up_cnt_q;
    logic                           [ 7: 0] core_tx_wake_up_cnt_core_tx_wake_up_cnt_next;
    logic                             core_tx_wake_up_cnt_core_tx_wake_up_cnt_anded;
    logic                             core_tx_wake_up_cnt_core_tx_wake_up_cnt_ored;
    logic                             core_tx_wake_up_cnt_core_tx_wake_up_cnt_xored;
    logic                           [63: 0] rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_q;
    logic                           [63: 0] rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_next;
    logic                             rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_anded;
    logic                             rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_ored;
    logic                             rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_xored;
    logic                           [31: 0] rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_q;
    logic                           [31: 0] rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_next;
    logic                             rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_anded;
    logic                             rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_ored;
    logic                             rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_xored;
    logic                           [63: 0] tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_q;
    logic                           [63: 0] tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_next;
    logic                             tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_anded;
    logic                             tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_ored;
    logic                             tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_xored;
    logic                           [31: 0] tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_q;
    logic                           [31: 0] tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_next;
    logic                             tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_anded;
    logic                             tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_ored;
    logic                             tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_xored;
    logic                           [31: 0] used_slot_num_used_slot_num_q;
    logic                           [31: 0] used_slot_num_used_slot_num_next;
    logic                             used_slot_num_used_slot_num_anded;
    logic                             used_slot_num_used_slot_num_ored;
    logic                             used_slot_num_used_slot_num_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [ADDR_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_tx_dfx_err_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_tx_dfx_status_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_tx_alloc_slot_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_tx_avail_id_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_tx_slot_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_tx_rd_desc_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_tx_desc_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_rx_dfx_err_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_rx_dfx_status_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_rx_alloc_slot_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_rx_avail_id_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_rx_slot_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_rx_rd_desc_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] slot_mgmt_rx_desc_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] core_rx_dfx_err_rdata;
    logic                     [DATA_WIDTH-1:0] core_rx_dfx_status_rdata;
    logic                     [DATA_WIDTH-1:0] core_rx_dma_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] core_rx_sch_out_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] core_rx_desc_buf_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] core_rx_wake_up_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] core_tx_dfx_err_rdata;
    logic                     [DATA_WIDTH-1:0] core_tx_dfx_status_rdata;
    logic                     [DATA_WIDTH-1:0] core_tx_dma_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] core_tx_sch_out_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] core_tx_desc_buf_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] core_tx_wake_up_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] rx_dma_rd_req_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] rx_dma_rd_rsp_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] tx_dma_rd_req_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] tx_dma_rd_rsp_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] used_slot_num_rdata;

    assign sw_rdata = // or of each register return (masked)
                   slot_mgmt_tx_dfx_err_rdata | 
                   slot_mgmt_tx_dfx_status_rdata | 
                   slot_mgmt_tx_alloc_slot_cnt_rdata | 
                   slot_mgmt_tx_avail_id_cnt_rdata | 
                   slot_mgmt_tx_slot_cnt_rdata | 
                   slot_mgmt_tx_rd_desc_cnt_rdata | 
                   slot_mgmt_tx_desc_cnt_rdata | 
                   slot_mgmt_rx_dfx_err_rdata | 
                   slot_mgmt_rx_dfx_status_rdata | 
                   slot_mgmt_rx_alloc_slot_cnt_rdata | 
                   slot_mgmt_rx_avail_id_cnt_rdata | 
                   slot_mgmt_rx_slot_cnt_rdata | 
                   slot_mgmt_rx_rd_desc_cnt_rdata | 
                   slot_mgmt_rx_desc_cnt_rdata | 
                   core_rx_dfx_err_rdata | 
                   core_rx_dfx_status_rdata | 
                   core_rx_dma_cnt_rdata | 
                   core_rx_sch_out_cnt_rdata | 
                   core_rx_desc_buf_cnt_rdata | 
                   core_rx_wake_up_cnt_rdata | 
                   core_tx_dfx_err_rdata | 
                   core_tx_dfx_status_rdata | 
                   core_tx_dma_cnt_rdata | 
                   core_tx_sch_out_cnt_rdata | 
                   core_tx_desc_buf_cnt_rdata | 
                   core_tx_wake_up_cnt_rdata | 
                   rx_dma_rd_req_cnt_rdata | 
                   rx_dma_rd_rsp_cnt_rdata | 
                   tx_dma_rd_req_cnt_rdata | 
                   tx_dma_rd_rsp_cnt_rdata | 
                   used_slot_num_rdata;
            
        
    // ============================================================
    // Register: SLOT_MGMT_TX_DFX_ERR
    //    [27: 0] slot_mgmt_tx_dfx_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  slot_mgmt_tx_dfx_err_decode;
    logic                  slot_mgmt_tx_dfx_err_sw_wr;
    logic                  slot_mgmt_tx_dfx_err_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_tx_dfx_err_q;

    assign slot_mgmt_tx_dfx_err_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign slot_mgmt_tx_dfx_err_sw_wr = sw_wr && slot_mgmt_tx_dfx_err_decode;
    assign slot_mgmt_tx_dfx_err_sw_rd = sw_rd && slot_mgmt_tx_dfx_err_decode;

    always_comb begin
        slot_mgmt_tx_dfx_err_q = '0;
        slot_mgmt_tx_dfx_err_q[27: 0] = slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_q;
    end

    // masked version of return data
    assign slot_mgmt_tx_dfx_err_rdata = slot_mgmt_tx_dfx_err_sw_rd ? slot_mgmt_tx_dfx_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_tx_dfx_err
    // ------------------------------------------------------------
    assign slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_anded = & slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_q;
    assign slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_ored  = | slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_q;
    assign slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_xored = ^ slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_q;

    // next hardware value
    assign slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_next = slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_q <= 64'd0;
    end else begin
        // Hardware Write
        if (slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_we) begin
            slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_q <= slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_next;
        end
        // Software write
        else if (slot_mgmt_tx_dfx_err_sw_wr) begin
            slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_q <= ~sw_masked_data[27: 0] &  slot_mgmt_tx_dfx_err_slot_mgmt_tx_dfx_err_q;
        end
    end
            
        
    // ============================================================
    // Register: SLOT_MGMT_TX_DFX_STATUS
    //    [19: 0] slot_mgmt_tx_dfx_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_tx_dfx_status_decode;
    logic                  slot_mgmt_tx_dfx_status_sw_wr;
    logic                  slot_mgmt_tx_dfx_status_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_tx_dfx_status_q;

    assign slot_mgmt_tx_dfx_status_decode = (addr == (ADDR_OFFSET+'h0+'h8));
    assign slot_mgmt_tx_dfx_status_sw_wr = sw_wr && slot_mgmt_tx_dfx_status_decode;
    assign slot_mgmt_tx_dfx_status_sw_rd = sw_rd && slot_mgmt_tx_dfx_status_decode;

    always_comb begin
        slot_mgmt_tx_dfx_status_q = '0;
        slot_mgmt_tx_dfx_status_q[19: 0] = slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_q;
    end

    // masked version of return data
    assign slot_mgmt_tx_dfx_status_rdata = slot_mgmt_tx_dfx_status_sw_rd ? slot_mgmt_tx_dfx_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_tx_dfx_status (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_anded = & slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_q;
    assign slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_ored  = | slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_q;
    assign slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_xored = ^ slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_q;

    // next hardware value
    assign slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_next = slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_wdata;
    assign slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_q = slot_mgmt_tx_dfx_status_slot_mgmt_tx_dfx_status_next;
            
        
    // ============================================================
    // Register: SLOT_MGMT_TX_ALLOC_SLOT_CNT
    //    [23: 0] slot_mgmt_tx_alloc_slot_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_tx_alloc_slot_cnt_decode;
    logic                  slot_mgmt_tx_alloc_slot_cnt_sw_wr;
    logic                  slot_mgmt_tx_alloc_slot_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_tx_alloc_slot_cnt_q;

    assign slot_mgmt_tx_alloc_slot_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h30));
    assign slot_mgmt_tx_alloc_slot_cnt_sw_wr = sw_wr && slot_mgmt_tx_alloc_slot_cnt_decode;
    assign slot_mgmt_tx_alloc_slot_cnt_sw_rd = sw_rd && slot_mgmt_tx_alloc_slot_cnt_decode;

    always_comb begin
        slot_mgmt_tx_alloc_slot_cnt_q = '0;
        slot_mgmt_tx_alloc_slot_cnt_q[23: 0] = slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_q;
    end

    // masked version of return data
    assign slot_mgmt_tx_alloc_slot_cnt_rdata = slot_mgmt_tx_alloc_slot_cnt_sw_rd ? slot_mgmt_tx_alloc_slot_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_tx_alloc_slot_cnt (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_anded = & slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_q;
    assign slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_ored  = | slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_q;
    assign slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_xored = ^ slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_q;

    // next hardware value
    assign slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_next = slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_wdata;
    assign slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_q = slot_mgmt_tx_alloc_slot_cnt_slot_mgmt_tx_alloc_slot_cnt_next;
            
        
    // ============================================================
    // Register: SLOT_MGMT_TX_AVAIL_ID_CNT
    //    [39: 0] slot_mgmt_tx_avail_id_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_tx_avail_id_cnt_decode;
    logic                  slot_mgmt_tx_avail_id_cnt_sw_wr;
    logic                  slot_mgmt_tx_avail_id_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_tx_avail_id_cnt_q;

    assign slot_mgmt_tx_avail_id_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h38));
    assign slot_mgmt_tx_avail_id_cnt_sw_wr = sw_wr && slot_mgmt_tx_avail_id_cnt_decode;
    assign slot_mgmt_tx_avail_id_cnt_sw_rd = sw_rd && slot_mgmt_tx_avail_id_cnt_decode;

    always_comb begin
        slot_mgmt_tx_avail_id_cnt_q = '0;
        slot_mgmt_tx_avail_id_cnt_q[39: 0] = slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_q;
    end

    // masked version of return data
    assign slot_mgmt_tx_avail_id_cnt_rdata = slot_mgmt_tx_avail_id_cnt_sw_rd ? slot_mgmt_tx_avail_id_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_tx_avail_id_cnt (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_anded = & slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_q;
    assign slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_ored  = | slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_q;
    assign slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_xored = ^ slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_q;

    // next hardware value
    assign slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_next = slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_wdata;
    assign slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_q = slot_mgmt_tx_avail_id_cnt_slot_mgmt_tx_avail_id_cnt_next;
            
        
    // ============================================================
    // Register: SLOT_MGMT_TX_SLOT_CNT
    //    [23: 0] slot_mgmt_tx_slot_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_tx_slot_cnt_decode;
    logic                  slot_mgmt_tx_slot_cnt_sw_wr;
    logic                  slot_mgmt_tx_slot_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_tx_slot_cnt_q;

    assign slot_mgmt_tx_slot_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h40));
    assign slot_mgmt_tx_slot_cnt_sw_wr = sw_wr && slot_mgmt_tx_slot_cnt_decode;
    assign slot_mgmt_tx_slot_cnt_sw_rd = sw_rd && slot_mgmt_tx_slot_cnt_decode;

    always_comb begin
        slot_mgmt_tx_slot_cnt_q = '0;
        slot_mgmt_tx_slot_cnt_q[23: 0] = slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_q;
    end

    // masked version of return data
    assign slot_mgmt_tx_slot_cnt_rdata = slot_mgmt_tx_slot_cnt_sw_rd ? slot_mgmt_tx_slot_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_tx_slot_cnt (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_anded = & slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_q;
    assign slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_ored  = | slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_q;
    assign slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_xored = ^ slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_q;

    // next hardware value
    assign slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_next = slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_wdata;
    assign slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_q = slot_mgmt_tx_slot_cnt_slot_mgmt_tx_slot_cnt_next;
            
        
    // ============================================================
    // Register: SLOT_MGMT_TX_RD_DESC_CNT
    //    [23: 0] slot_mgmt_tx_rd_desc_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_tx_rd_desc_cnt_decode;
    logic                  slot_mgmt_tx_rd_desc_cnt_sw_wr;
    logic                  slot_mgmt_tx_rd_desc_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_tx_rd_desc_cnt_q;

    assign slot_mgmt_tx_rd_desc_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h48));
    assign slot_mgmt_tx_rd_desc_cnt_sw_wr = sw_wr && slot_mgmt_tx_rd_desc_cnt_decode;
    assign slot_mgmt_tx_rd_desc_cnt_sw_rd = sw_rd && slot_mgmt_tx_rd_desc_cnt_decode;

    always_comb begin
        slot_mgmt_tx_rd_desc_cnt_q = '0;
        slot_mgmt_tx_rd_desc_cnt_q[23: 0] = slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_q;
    end

    // masked version of return data
    assign slot_mgmt_tx_rd_desc_cnt_rdata = slot_mgmt_tx_rd_desc_cnt_sw_rd ? slot_mgmt_tx_rd_desc_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_tx_rd_desc_cnt (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_anded = & slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_q;
    assign slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_ored  = | slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_q;
    assign slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_xored = ^ slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_q;

    // next hardware value
    assign slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_next = slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_wdata;
    assign slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_q = slot_mgmt_tx_rd_desc_cnt_slot_mgmt_tx_rd_desc_cnt_next;
            
        
    // ============================================================
    // Register: SLOT_MGMT_TX_DESC_CNT
    //    [23: 0] slot_mgmt_tx_desc_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_tx_desc_cnt_decode;
    logic                  slot_mgmt_tx_desc_cnt_sw_wr;
    logic                  slot_mgmt_tx_desc_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_tx_desc_cnt_q;

    assign slot_mgmt_tx_desc_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h50));
    assign slot_mgmt_tx_desc_cnt_sw_wr = sw_wr && slot_mgmt_tx_desc_cnt_decode;
    assign slot_mgmt_tx_desc_cnt_sw_rd = sw_rd && slot_mgmt_tx_desc_cnt_decode;

    always_comb begin
        slot_mgmt_tx_desc_cnt_q = '0;
        slot_mgmt_tx_desc_cnt_q[23: 0] = slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_q;
    end

    // masked version of return data
    assign slot_mgmt_tx_desc_cnt_rdata = slot_mgmt_tx_desc_cnt_sw_rd ? slot_mgmt_tx_desc_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_tx_desc_cnt (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_anded = & slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_q;
    assign slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_ored  = | slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_q;
    assign slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_xored = ^ slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_q;

    // next hardware value
    assign slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_next = slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_wdata;
    assign slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_q = slot_mgmt_tx_desc_cnt_slot_mgmt_tx_desc_cnt_next;
            
        
    // ============================================================
    // Register: SLOT_MGMT_RX_DFX_ERR
    //    [27: 0] slot_mgmt_rx_dfx_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  slot_mgmt_rx_dfx_err_decode;
    logic                  slot_mgmt_rx_dfx_err_sw_wr;
    logic                  slot_mgmt_rx_dfx_err_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_rx_dfx_err_q;

    assign slot_mgmt_rx_dfx_err_decode = (addr == (ADDR_OFFSET+'h0+'h80));
    assign slot_mgmt_rx_dfx_err_sw_wr = sw_wr && slot_mgmt_rx_dfx_err_decode;
    assign slot_mgmt_rx_dfx_err_sw_rd = sw_rd && slot_mgmt_rx_dfx_err_decode;

    always_comb begin
        slot_mgmt_rx_dfx_err_q = '0;
        slot_mgmt_rx_dfx_err_q[27: 0] = slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_q;
    end

    // masked version of return data
    assign slot_mgmt_rx_dfx_err_rdata = slot_mgmt_rx_dfx_err_sw_rd ? slot_mgmt_rx_dfx_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_rx_dfx_err
    // ------------------------------------------------------------
    assign slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_anded = & slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_q;
    assign slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_ored  = | slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_q;
    assign slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_xored = ^ slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_q;

    // next hardware value
    assign slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_next = slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_q <= 64'd0;
    end else begin
        // Hardware Write
        if (slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_we) begin
            slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_q <= slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_next;
        end
        // Software write
        else if (slot_mgmt_rx_dfx_err_sw_wr) begin
            slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_q <= ~sw_masked_data[27: 0] &  slot_mgmt_rx_dfx_err_slot_mgmt_rx_dfx_err_q;
        end
    end
            
        
    // ============================================================
    // Register: SLOT_MGMT_RX_DFX_STATUS
    //    [19: 0] slot_mgmt_rx_dfx_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_rx_dfx_status_decode;
    logic                  slot_mgmt_rx_dfx_status_sw_wr;
    logic                  slot_mgmt_rx_dfx_status_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_rx_dfx_status_q;

    assign slot_mgmt_rx_dfx_status_decode = (addr == (ADDR_OFFSET+'h0+'h88));
    assign slot_mgmt_rx_dfx_status_sw_wr = sw_wr && slot_mgmt_rx_dfx_status_decode;
    assign slot_mgmt_rx_dfx_status_sw_rd = sw_rd && slot_mgmt_rx_dfx_status_decode;

    always_comb begin
        slot_mgmt_rx_dfx_status_q = '0;
        slot_mgmt_rx_dfx_status_q[19: 0] = slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_q;
    end

    // masked version of return data
    assign slot_mgmt_rx_dfx_status_rdata = slot_mgmt_rx_dfx_status_sw_rd ? slot_mgmt_rx_dfx_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_rx_dfx_status (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_anded = & slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_q;
    assign slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_ored  = | slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_q;
    assign slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_xored = ^ slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_q;

    // next hardware value
    assign slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_next = slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_wdata;
    assign slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_q = slot_mgmt_rx_dfx_status_slot_mgmt_rx_dfx_status_next;
            
        
    // ============================================================
    // Register: SLOT_MGMT_RX_ALLOC_SLOT_CNT
    //    [23: 0] slot_mgmt_rx_alloc_slot_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_rx_alloc_slot_cnt_decode;
    logic                  slot_mgmt_rx_alloc_slot_cnt_sw_wr;
    logic                  slot_mgmt_rx_alloc_slot_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_rx_alloc_slot_cnt_q;

    assign slot_mgmt_rx_alloc_slot_cnt_decode = (addr == (ADDR_OFFSET+'h0+'hb0));
    assign slot_mgmt_rx_alloc_slot_cnt_sw_wr = sw_wr && slot_mgmt_rx_alloc_slot_cnt_decode;
    assign slot_mgmt_rx_alloc_slot_cnt_sw_rd = sw_rd && slot_mgmt_rx_alloc_slot_cnt_decode;

    always_comb begin
        slot_mgmt_rx_alloc_slot_cnt_q = '0;
        slot_mgmt_rx_alloc_slot_cnt_q[23: 0] = slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_q;
    end

    // masked version of return data
    assign slot_mgmt_rx_alloc_slot_cnt_rdata = slot_mgmt_rx_alloc_slot_cnt_sw_rd ? slot_mgmt_rx_alloc_slot_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_rx_alloc_slot_cnt (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_anded = & slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_q;
    assign slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_ored  = | slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_q;
    assign slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_xored = ^ slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_q;

    // next hardware value
    assign slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_next = slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_wdata;
    assign slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_q = slot_mgmt_rx_alloc_slot_cnt_slot_mgmt_rx_alloc_slot_cnt_next;
            
        
    // ============================================================
    // Register: SLOT_MGMT_RX_AVAIL_ID_CNT
    //    [39: 0] slot_mgmt_rx_avail_id_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_rx_avail_id_cnt_decode;
    logic                  slot_mgmt_rx_avail_id_cnt_sw_wr;
    logic                  slot_mgmt_rx_avail_id_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_rx_avail_id_cnt_q;

    assign slot_mgmt_rx_avail_id_cnt_decode = (addr == (ADDR_OFFSET+'h0+'hb8));
    assign slot_mgmt_rx_avail_id_cnt_sw_wr = sw_wr && slot_mgmt_rx_avail_id_cnt_decode;
    assign slot_mgmt_rx_avail_id_cnt_sw_rd = sw_rd && slot_mgmt_rx_avail_id_cnt_decode;

    always_comb begin
        slot_mgmt_rx_avail_id_cnt_q = '0;
        slot_mgmt_rx_avail_id_cnt_q[39: 0] = slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_q;
    end

    // masked version of return data
    assign slot_mgmt_rx_avail_id_cnt_rdata = slot_mgmt_rx_avail_id_cnt_sw_rd ? slot_mgmt_rx_avail_id_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_rx_avail_id_cnt (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_anded = & slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_q;
    assign slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_ored  = | slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_q;
    assign slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_xored = ^ slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_q;

    // next hardware value
    assign slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_next = slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_wdata;
    assign slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_q = slot_mgmt_rx_avail_id_cnt_slot_mgmt_rx_avail_id_cnt_next;
            
        
    // ============================================================
    // Register: SLOT_MGMT_RX_SLOT_CNT
    //    [23: 0] slot_mgmt_rx_slot_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_rx_slot_cnt_decode;
    logic                  slot_mgmt_rx_slot_cnt_sw_wr;
    logic                  slot_mgmt_rx_slot_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_rx_slot_cnt_q;

    assign slot_mgmt_rx_slot_cnt_decode = (addr == (ADDR_OFFSET+'h0+'hc0));
    assign slot_mgmt_rx_slot_cnt_sw_wr = sw_wr && slot_mgmt_rx_slot_cnt_decode;
    assign slot_mgmt_rx_slot_cnt_sw_rd = sw_rd && slot_mgmt_rx_slot_cnt_decode;

    always_comb begin
        slot_mgmt_rx_slot_cnt_q = '0;
        slot_mgmt_rx_slot_cnt_q[23: 0] = slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_q;
    end

    // masked version of return data
    assign slot_mgmt_rx_slot_cnt_rdata = slot_mgmt_rx_slot_cnt_sw_rd ? slot_mgmt_rx_slot_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_rx_slot_cnt (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_anded = & slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_q;
    assign slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_ored  = | slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_q;
    assign slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_xored = ^ slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_q;

    // next hardware value
    assign slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_next = slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_wdata;
    assign slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_q = slot_mgmt_rx_slot_cnt_slot_mgmt_rx_slot_cnt_next;
            
        
    // ============================================================
    // Register: SLOT_MGMT_RX_RD_DESC_CNT
    //    [23: 0] slot_mgmt_rx_rd_desc_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_rx_rd_desc_cnt_decode;
    logic                  slot_mgmt_rx_rd_desc_cnt_sw_wr;
    logic                  slot_mgmt_rx_rd_desc_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_rx_rd_desc_cnt_q;

    assign slot_mgmt_rx_rd_desc_cnt_decode = (addr == (ADDR_OFFSET+'h0+'hc8));
    assign slot_mgmt_rx_rd_desc_cnt_sw_wr = sw_wr && slot_mgmt_rx_rd_desc_cnt_decode;
    assign slot_mgmt_rx_rd_desc_cnt_sw_rd = sw_rd && slot_mgmt_rx_rd_desc_cnt_decode;

    always_comb begin
        slot_mgmt_rx_rd_desc_cnt_q = '0;
        slot_mgmt_rx_rd_desc_cnt_q[23: 0] = slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_q;
    end

    // masked version of return data
    assign slot_mgmt_rx_rd_desc_cnt_rdata = slot_mgmt_rx_rd_desc_cnt_sw_rd ? slot_mgmt_rx_rd_desc_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_rx_rd_desc_cnt (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_anded = & slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_q;
    assign slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_ored  = | slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_q;
    assign slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_xored = ^ slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_q;

    // next hardware value
    assign slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_next = slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_wdata;
    assign slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_q = slot_mgmt_rx_rd_desc_cnt_slot_mgmt_rx_rd_desc_cnt_next;
            
        
    // ============================================================
    // Register: SLOT_MGMT_RX_DESC_CNT
    //    [23: 0] slot_mgmt_rx_desc_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  slot_mgmt_rx_desc_cnt_decode;
    logic                  slot_mgmt_rx_desc_cnt_sw_wr;
    logic                  slot_mgmt_rx_desc_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] slot_mgmt_rx_desc_cnt_q;

    assign slot_mgmt_rx_desc_cnt_decode = (addr == (ADDR_OFFSET+'h0+'hd0));
    assign slot_mgmt_rx_desc_cnt_sw_wr = sw_wr && slot_mgmt_rx_desc_cnt_decode;
    assign slot_mgmt_rx_desc_cnt_sw_rd = sw_rd && slot_mgmt_rx_desc_cnt_decode;

    always_comb begin
        slot_mgmt_rx_desc_cnt_q = '0;
        slot_mgmt_rx_desc_cnt_q[23: 0] = slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_q;
    end

    // masked version of return data
    assign slot_mgmt_rx_desc_cnt_rdata = slot_mgmt_rx_desc_cnt_sw_rd ? slot_mgmt_rx_desc_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: slot_mgmt_rx_desc_cnt (wire)
    // ------------------------------------------------------------
    assign slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_anded = & slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_q;
    assign slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_ored  = | slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_q;
    assign slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_xored = ^ slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_q;

    // next hardware value
    assign slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_next = slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_wdata;
    assign slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_q = slot_mgmt_rx_desc_cnt_slot_mgmt_rx_desc_cnt_next;
            
        
    // ============================================================
    // Register: CORE_RX_DFX_ERR
    //    [44: 0]      core_rx_dfx_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  core_rx_dfx_err_decode;
    logic                  core_rx_dfx_err_sw_wr;
    logic                  core_rx_dfx_err_sw_rd;
    logic [DATA_WIDTH-1:0] core_rx_dfx_err_q;

    assign core_rx_dfx_err_decode = (addr == (ADDR_OFFSET+'h0+'h100));
    assign core_rx_dfx_err_sw_wr = sw_wr && core_rx_dfx_err_decode;
    assign core_rx_dfx_err_sw_rd = sw_rd && core_rx_dfx_err_decode;

    always_comb begin
        core_rx_dfx_err_q = '0;
        core_rx_dfx_err_q[44: 0] = core_rx_dfx_err_core_rx_dfx_err_q;
    end

    // masked version of return data
    assign core_rx_dfx_err_rdata = core_rx_dfx_err_sw_rd ? core_rx_dfx_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_rx_dfx_err
    // ------------------------------------------------------------
    assign core_rx_dfx_err_core_rx_dfx_err_anded = & core_rx_dfx_err_core_rx_dfx_err_q;
    assign core_rx_dfx_err_core_rx_dfx_err_ored  = | core_rx_dfx_err_core_rx_dfx_err_q;
    assign core_rx_dfx_err_core_rx_dfx_err_xored = ^ core_rx_dfx_err_core_rx_dfx_err_q;

    // next hardware value
    assign core_rx_dfx_err_core_rx_dfx_err_next = core_rx_dfx_err_core_rx_dfx_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        core_rx_dfx_err_core_rx_dfx_err_q <= 64'd0;
    end else begin
        // Hardware Write
        if (core_rx_dfx_err_core_rx_dfx_err_we) begin
            core_rx_dfx_err_core_rx_dfx_err_q <= core_rx_dfx_err_core_rx_dfx_err_next;
        end
        // Software write
        else if (core_rx_dfx_err_sw_wr) begin
            core_rx_dfx_err_core_rx_dfx_err_q <= ~sw_masked_data[44: 0] &  core_rx_dfx_err_core_rx_dfx_err_q;
        end
    end
            
        
    // ============================================================
    // Register: CORE_RX_DFX_STATUS
    //    [62: 0]   core_rx_dfx_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  core_rx_dfx_status_decode;
    logic                  core_rx_dfx_status_sw_wr;
    logic                  core_rx_dfx_status_sw_rd;
    logic [DATA_WIDTH-1:0] core_rx_dfx_status_q;

    assign core_rx_dfx_status_decode = (addr == (ADDR_OFFSET+'h0+'h108));
    assign core_rx_dfx_status_sw_wr = sw_wr && core_rx_dfx_status_decode;
    assign core_rx_dfx_status_sw_rd = sw_rd && core_rx_dfx_status_decode;

    always_comb begin
        core_rx_dfx_status_q = '0;
        core_rx_dfx_status_q[62: 0] = core_rx_dfx_status_core_rx_dfx_status_q;
    end

    // masked version of return data
    assign core_rx_dfx_status_rdata = core_rx_dfx_status_sw_rd ? core_rx_dfx_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_rx_dfx_status (wire)
    // ------------------------------------------------------------
    assign core_rx_dfx_status_core_rx_dfx_status_anded = & core_rx_dfx_status_core_rx_dfx_status_q;
    assign core_rx_dfx_status_core_rx_dfx_status_ored  = | core_rx_dfx_status_core_rx_dfx_status_q;
    assign core_rx_dfx_status_core_rx_dfx_status_xored = ^ core_rx_dfx_status_core_rx_dfx_status_q;

    // next hardware value
    assign core_rx_dfx_status_core_rx_dfx_status_next = core_rx_dfx_status_core_rx_dfx_status_wdata;
    assign core_rx_dfx_status_core_rx_dfx_status_q = core_rx_dfx_status_core_rx_dfx_status_next;
            
        
    // ============================================================
    // Register: CORE_RX_DMA_CNT
    //    [15: 0]      core_rx_dma_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  core_rx_dma_cnt_decode;
    logic                  core_rx_dma_cnt_sw_wr;
    logic                  core_rx_dma_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] core_rx_dma_cnt_q;

    assign core_rx_dma_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h130));
    assign core_rx_dma_cnt_sw_wr = sw_wr && core_rx_dma_cnt_decode;
    assign core_rx_dma_cnt_sw_rd = sw_rd && core_rx_dma_cnt_decode;

    always_comb begin
        core_rx_dma_cnt_q = '0;
        core_rx_dma_cnt_q[15: 0] = core_rx_dma_cnt_core_rx_dma_cnt_q;
    end

    // masked version of return data
    assign core_rx_dma_cnt_rdata = core_rx_dma_cnt_sw_rd ? core_rx_dma_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_rx_dma_cnt (wire)
    // ------------------------------------------------------------
    assign core_rx_dma_cnt_core_rx_dma_cnt_anded = & core_rx_dma_cnt_core_rx_dma_cnt_q;
    assign core_rx_dma_cnt_core_rx_dma_cnt_ored  = | core_rx_dma_cnt_core_rx_dma_cnt_q;
    assign core_rx_dma_cnt_core_rx_dma_cnt_xored = ^ core_rx_dma_cnt_core_rx_dma_cnt_q;

    // next hardware value
    assign core_rx_dma_cnt_core_rx_dma_cnt_next = core_rx_dma_cnt_core_rx_dma_cnt_wdata;
    assign core_rx_dma_cnt_core_rx_dma_cnt_q = core_rx_dma_cnt_core_rx_dma_cnt_next;
            
        
    // ============================================================
    // Register: CORE_RX_SCH_OUT_CNT
    //    [23: 0]  core_rx_sch_out_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  core_rx_sch_out_cnt_decode;
    logic                  core_rx_sch_out_cnt_sw_wr;
    logic                  core_rx_sch_out_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] core_rx_sch_out_cnt_q;

    assign core_rx_sch_out_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h138));
    assign core_rx_sch_out_cnt_sw_wr = sw_wr && core_rx_sch_out_cnt_decode;
    assign core_rx_sch_out_cnt_sw_rd = sw_rd && core_rx_sch_out_cnt_decode;

    always_comb begin
        core_rx_sch_out_cnt_q = '0;
        core_rx_sch_out_cnt_q[23: 0] = core_rx_sch_out_cnt_core_rx_sch_out_cnt_q;
    end

    // masked version of return data
    assign core_rx_sch_out_cnt_rdata = core_rx_sch_out_cnt_sw_rd ? core_rx_sch_out_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_rx_sch_out_cnt (wire)
    // ------------------------------------------------------------
    assign core_rx_sch_out_cnt_core_rx_sch_out_cnt_anded = & core_rx_sch_out_cnt_core_rx_sch_out_cnt_q;
    assign core_rx_sch_out_cnt_core_rx_sch_out_cnt_ored  = | core_rx_sch_out_cnt_core_rx_sch_out_cnt_q;
    assign core_rx_sch_out_cnt_core_rx_sch_out_cnt_xored = ^ core_rx_sch_out_cnt_core_rx_sch_out_cnt_q;

    // next hardware value
    assign core_rx_sch_out_cnt_core_rx_sch_out_cnt_next = core_rx_sch_out_cnt_core_rx_sch_out_cnt_wdata;
    assign core_rx_sch_out_cnt_core_rx_sch_out_cnt_q = core_rx_sch_out_cnt_core_rx_sch_out_cnt_next;
            
        
    // ============================================================
    // Register: CORE_RX_DESC_BUF_CNT
    //    [15: 0] core_rx_desc_buf_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  core_rx_desc_buf_cnt_decode;
    logic                  core_rx_desc_buf_cnt_sw_wr;
    logic                  core_rx_desc_buf_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] core_rx_desc_buf_cnt_q;

    assign core_rx_desc_buf_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h140));
    assign core_rx_desc_buf_cnt_sw_wr = sw_wr && core_rx_desc_buf_cnt_decode;
    assign core_rx_desc_buf_cnt_sw_rd = sw_rd && core_rx_desc_buf_cnt_decode;

    always_comb begin
        core_rx_desc_buf_cnt_q = '0;
        core_rx_desc_buf_cnt_q[15: 0] = core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_q;
    end

    // masked version of return data
    assign core_rx_desc_buf_cnt_rdata = core_rx_desc_buf_cnt_sw_rd ? core_rx_desc_buf_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_rx_desc_buf_cnt (wire)
    // ------------------------------------------------------------
    assign core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_anded = & core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_q;
    assign core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_ored  = | core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_q;
    assign core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_xored = ^ core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_q;

    // next hardware value
    assign core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_next = core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_wdata;
    assign core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_q = core_rx_desc_buf_cnt_core_rx_desc_buf_cnt_next;
            
        
    // ============================================================
    // Register: CORE_RX_WAKE_UP_CNT
    //    [ 7: 0]  core_rx_wake_up_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  core_rx_wake_up_cnt_decode;
    logic                  core_rx_wake_up_cnt_sw_wr;
    logic                  core_rx_wake_up_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] core_rx_wake_up_cnt_q;

    assign core_rx_wake_up_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h148));
    assign core_rx_wake_up_cnt_sw_wr = sw_wr && core_rx_wake_up_cnt_decode;
    assign core_rx_wake_up_cnt_sw_rd = sw_rd && core_rx_wake_up_cnt_decode;

    always_comb begin
        core_rx_wake_up_cnt_q = '0;
        core_rx_wake_up_cnt_q[ 7: 0] = core_rx_wake_up_cnt_core_rx_wake_up_cnt_q;
    end

    // masked version of return data
    assign core_rx_wake_up_cnt_rdata = core_rx_wake_up_cnt_sw_rd ? core_rx_wake_up_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_rx_wake_up_cnt (wire)
    // ------------------------------------------------------------
    assign core_rx_wake_up_cnt_core_rx_wake_up_cnt_anded = & core_rx_wake_up_cnt_core_rx_wake_up_cnt_q;
    assign core_rx_wake_up_cnt_core_rx_wake_up_cnt_ored  = | core_rx_wake_up_cnt_core_rx_wake_up_cnt_q;
    assign core_rx_wake_up_cnt_core_rx_wake_up_cnt_xored = ^ core_rx_wake_up_cnt_core_rx_wake_up_cnt_q;

    // next hardware value
    assign core_rx_wake_up_cnt_core_rx_wake_up_cnt_next = core_rx_wake_up_cnt_core_rx_wake_up_cnt_wdata;
    assign core_rx_wake_up_cnt_core_rx_wake_up_cnt_q = core_rx_wake_up_cnt_core_rx_wake_up_cnt_next;
            
        
    // ============================================================
    // Register: CORE_TX_DFX_ERR
    //    [44: 0]      core_tx_dfx_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  core_tx_dfx_err_decode;
    logic                  core_tx_dfx_err_sw_wr;
    logic                  core_tx_dfx_err_sw_rd;
    logic [DATA_WIDTH-1:0] core_tx_dfx_err_q;

    assign core_tx_dfx_err_decode = (addr == (ADDR_OFFSET+'h0+'h180));
    assign core_tx_dfx_err_sw_wr = sw_wr && core_tx_dfx_err_decode;
    assign core_tx_dfx_err_sw_rd = sw_rd && core_tx_dfx_err_decode;

    always_comb begin
        core_tx_dfx_err_q = '0;
        core_tx_dfx_err_q[44: 0] = core_tx_dfx_err_core_tx_dfx_err_q;
    end

    // masked version of return data
    assign core_tx_dfx_err_rdata = core_tx_dfx_err_sw_rd ? core_tx_dfx_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_tx_dfx_err
    // ------------------------------------------------------------
    assign core_tx_dfx_err_core_tx_dfx_err_anded = & core_tx_dfx_err_core_tx_dfx_err_q;
    assign core_tx_dfx_err_core_tx_dfx_err_ored  = | core_tx_dfx_err_core_tx_dfx_err_q;
    assign core_tx_dfx_err_core_tx_dfx_err_xored = ^ core_tx_dfx_err_core_tx_dfx_err_q;

    // next hardware value
    assign core_tx_dfx_err_core_tx_dfx_err_next = core_tx_dfx_err_core_tx_dfx_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        core_tx_dfx_err_core_tx_dfx_err_q <= 64'd0;
    end else begin
        // Hardware Write
        if (core_tx_dfx_err_core_tx_dfx_err_we) begin
            core_tx_dfx_err_core_tx_dfx_err_q <= core_tx_dfx_err_core_tx_dfx_err_next;
        end
        // Software write
        else if (core_tx_dfx_err_sw_wr) begin
            core_tx_dfx_err_core_tx_dfx_err_q <= ~sw_masked_data[44: 0] &  core_tx_dfx_err_core_tx_dfx_err_q;
        end
    end
            
        
    // ============================================================
    // Register: CORE_TX_DFX_STATUS
    //    [62: 0]   core_tx_dfx_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  core_tx_dfx_status_decode;
    logic                  core_tx_dfx_status_sw_wr;
    logic                  core_tx_dfx_status_sw_rd;
    logic [DATA_WIDTH-1:0] core_tx_dfx_status_q;

    assign core_tx_dfx_status_decode = (addr == (ADDR_OFFSET+'h0+'h188));
    assign core_tx_dfx_status_sw_wr = sw_wr && core_tx_dfx_status_decode;
    assign core_tx_dfx_status_sw_rd = sw_rd && core_tx_dfx_status_decode;

    always_comb begin
        core_tx_dfx_status_q = '0;
        core_tx_dfx_status_q[62: 0] = core_tx_dfx_status_core_tx_dfx_status_q;
    end

    // masked version of return data
    assign core_tx_dfx_status_rdata = core_tx_dfx_status_sw_rd ? core_tx_dfx_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_tx_dfx_status (wire)
    // ------------------------------------------------------------
    assign core_tx_dfx_status_core_tx_dfx_status_anded = & core_tx_dfx_status_core_tx_dfx_status_q;
    assign core_tx_dfx_status_core_tx_dfx_status_ored  = | core_tx_dfx_status_core_tx_dfx_status_q;
    assign core_tx_dfx_status_core_tx_dfx_status_xored = ^ core_tx_dfx_status_core_tx_dfx_status_q;

    // next hardware value
    assign core_tx_dfx_status_core_tx_dfx_status_next = core_tx_dfx_status_core_tx_dfx_status_wdata;
    assign core_tx_dfx_status_core_tx_dfx_status_q = core_tx_dfx_status_core_tx_dfx_status_next;
            
        
    // ============================================================
    // Register: CORE_TX_DMA_CNT
    //    [15: 0]      core_tx_dma_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  core_tx_dma_cnt_decode;
    logic                  core_tx_dma_cnt_sw_wr;
    logic                  core_tx_dma_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] core_tx_dma_cnt_q;

    assign core_tx_dma_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h1b0));
    assign core_tx_dma_cnt_sw_wr = sw_wr && core_tx_dma_cnt_decode;
    assign core_tx_dma_cnt_sw_rd = sw_rd && core_tx_dma_cnt_decode;

    always_comb begin
        core_tx_dma_cnt_q = '0;
        core_tx_dma_cnt_q[15: 0] = core_tx_dma_cnt_core_tx_dma_cnt_q;
    end

    // masked version of return data
    assign core_tx_dma_cnt_rdata = core_tx_dma_cnt_sw_rd ? core_tx_dma_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_tx_dma_cnt (wire)
    // ------------------------------------------------------------
    assign core_tx_dma_cnt_core_tx_dma_cnt_anded = & core_tx_dma_cnt_core_tx_dma_cnt_q;
    assign core_tx_dma_cnt_core_tx_dma_cnt_ored  = | core_tx_dma_cnt_core_tx_dma_cnt_q;
    assign core_tx_dma_cnt_core_tx_dma_cnt_xored = ^ core_tx_dma_cnt_core_tx_dma_cnt_q;

    // next hardware value
    assign core_tx_dma_cnt_core_tx_dma_cnt_next = core_tx_dma_cnt_core_tx_dma_cnt_wdata;
    assign core_tx_dma_cnt_core_tx_dma_cnt_q = core_tx_dma_cnt_core_tx_dma_cnt_next;
            
        
    // ============================================================
    // Register: CORE_TX_SCH_OUT_CNT
    //    [23: 0]  core_tx_sch_out_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  core_tx_sch_out_cnt_decode;
    logic                  core_tx_sch_out_cnt_sw_wr;
    logic                  core_tx_sch_out_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] core_tx_sch_out_cnt_q;

    assign core_tx_sch_out_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h1b8));
    assign core_tx_sch_out_cnt_sw_wr = sw_wr && core_tx_sch_out_cnt_decode;
    assign core_tx_sch_out_cnt_sw_rd = sw_rd && core_tx_sch_out_cnt_decode;

    always_comb begin
        core_tx_sch_out_cnt_q = '0;
        core_tx_sch_out_cnt_q[23: 0] = core_tx_sch_out_cnt_core_tx_sch_out_cnt_q;
    end

    // masked version of return data
    assign core_tx_sch_out_cnt_rdata = core_tx_sch_out_cnt_sw_rd ? core_tx_sch_out_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_tx_sch_out_cnt (wire)
    // ------------------------------------------------------------
    assign core_tx_sch_out_cnt_core_tx_sch_out_cnt_anded = & core_tx_sch_out_cnt_core_tx_sch_out_cnt_q;
    assign core_tx_sch_out_cnt_core_tx_sch_out_cnt_ored  = | core_tx_sch_out_cnt_core_tx_sch_out_cnt_q;
    assign core_tx_sch_out_cnt_core_tx_sch_out_cnt_xored = ^ core_tx_sch_out_cnt_core_tx_sch_out_cnt_q;

    // next hardware value
    assign core_tx_sch_out_cnt_core_tx_sch_out_cnt_next = core_tx_sch_out_cnt_core_tx_sch_out_cnt_wdata;
    assign core_tx_sch_out_cnt_core_tx_sch_out_cnt_q = core_tx_sch_out_cnt_core_tx_sch_out_cnt_next;
            
        
    // ============================================================
    // Register: CORE_TX_DESC_BUF_CNT
    //    [15: 0] core_tx_desc_buf_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  core_tx_desc_buf_cnt_decode;
    logic                  core_tx_desc_buf_cnt_sw_wr;
    logic                  core_tx_desc_buf_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] core_tx_desc_buf_cnt_q;

    assign core_tx_desc_buf_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h1c0));
    assign core_tx_desc_buf_cnt_sw_wr = sw_wr && core_tx_desc_buf_cnt_decode;
    assign core_tx_desc_buf_cnt_sw_rd = sw_rd && core_tx_desc_buf_cnt_decode;

    always_comb begin
        core_tx_desc_buf_cnt_q = '0;
        core_tx_desc_buf_cnt_q[15: 0] = core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_q;
    end

    // masked version of return data
    assign core_tx_desc_buf_cnt_rdata = core_tx_desc_buf_cnt_sw_rd ? core_tx_desc_buf_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_tx_desc_buf_cnt (wire)
    // ------------------------------------------------------------
    assign core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_anded = & core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_q;
    assign core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_ored  = | core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_q;
    assign core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_xored = ^ core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_q;

    // next hardware value
    assign core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_next = core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_wdata;
    assign core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_q = core_tx_desc_buf_cnt_core_tx_desc_buf_cnt_next;
            
        
    // ============================================================
    // Register: CORE_TX_WAKE_UP_CNT
    //    [ 7: 0]  core_tx_wake_up_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  core_tx_wake_up_cnt_decode;
    logic                  core_tx_wake_up_cnt_sw_wr;
    logic                  core_tx_wake_up_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] core_tx_wake_up_cnt_q;

    assign core_tx_wake_up_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h1c8));
    assign core_tx_wake_up_cnt_sw_wr = sw_wr && core_tx_wake_up_cnt_decode;
    assign core_tx_wake_up_cnt_sw_rd = sw_rd && core_tx_wake_up_cnt_decode;

    always_comb begin
        core_tx_wake_up_cnt_q = '0;
        core_tx_wake_up_cnt_q[ 7: 0] = core_tx_wake_up_cnt_core_tx_wake_up_cnt_q;
    end

    // masked version of return data
    assign core_tx_wake_up_cnt_rdata = core_tx_wake_up_cnt_sw_rd ? core_tx_wake_up_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: core_tx_wake_up_cnt (wire)
    // ------------------------------------------------------------
    assign core_tx_wake_up_cnt_core_tx_wake_up_cnt_anded = & core_tx_wake_up_cnt_core_tx_wake_up_cnt_q;
    assign core_tx_wake_up_cnt_core_tx_wake_up_cnt_ored  = | core_tx_wake_up_cnt_core_tx_wake_up_cnt_q;
    assign core_tx_wake_up_cnt_core_tx_wake_up_cnt_xored = ^ core_tx_wake_up_cnt_core_tx_wake_up_cnt_q;

    // next hardware value
    assign core_tx_wake_up_cnt_core_tx_wake_up_cnt_next = core_tx_wake_up_cnt_core_tx_wake_up_cnt_wdata;
    assign core_tx_wake_up_cnt_core_tx_wake_up_cnt_q = core_tx_wake_up_cnt_core_tx_wake_up_cnt_next;
            
        
    // ============================================================
    // Register: RX_DMA_RD_REQ_CNT
    //    [63: 0]    rx_dma_rd_req_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  rx_dma_rd_req_cnt_decode;
    logic                  rx_dma_rd_req_cnt_sw_wr;
    logic                  rx_dma_rd_req_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] rx_dma_rd_req_cnt_q;

    assign rx_dma_rd_req_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h200));
    assign rx_dma_rd_req_cnt_sw_wr = sw_wr && rx_dma_rd_req_cnt_decode;
    assign rx_dma_rd_req_cnt_sw_rd = sw_rd && rx_dma_rd_req_cnt_decode;

    always_comb begin
        rx_dma_rd_req_cnt_q = '0;
        rx_dma_rd_req_cnt_q[63: 0] = rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_q;
    end

    // masked version of return data
    assign rx_dma_rd_req_cnt_rdata = rx_dma_rd_req_cnt_sw_rd ? rx_dma_rd_req_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: rx_dma_rd_req_cnt (wire)
    // ------------------------------------------------------------
    assign rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_anded = & rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_q;
    assign rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_ored  = | rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_q;
    assign rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_xored = ^ rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_q;

    // next hardware value
    assign rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_next = rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_wdata;
    assign rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_q = rx_dma_rd_req_cnt_rx_dma_rd_req_cnt_next;
            
        
    // ============================================================
    // Register: RX_DMA_RD_RSP_CNT
    //    [31: 0]    rx_dma_rd_rsp_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  rx_dma_rd_rsp_cnt_decode;
    logic                  rx_dma_rd_rsp_cnt_sw_wr;
    logic                  rx_dma_rd_rsp_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] rx_dma_rd_rsp_cnt_q;

    assign rx_dma_rd_rsp_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h208));
    assign rx_dma_rd_rsp_cnt_sw_wr = sw_wr && rx_dma_rd_rsp_cnt_decode;
    assign rx_dma_rd_rsp_cnt_sw_rd = sw_rd && rx_dma_rd_rsp_cnt_decode;

    always_comb begin
        rx_dma_rd_rsp_cnt_q = '0;
        rx_dma_rd_rsp_cnt_q[31: 0] = rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_q;
    end

    // masked version of return data
    assign rx_dma_rd_rsp_cnt_rdata = rx_dma_rd_rsp_cnt_sw_rd ? rx_dma_rd_rsp_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: rx_dma_rd_rsp_cnt (wire)
    // ------------------------------------------------------------
    assign rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_anded = & rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_q;
    assign rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_ored  = | rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_q;
    assign rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_xored = ^ rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_q;

    // next hardware value
    assign rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_next = rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_wdata;
    assign rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_q = rx_dma_rd_rsp_cnt_rx_dma_rd_rsp_cnt_next;
            
        
    // ============================================================
    // Register: TX_DMA_RD_REQ_CNT
    //    [63: 0]    tx_dma_rd_req_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  tx_dma_rd_req_cnt_decode;
    logic                  tx_dma_rd_req_cnt_sw_wr;
    logic                  tx_dma_rd_req_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] tx_dma_rd_req_cnt_q;

    assign tx_dma_rd_req_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h210));
    assign tx_dma_rd_req_cnt_sw_wr = sw_wr && tx_dma_rd_req_cnt_decode;
    assign tx_dma_rd_req_cnt_sw_rd = sw_rd && tx_dma_rd_req_cnt_decode;

    always_comb begin
        tx_dma_rd_req_cnt_q = '0;
        tx_dma_rd_req_cnt_q[63: 0] = tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_q;
    end

    // masked version of return data
    assign tx_dma_rd_req_cnt_rdata = tx_dma_rd_req_cnt_sw_rd ? tx_dma_rd_req_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: tx_dma_rd_req_cnt (wire)
    // ------------------------------------------------------------
    assign tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_anded = & tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_q;
    assign tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_ored  = | tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_q;
    assign tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_xored = ^ tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_q;

    // next hardware value
    assign tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_next = tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_wdata;
    assign tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_q = tx_dma_rd_req_cnt_tx_dma_rd_req_cnt_next;
            
        
    // ============================================================
    // Register: TX_DMA_RD_RSP_CNT
    //    [31: 0]    tx_dma_rd_rsp_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  tx_dma_rd_rsp_cnt_decode;
    logic                  tx_dma_rd_rsp_cnt_sw_wr;
    logic                  tx_dma_rd_rsp_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] tx_dma_rd_rsp_cnt_q;

    assign tx_dma_rd_rsp_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h218));
    assign tx_dma_rd_rsp_cnt_sw_wr = sw_wr && tx_dma_rd_rsp_cnt_decode;
    assign tx_dma_rd_rsp_cnt_sw_rd = sw_rd && tx_dma_rd_rsp_cnt_decode;

    always_comb begin
        tx_dma_rd_rsp_cnt_q = '0;
        tx_dma_rd_rsp_cnt_q[31: 0] = tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_q;
    end

    // masked version of return data
    assign tx_dma_rd_rsp_cnt_rdata = tx_dma_rd_rsp_cnt_sw_rd ? tx_dma_rd_rsp_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: tx_dma_rd_rsp_cnt (wire)
    // ------------------------------------------------------------
    assign tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_anded = & tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_q;
    assign tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_ored  = | tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_q;
    assign tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_xored = ^ tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_q;

    // next hardware value
    assign tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_next = tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_wdata;
    assign tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_q = tx_dma_rd_rsp_cnt_tx_dma_rd_rsp_cnt_next;
            
        
    // ============================================================
    // Register: USED_SLOT_NUM
    //    [31: 0]        used_slot_num: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  used_slot_num_decode;
    logic                  used_slot_num_sw_wr;
    logic                  used_slot_num_sw_rd;
    logic [DATA_WIDTH-1:0] used_slot_num_q;

    assign used_slot_num_decode = (addr == (ADDR_OFFSET+'h0+'h280));
    assign used_slot_num_sw_wr = sw_wr && used_slot_num_decode;
    assign used_slot_num_sw_rd = sw_rd && used_slot_num_decode;

    always_comb begin
        used_slot_num_q = '0;
        used_slot_num_q[31: 0] = used_slot_num_used_slot_num_q;
    end

    // masked version of return data
    assign used_slot_num_rdata = used_slot_num_sw_rd ? used_slot_num_q : 'b0;

    // ------------------------------------------------------------
    // Field: used_slot_num (wire)
    // ------------------------------------------------------------
    assign used_slot_num_used_slot_num_anded = & used_slot_num_used_slot_num_q;
    assign used_slot_num_used_slot_num_ored  = | used_slot_num_used_slot_num_q;
    assign used_slot_num_used_slot_num_xored = ^ used_slot_num_used_slot_num_q;

    // next hardware value
    assign used_slot_num_used_slot_num_next = used_slot_num_used_slot_num_wdata;
    assign used_slot_num_used_slot_num_q = used_slot_num_used_slot_num_next;

endmodule: virtio_desc_engine_dfx
