// This file was autogenerated by PeakRDL-verilog
module emu_dfx #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register EMU_TOP_ERR
    input  logic                             emu_top_err_emu_top_err_we,             //! Control HW write (active high)
    input  logic                     [31: 0] emu_top_err_emu_top_err_wdata,          //! HW write data
    output logic                     [31: 0] emu_top_err_emu_top_err_q,              //! Current field value

    // Register EMU_REG_CTRL_ERR
    input  logic                             emu_reg_ctrl_err_emu_reg_ctrl_err_we,             //! Control HW write (active high)
    input  logic                     [31: 0] emu_reg_ctrl_err_emu_reg_ctrl_err_wdata,          //! HW write data
    output logic                     [31: 0] emu_reg_ctrl_err_emu_reg_ctrl_err_q,              //! Current field value

    // Register EMU_REQ_MATCH_STAT
    input  logic                     [31: 0] emu_req_match_stat_emu_req_match_stat_wdata,          //! HW write data

    // Register EMU_TX_CPL_STAT
    input  logic                     [31: 0] emu_tx_cpl_stat_emu_tx_cpl_stat_wdata,          //! HW write data

    // Register EMU_BP_BLK_CNT_STAT
    input  logic                     [31: 0] emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_wdata,          //! HW write data

    // Register EMU_BP_VDAT_CNT_STAT
    input  logic                     [31: 0] emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_wdata,          //! HW write data

    // Register EMU_NON_PST_EXP_CK_STAT
    input  logic                     [31: 0] emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_wdata,          //! HW write data

    // Register EMU_NON_PST_ACT_CK_STAT
    input  logic                     [31: 0] emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_wdata,          //! HW write data

    // Register EMU_DOORBELL_QID_STAT
    input  logic                     [31: 0] emu_doorbell_qid_stat_emu_doorbell_qid_stat_wdata,          //! HW write data

    // Register EMU_REQ_COOKIE_STAT
    input  logic                     [31: 0] emu_req_cookie_stat_emu_req_cookie_stat_wdata,          //! HW write data

    // Register EMU_BYPASS_REQ_CNT
    input  logic                             emu_bypass_req_cnt_emu_bypass_req_cnt_we,             //! Control HW write (active high)
    input  logic                     [31: 0] emu_bypass_req_cnt_emu_bypass_req_cnt_wdata,          //! HW write data
    output logic                     [31: 0] emu_bypass_req_cnt_emu_bypass_req_cnt_q,              //! Current field value

    // Register EMU_BYPASS_CPL_CNT
    input  logic                             emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_we,             //! Control HW write (active high)
    input  logic                     [31: 0] emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_wdata,          //! HW write data
    output logic                     [31: 0] emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_q,              //! Current field value

    // Register EMU_COMB_CNT
    input  logic                             emu_comb_cnt_emu_comb_cnt_we,             //! Control HW write (active high)
    input  logic                     [31: 0] emu_comb_cnt_emu_comb_cnt_wdata,          //! HW write data
    output logic                     [31: 0] emu_comb_cnt_emu_comb_cnt_q,              //! Current field value

    // Register EMU_MWR_REQ_CNT
    input  logic                             emu_mwr_req_cnt_emu_mwr_req_cnt_we,             //! Control HW write (active high)
    input  logic                     [31: 0] emu_mwr_req_cnt_emu_mwr_req_cnt_wdata,          //! HW write data
    output logic                     [31: 0] emu_mwr_req_cnt_emu_mwr_req_cnt_q,              //! Current field value

    // Register EMU_BEQ2EMU_REQ_CNT
    input  logic                             emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_we,             //! Control HW write (active high)
    input  logic                     [31: 0] emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_wdata,          //! HW write data
    output logic                     [31: 0] emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_q,              //! Current field value

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [31: 0] emu_top_err_emu_top_err_next;
    logic                             emu_top_err_emu_top_err_anded;
    logic                             emu_top_err_emu_top_err_ored;
    logic                             emu_top_err_emu_top_err_xored;
    logic                           [31: 0] emu_reg_ctrl_err_emu_reg_ctrl_err_next;
    logic                             emu_reg_ctrl_err_emu_reg_ctrl_err_anded;
    logic                             emu_reg_ctrl_err_emu_reg_ctrl_err_ored;
    logic                             emu_reg_ctrl_err_emu_reg_ctrl_err_xored;
    logic                           [31: 0] emu_req_match_stat_emu_req_match_stat_q;
    logic                           [31: 0] emu_req_match_stat_emu_req_match_stat_next;
    logic                             emu_req_match_stat_emu_req_match_stat_anded;
    logic                             emu_req_match_stat_emu_req_match_stat_ored;
    logic                             emu_req_match_stat_emu_req_match_stat_xored;
    logic                           [31: 0] emu_tx_cpl_stat_emu_tx_cpl_stat_q;
    logic                           [31: 0] emu_tx_cpl_stat_emu_tx_cpl_stat_next;
    logic                             emu_tx_cpl_stat_emu_tx_cpl_stat_anded;
    logic                             emu_tx_cpl_stat_emu_tx_cpl_stat_ored;
    logic                             emu_tx_cpl_stat_emu_tx_cpl_stat_xored;
    logic                           [31: 0] emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_q;
    logic                           [31: 0] emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_next;
    logic                             emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_anded;
    logic                             emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_ored;
    logic                             emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_xored;
    logic                           [31: 0] emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_q;
    logic                           [31: 0] emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_next;
    logic                             emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_anded;
    logic                             emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_ored;
    logic                             emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_xored;
    logic                           [31: 0] emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_q;
    logic                           [31: 0] emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_next;
    logic                             emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_anded;
    logic                             emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_ored;
    logic                             emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_xored;
    logic                           [31: 0] emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_q;
    logic                           [31: 0] emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_next;
    logic                             emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_anded;
    logic                             emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_ored;
    logic                             emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_xored;
    logic                           [31: 0] emu_doorbell_qid_stat_emu_doorbell_qid_stat_q;
    logic                           [31: 0] emu_doorbell_qid_stat_emu_doorbell_qid_stat_next;
    logic                             emu_doorbell_qid_stat_emu_doorbell_qid_stat_anded;
    logic                             emu_doorbell_qid_stat_emu_doorbell_qid_stat_ored;
    logic                             emu_doorbell_qid_stat_emu_doorbell_qid_stat_xored;
    logic                           [31: 0] emu_req_cookie_stat_emu_req_cookie_stat_q;
    logic                           [31: 0] emu_req_cookie_stat_emu_req_cookie_stat_next;
    logic                             emu_req_cookie_stat_emu_req_cookie_stat_anded;
    logic                             emu_req_cookie_stat_emu_req_cookie_stat_ored;
    logic                             emu_req_cookie_stat_emu_req_cookie_stat_xored;
    logic                           [31: 0] emu_bypass_req_cnt_emu_bypass_req_cnt_next;
    logic                             emu_bypass_req_cnt_emu_bypass_req_cnt_anded;
    logic                             emu_bypass_req_cnt_emu_bypass_req_cnt_ored;
    logic                             emu_bypass_req_cnt_emu_bypass_req_cnt_xored;
    logic                           [31: 0] emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_next;
    logic                             emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_anded;
    logic                             emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_ored;
    logic                             emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_xored;
    logic                           [31: 0] emu_comb_cnt_emu_comb_cnt_next;
    logic                             emu_comb_cnt_emu_comb_cnt_anded;
    logic                             emu_comb_cnt_emu_comb_cnt_ored;
    logic                             emu_comb_cnt_emu_comb_cnt_xored;
    logic                           [31: 0] emu_mwr_req_cnt_emu_mwr_req_cnt_next;
    logic                             emu_mwr_req_cnt_emu_mwr_req_cnt_anded;
    logic                             emu_mwr_req_cnt_emu_mwr_req_cnt_ored;
    logic                             emu_mwr_req_cnt_emu_mwr_req_cnt_xored;
    logic                           [31: 0] emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_next;
    logic                             emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_anded;
    logic                             emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_ored;
    logic                             emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [ADDR_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] emu_top_err_rdata;
    logic                     [DATA_WIDTH-1:0] emu_reg_ctrl_err_rdata;
    logic                     [DATA_WIDTH-1:0] emu_req_match_stat_rdata;
    logic                     [DATA_WIDTH-1:0] emu_tx_cpl_stat_rdata;
    logic                     [DATA_WIDTH-1:0] emu_bp_blk_cnt_stat_rdata;
    logic                     [DATA_WIDTH-1:0] emu_bp_vdat_cnt_stat_rdata;
    logic                     [DATA_WIDTH-1:0] emu_non_pst_exp_ck_stat_rdata;
    logic                     [DATA_WIDTH-1:0] emu_non_pst_act_ck_stat_rdata;
    logic                     [DATA_WIDTH-1:0] emu_doorbell_qid_stat_rdata;
    logic                     [DATA_WIDTH-1:0] emu_req_cookie_stat_rdata;
    logic                     [DATA_WIDTH-1:0] emu_bypass_req_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] emu_bypass_cpl_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] emu_comb_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] emu_mwr_req_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] emu_beq2emu_req_cnt_rdata;

    assign sw_rdata = // or of each register return (masked)
                   emu_top_err_rdata | 
                   emu_reg_ctrl_err_rdata | 
                   emu_req_match_stat_rdata | 
                   emu_tx_cpl_stat_rdata | 
                   emu_bp_blk_cnt_stat_rdata | 
                   emu_bp_vdat_cnt_stat_rdata | 
                   emu_non_pst_exp_ck_stat_rdata | 
                   emu_non_pst_act_ck_stat_rdata | 
                   emu_doorbell_qid_stat_rdata | 
                   emu_req_cookie_stat_rdata | 
                   emu_bypass_req_cnt_rdata | 
                   emu_bypass_cpl_cnt_rdata | 
                   emu_comb_cnt_rdata | 
                   emu_mwr_req_cnt_rdata | 
                   emu_beq2emu_req_cnt_rdata;
            
        
    // ============================================================
    // Register: EMU_TOP_ERR
    //    [31: 0]          emu_top_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  emu_top_err_decode;
    logic                  emu_top_err_sw_wr;
    logic                  emu_top_err_sw_rd;
    logic [DATA_WIDTH-1:0] emu_top_err_q;

    assign emu_top_err_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign emu_top_err_sw_wr = sw_wr && emu_top_err_decode;
    assign emu_top_err_sw_rd = sw_rd && emu_top_err_decode;

    always_comb begin
        emu_top_err_q = '0;
        emu_top_err_q[31: 0] = emu_top_err_emu_top_err_q;
    end

    // masked version of return data
    assign emu_top_err_rdata = emu_top_err_sw_rd ? emu_top_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_top_err
    // ------------------------------------------------------------
    assign emu_top_err_emu_top_err_anded = & emu_top_err_emu_top_err_q;
    assign emu_top_err_emu_top_err_ored  = | emu_top_err_emu_top_err_q;
    assign emu_top_err_emu_top_err_xored = ^ emu_top_err_emu_top_err_q;

    // next hardware value
    assign emu_top_err_emu_top_err_next = emu_top_err_emu_top_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        emu_top_err_emu_top_err_q <= 64'd0;
    end else begin
        // Hardware Write
        if (emu_top_err_emu_top_err_we) begin
            emu_top_err_emu_top_err_q <= emu_top_err_emu_top_err_next;
        end
        // Software write
        else if (emu_top_err_sw_wr) begin
            emu_top_err_emu_top_err_q <= ~sw_masked_data[31: 0] &  emu_top_err_emu_top_err_q;
        end
    end
            
        
    // ============================================================
    // Register: EMU_REG_CTRL_ERR
    //    [31: 0]     emu_reg_ctrl_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  emu_reg_ctrl_err_decode;
    logic                  emu_reg_ctrl_err_sw_wr;
    logic                  emu_reg_ctrl_err_sw_rd;
    logic [DATA_WIDTH-1:0] emu_reg_ctrl_err_q;

    assign emu_reg_ctrl_err_decode = (addr == (ADDR_OFFSET+'h0+'h8));
    assign emu_reg_ctrl_err_sw_wr = sw_wr && emu_reg_ctrl_err_decode;
    assign emu_reg_ctrl_err_sw_rd = sw_rd && emu_reg_ctrl_err_decode;

    always_comb begin
        emu_reg_ctrl_err_q = '0;
        emu_reg_ctrl_err_q[31: 0] = emu_reg_ctrl_err_emu_reg_ctrl_err_q;
    end

    // masked version of return data
    assign emu_reg_ctrl_err_rdata = emu_reg_ctrl_err_sw_rd ? emu_reg_ctrl_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_reg_ctrl_err
    // ------------------------------------------------------------
    assign emu_reg_ctrl_err_emu_reg_ctrl_err_anded = & emu_reg_ctrl_err_emu_reg_ctrl_err_q;
    assign emu_reg_ctrl_err_emu_reg_ctrl_err_ored  = | emu_reg_ctrl_err_emu_reg_ctrl_err_q;
    assign emu_reg_ctrl_err_emu_reg_ctrl_err_xored = ^ emu_reg_ctrl_err_emu_reg_ctrl_err_q;

    // next hardware value
    assign emu_reg_ctrl_err_emu_reg_ctrl_err_next = emu_reg_ctrl_err_emu_reg_ctrl_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        emu_reg_ctrl_err_emu_reg_ctrl_err_q <= 64'd0;
    end else begin
        // Hardware Write
        if (emu_reg_ctrl_err_emu_reg_ctrl_err_we) begin
            emu_reg_ctrl_err_emu_reg_ctrl_err_q <= emu_reg_ctrl_err_emu_reg_ctrl_err_next;
        end
        // Software write
        else if (emu_reg_ctrl_err_sw_wr) begin
            emu_reg_ctrl_err_emu_reg_ctrl_err_q <= ~sw_masked_data[31: 0] &  emu_reg_ctrl_err_emu_reg_ctrl_err_q;
        end
    end
            
        
    // ============================================================
    // Register: EMU_REQ_MATCH_STAT
    //    [31: 0]   emu_req_match_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emu_req_match_stat_decode;
    logic                  emu_req_match_stat_sw_wr;
    logic                  emu_req_match_stat_sw_rd;
    logic [DATA_WIDTH-1:0] emu_req_match_stat_q;

    assign emu_req_match_stat_decode = (addr == (ADDR_OFFSET+'h0+'h100));
    assign emu_req_match_stat_sw_wr = sw_wr && emu_req_match_stat_decode;
    assign emu_req_match_stat_sw_rd = sw_rd && emu_req_match_stat_decode;

    always_comb begin
        emu_req_match_stat_q = '0;
        emu_req_match_stat_q[31: 0] = emu_req_match_stat_emu_req_match_stat_q;
    end

    // masked version of return data
    assign emu_req_match_stat_rdata = emu_req_match_stat_sw_rd ? emu_req_match_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_req_match_stat (wire)
    // ------------------------------------------------------------
    assign emu_req_match_stat_emu_req_match_stat_anded = & emu_req_match_stat_emu_req_match_stat_q;
    assign emu_req_match_stat_emu_req_match_stat_ored  = | emu_req_match_stat_emu_req_match_stat_q;
    assign emu_req_match_stat_emu_req_match_stat_xored = ^ emu_req_match_stat_emu_req_match_stat_q;

    // next hardware value
    assign emu_req_match_stat_emu_req_match_stat_next = emu_req_match_stat_emu_req_match_stat_wdata;
    assign emu_req_match_stat_emu_req_match_stat_q = emu_req_match_stat_emu_req_match_stat_next;
            
        
    // ============================================================
    // Register: EMU_TX_CPL_STAT
    //    [31: 0]      emu_tx_cpl_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emu_tx_cpl_stat_decode;
    logic                  emu_tx_cpl_stat_sw_wr;
    logic                  emu_tx_cpl_stat_sw_rd;
    logic [DATA_WIDTH-1:0] emu_tx_cpl_stat_q;

    assign emu_tx_cpl_stat_decode = (addr == (ADDR_OFFSET+'h0+'h108));
    assign emu_tx_cpl_stat_sw_wr = sw_wr && emu_tx_cpl_stat_decode;
    assign emu_tx_cpl_stat_sw_rd = sw_rd && emu_tx_cpl_stat_decode;

    always_comb begin
        emu_tx_cpl_stat_q = '0;
        emu_tx_cpl_stat_q[31: 0] = emu_tx_cpl_stat_emu_tx_cpl_stat_q;
    end

    // masked version of return data
    assign emu_tx_cpl_stat_rdata = emu_tx_cpl_stat_sw_rd ? emu_tx_cpl_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_tx_cpl_stat (wire)
    // ------------------------------------------------------------
    assign emu_tx_cpl_stat_emu_tx_cpl_stat_anded = & emu_tx_cpl_stat_emu_tx_cpl_stat_q;
    assign emu_tx_cpl_stat_emu_tx_cpl_stat_ored  = | emu_tx_cpl_stat_emu_tx_cpl_stat_q;
    assign emu_tx_cpl_stat_emu_tx_cpl_stat_xored = ^ emu_tx_cpl_stat_emu_tx_cpl_stat_q;

    // next hardware value
    assign emu_tx_cpl_stat_emu_tx_cpl_stat_next = emu_tx_cpl_stat_emu_tx_cpl_stat_wdata;
    assign emu_tx_cpl_stat_emu_tx_cpl_stat_q = emu_tx_cpl_stat_emu_tx_cpl_stat_next;
            
        
    // ============================================================
    // Register: EMU_BP_BLK_CNT_STAT
    //    [31: 0]  emu_bp_blk_cnt_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emu_bp_blk_cnt_stat_decode;
    logic                  emu_bp_blk_cnt_stat_sw_wr;
    logic                  emu_bp_blk_cnt_stat_sw_rd;
    logic [DATA_WIDTH-1:0] emu_bp_blk_cnt_stat_q;

    assign emu_bp_blk_cnt_stat_decode = (addr == (ADDR_OFFSET+'h0+'h110));
    assign emu_bp_blk_cnt_stat_sw_wr = sw_wr && emu_bp_blk_cnt_stat_decode;
    assign emu_bp_blk_cnt_stat_sw_rd = sw_rd && emu_bp_blk_cnt_stat_decode;

    always_comb begin
        emu_bp_blk_cnt_stat_q = '0;
        emu_bp_blk_cnt_stat_q[31: 0] = emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_q;
    end

    // masked version of return data
    assign emu_bp_blk_cnt_stat_rdata = emu_bp_blk_cnt_stat_sw_rd ? emu_bp_blk_cnt_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_bp_blk_cnt_stat (wire)
    // ------------------------------------------------------------
    assign emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_anded = & emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_q;
    assign emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_ored  = | emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_q;
    assign emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_xored = ^ emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_q;

    // next hardware value
    assign emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_next = emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_wdata;
    assign emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_q = emu_bp_blk_cnt_stat_emu_bp_blk_cnt_stat_next;
            
        
    // ============================================================
    // Register: EMU_BP_VDAT_CNT_STAT
    //    [31: 0] emu_bp_vdat_cnt_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emu_bp_vdat_cnt_stat_decode;
    logic                  emu_bp_vdat_cnt_stat_sw_wr;
    logic                  emu_bp_vdat_cnt_stat_sw_rd;
    logic [DATA_WIDTH-1:0] emu_bp_vdat_cnt_stat_q;

    assign emu_bp_vdat_cnt_stat_decode = (addr == (ADDR_OFFSET+'h0+'h118));
    assign emu_bp_vdat_cnt_stat_sw_wr = sw_wr && emu_bp_vdat_cnt_stat_decode;
    assign emu_bp_vdat_cnt_stat_sw_rd = sw_rd && emu_bp_vdat_cnt_stat_decode;

    always_comb begin
        emu_bp_vdat_cnt_stat_q = '0;
        emu_bp_vdat_cnt_stat_q[31: 0] = emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_q;
    end

    // masked version of return data
    assign emu_bp_vdat_cnt_stat_rdata = emu_bp_vdat_cnt_stat_sw_rd ? emu_bp_vdat_cnt_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_bp_vdat_cnt_stat (wire)
    // ------------------------------------------------------------
    assign emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_anded = & emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_q;
    assign emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_ored  = | emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_q;
    assign emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_xored = ^ emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_q;

    // next hardware value
    assign emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_next = emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_wdata;
    assign emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_q = emu_bp_vdat_cnt_stat_emu_bp_vdat_cnt_stat_next;
            
        
    // ============================================================
    // Register: EMU_NON_PST_EXP_CK_STAT
    //    [31: 0] emu_non_pst_exp_ck_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emu_non_pst_exp_ck_stat_decode;
    logic                  emu_non_pst_exp_ck_stat_sw_wr;
    logic                  emu_non_pst_exp_ck_stat_sw_rd;
    logic [DATA_WIDTH-1:0] emu_non_pst_exp_ck_stat_q;

    assign emu_non_pst_exp_ck_stat_decode = (addr == (ADDR_OFFSET+'h0+'h120));
    assign emu_non_pst_exp_ck_stat_sw_wr = sw_wr && emu_non_pst_exp_ck_stat_decode;
    assign emu_non_pst_exp_ck_stat_sw_rd = sw_rd && emu_non_pst_exp_ck_stat_decode;

    always_comb begin
        emu_non_pst_exp_ck_stat_q = '0;
        emu_non_pst_exp_ck_stat_q[31: 0] = emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_q;
    end

    // masked version of return data
    assign emu_non_pst_exp_ck_stat_rdata = emu_non_pst_exp_ck_stat_sw_rd ? emu_non_pst_exp_ck_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_non_pst_exp_ck_stat (wire)
    // ------------------------------------------------------------
    assign emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_anded = & emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_q;
    assign emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_ored  = | emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_q;
    assign emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_xored = ^ emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_q;

    // next hardware value
    assign emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_next = emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_wdata;
    assign emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_q = emu_non_pst_exp_ck_stat_emu_non_pst_exp_ck_stat_next;
            
        
    // ============================================================
    // Register: EMU_NON_PST_ACT_CK_STAT
    //    [31: 0] emu_non_pst_act_ck_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emu_non_pst_act_ck_stat_decode;
    logic                  emu_non_pst_act_ck_stat_sw_wr;
    logic                  emu_non_pst_act_ck_stat_sw_rd;
    logic [DATA_WIDTH-1:0] emu_non_pst_act_ck_stat_q;

    assign emu_non_pst_act_ck_stat_decode = (addr == (ADDR_OFFSET+'h0+'h128));
    assign emu_non_pst_act_ck_stat_sw_wr = sw_wr && emu_non_pst_act_ck_stat_decode;
    assign emu_non_pst_act_ck_stat_sw_rd = sw_rd && emu_non_pst_act_ck_stat_decode;

    always_comb begin
        emu_non_pst_act_ck_stat_q = '0;
        emu_non_pst_act_ck_stat_q[31: 0] = emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_q;
    end

    // masked version of return data
    assign emu_non_pst_act_ck_stat_rdata = emu_non_pst_act_ck_stat_sw_rd ? emu_non_pst_act_ck_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_non_pst_act_ck_stat (wire)
    // ------------------------------------------------------------
    assign emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_anded = & emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_q;
    assign emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_ored  = | emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_q;
    assign emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_xored = ^ emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_q;

    // next hardware value
    assign emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_next = emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_wdata;
    assign emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_q = emu_non_pst_act_ck_stat_emu_non_pst_act_ck_stat_next;
            
        
    // ============================================================
    // Register: EMU_DOORBELL_QID_STAT
    //    [31: 0] emu_doorbell_qid_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emu_doorbell_qid_stat_decode;
    logic                  emu_doorbell_qid_stat_sw_wr;
    logic                  emu_doorbell_qid_stat_sw_rd;
    logic [DATA_WIDTH-1:0] emu_doorbell_qid_stat_q;

    assign emu_doorbell_qid_stat_decode = (addr == (ADDR_OFFSET+'h0+'h130));
    assign emu_doorbell_qid_stat_sw_wr = sw_wr && emu_doorbell_qid_stat_decode;
    assign emu_doorbell_qid_stat_sw_rd = sw_rd && emu_doorbell_qid_stat_decode;

    always_comb begin
        emu_doorbell_qid_stat_q = '0;
        emu_doorbell_qid_stat_q[31: 0] = emu_doorbell_qid_stat_emu_doorbell_qid_stat_q;
    end

    // masked version of return data
    assign emu_doorbell_qid_stat_rdata = emu_doorbell_qid_stat_sw_rd ? emu_doorbell_qid_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_doorbell_qid_stat (wire)
    // ------------------------------------------------------------
    assign emu_doorbell_qid_stat_emu_doorbell_qid_stat_anded = & emu_doorbell_qid_stat_emu_doorbell_qid_stat_q;
    assign emu_doorbell_qid_stat_emu_doorbell_qid_stat_ored  = | emu_doorbell_qid_stat_emu_doorbell_qid_stat_q;
    assign emu_doorbell_qid_stat_emu_doorbell_qid_stat_xored = ^ emu_doorbell_qid_stat_emu_doorbell_qid_stat_q;

    // next hardware value
    assign emu_doorbell_qid_stat_emu_doorbell_qid_stat_next = emu_doorbell_qid_stat_emu_doorbell_qid_stat_wdata;
    assign emu_doorbell_qid_stat_emu_doorbell_qid_stat_q = emu_doorbell_qid_stat_emu_doorbell_qid_stat_next;
            
        
    // ============================================================
    // Register: EMU_REQ_COOKIE_STAT
    //    [31: 0]  emu_req_cookie_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emu_req_cookie_stat_decode;
    logic                  emu_req_cookie_stat_sw_wr;
    logic                  emu_req_cookie_stat_sw_rd;
    logic [DATA_WIDTH-1:0] emu_req_cookie_stat_q;

    assign emu_req_cookie_stat_decode = (addr == (ADDR_OFFSET+'h0+'h138));
    assign emu_req_cookie_stat_sw_wr = sw_wr && emu_req_cookie_stat_decode;
    assign emu_req_cookie_stat_sw_rd = sw_rd && emu_req_cookie_stat_decode;

    always_comb begin
        emu_req_cookie_stat_q = '0;
        emu_req_cookie_stat_q[31: 0] = emu_req_cookie_stat_emu_req_cookie_stat_q;
    end

    // masked version of return data
    assign emu_req_cookie_stat_rdata = emu_req_cookie_stat_sw_rd ? emu_req_cookie_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_req_cookie_stat (wire)
    // ------------------------------------------------------------
    assign emu_req_cookie_stat_emu_req_cookie_stat_anded = & emu_req_cookie_stat_emu_req_cookie_stat_q;
    assign emu_req_cookie_stat_emu_req_cookie_stat_ored  = | emu_req_cookie_stat_emu_req_cookie_stat_q;
    assign emu_req_cookie_stat_emu_req_cookie_stat_xored = ^ emu_req_cookie_stat_emu_req_cookie_stat_q;

    // next hardware value
    assign emu_req_cookie_stat_emu_req_cookie_stat_next = emu_req_cookie_stat_emu_req_cookie_stat_wdata;
    assign emu_req_cookie_stat_emu_req_cookie_stat_q = emu_req_cookie_stat_emu_req_cookie_stat_next;
            
        
    // ============================================================
    // Register: EMU_BYPASS_REQ_CNT
    //    [31: 0]   emu_bypass_req_cnt: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  emu_bypass_req_cnt_decode;
    logic                  emu_bypass_req_cnt_sw_wr;
    logic                  emu_bypass_req_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] emu_bypass_req_cnt_q;

    assign emu_bypass_req_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h200));
    assign emu_bypass_req_cnt_sw_wr = sw_wr && emu_bypass_req_cnt_decode;
    assign emu_bypass_req_cnt_sw_rd = sw_rd && emu_bypass_req_cnt_decode;

    always_comb begin
        emu_bypass_req_cnt_q = '0;
        emu_bypass_req_cnt_q[31: 0] = emu_bypass_req_cnt_emu_bypass_req_cnt_q;
    end

    // masked version of return data
    assign emu_bypass_req_cnt_rdata = emu_bypass_req_cnt_sw_rd ? emu_bypass_req_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_bypass_req_cnt
    // ------------------------------------------------------------
    assign emu_bypass_req_cnt_emu_bypass_req_cnt_anded = & emu_bypass_req_cnt_emu_bypass_req_cnt_q;
    assign emu_bypass_req_cnt_emu_bypass_req_cnt_ored  = | emu_bypass_req_cnt_emu_bypass_req_cnt_q;
    assign emu_bypass_req_cnt_emu_bypass_req_cnt_xored = ^ emu_bypass_req_cnt_emu_bypass_req_cnt_q;

    // next hardware value
    assign emu_bypass_req_cnt_emu_bypass_req_cnt_next = emu_bypass_req_cnt_emu_bypass_req_cnt_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        emu_bypass_req_cnt_emu_bypass_req_cnt_q <= 64'd0;
    end else begin
        // Hardware Write
        if (emu_bypass_req_cnt_emu_bypass_req_cnt_we) begin
            emu_bypass_req_cnt_emu_bypass_req_cnt_q <= emu_bypass_req_cnt_emu_bypass_req_cnt_next;
        end
        // Software write
        else if (emu_bypass_req_cnt_sw_wr) begin
            emu_bypass_req_cnt_emu_bypass_req_cnt_q <= ~sw_masked_data[31: 0] &  emu_bypass_req_cnt_emu_bypass_req_cnt_q;
        end
    end
            
        
    // ============================================================
    // Register: EMU_BYPASS_CPL_CNT
    //    [31: 0]   emu_bypass_cpl_cnt: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  emu_bypass_cpl_cnt_decode;
    logic                  emu_bypass_cpl_cnt_sw_wr;
    logic                  emu_bypass_cpl_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] emu_bypass_cpl_cnt_q;

    assign emu_bypass_cpl_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h208));
    assign emu_bypass_cpl_cnt_sw_wr = sw_wr && emu_bypass_cpl_cnt_decode;
    assign emu_bypass_cpl_cnt_sw_rd = sw_rd && emu_bypass_cpl_cnt_decode;

    always_comb begin
        emu_bypass_cpl_cnt_q = '0;
        emu_bypass_cpl_cnt_q[31: 0] = emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_q;
    end

    // masked version of return data
    assign emu_bypass_cpl_cnt_rdata = emu_bypass_cpl_cnt_sw_rd ? emu_bypass_cpl_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_bypass_cpl_cnt
    // ------------------------------------------------------------
    assign emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_anded = & emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_q;
    assign emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_ored  = | emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_q;
    assign emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_xored = ^ emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_q;

    // next hardware value
    assign emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_next = emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_q <= 64'd0;
    end else begin
        // Hardware Write
        if (emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_we) begin
            emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_q <= emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_next;
        end
        // Software write
        else if (emu_bypass_cpl_cnt_sw_wr) begin
            emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_q <= ~sw_masked_data[31: 0] &  emu_bypass_cpl_cnt_emu_bypass_cpl_cnt_q;
        end
    end
            
        
    // ============================================================
    // Register: EMU_COMB_CNT
    //    [31: 0]         emu_comb_cnt: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  emu_comb_cnt_decode;
    logic                  emu_comb_cnt_sw_wr;
    logic                  emu_comb_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] emu_comb_cnt_q;

    assign emu_comb_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h210));
    assign emu_comb_cnt_sw_wr = sw_wr && emu_comb_cnt_decode;
    assign emu_comb_cnt_sw_rd = sw_rd && emu_comb_cnt_decode;

    always_comb begin
        emu_comb_cnt_q = '0;
        emu_comb_cnt_q[31: 0] = emu_comb_cnt_emu_comb_cnt_q;
    end

    // masked version of return data
    assign emu_comb_cnt_rdata = emu_comb_cnt_sw_rd ? emu_comb_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_comb_cnt
    // ------------------------------------------------------------
    assign emu_comb_cnt_emu_comb_cnt_anded = & emu_comb_cnt_emu_comb_cnt_q;
    assign emu_comb_cnt_emu_comb_cnt_ored  = | emu_comb_cnt_emu_comb_cnt_q;
    assign emu_comb_cnt_emu_comb_cnt_xored = ^ emu_comb_cnt_emu_comb_cnt_q;

    // next hardware value
    assign emu_comb_cnt_emu_comb_cnt_next = emu_comb_cnt_emu_comb_cnt_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        emu_comb_cnt_emu_comb_cnt_q <= 64'd0;
    end else begin
        // Hardware Write
        if (emu_comb_cnt_emu_comb_cnt_we) begin
            emu_comb_cnt_emu_comb_cnt_q <= emu_comb_cnt_emu_comb_cnt_next;
        end
        // Software write
        else if (emu_comb_cnt_sw_wr) begin
            emu_comb_cnt_emu_comb_cnt_q <= ~sw_masked_data[31: 0] &  emu_comb_cnt_emu_comb_cnt_q;
        end
    end
            
        
    // ============================================================
    // Register: EMU_MWR_REQ_CNT
    //    [31: 0]      emu_mwr_req_cnt: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  emu_mwr_req_cnt_decode;
    logic                  emu_mwr_req_cnt_sw_wr;
    logic                  emu_mwr_req_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] emu_mwr_req_cnt_q;

    assign emu_mwr_req_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h218));
    assign emu_mwr_req_cnt_sw_wr = sw_wr && emu_mwr_req_cnt_decode;
    assign emu_mwr_req_cnt_sw_rd = sw_rd && emu_mwr_req_cnt_decode;

    always_comb begin
        emu_mwr_req_cnt_q = '0;
        emu_mwr_req_cnt_q[31: 0] = emu_mwr_req_cnt_emu_mwr_req_cnt_q;
    end

    // masked version of return data
    assign emu_mwr_req_cnt_rdata = emu_mwr_req_cnt_sw_rd ? emu_mwr_req_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_mwr_req_cnt
    // ------------------------------------------------------------
    assign emu_mwr_req_cnt_emu_mwr_req_cnt_anded = & emu_mwr_req_cnt_emu_mwr_req_cnt_q;
    assign emu_mwr_req_cnt_emu_mwr_req_cnt_ored  = | emu_mwr_req_cnt_emu_mwr_req_cnt_q;
    assign emu_mwr_req_cnt_emu_mwr_req_cnt_xored = ^ emu_mwr_req_cnt_emu_mwr_req_cnt_q;

    // next hardware value
    assign emu_mwr_req_cnt_emu_mwr_req_cnt_next = emu_mwr_req_cnt_emu_mwr_req_cnt_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        emu_mwr_req_cnt_emu_mwr_req_cnt_q <= 64'd0;
    end else begin
        // Hardware Write
        if (emu_mwr_req_cnt_emu_mwr_req_cnt_we) begin
            emu_mwr_req_cnt_emu_mwr_req_cnt_q <= emu_mwr_req_cnt_emu_mwr_req_cnt_next;
        end
        // Software write
        else if (emu_mwr_req_cnt_sw_wr) begin
            emu_mwr_req_cnt_emu_mwr_req_cnt_q <= ~sw_masked_data[31: 0] &  emu_mwr_req_cnt_emu_mwr_req_cnt_q;
        end
    end
            
        
    // ============================================================
    // Register: EMU_BEQ2EMU_REQ_CNT
    //    [31: 0]  emu_beq2emu_req_cnt: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  emu_beq2emu_req_cnt_decode;
    logic                  emu_beq2emu_req_cnt_sw_wr;
    logic                  emu_beq2emu_req_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] emu_beq2emu_req_cnt_q;

    assign emu_beq2emu_req_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h220));
    assign emu_beq2emu_req_cnt_sw_wr = sw_wr && emu_beq2emu_req_cnt_decode;
    assign emu_beq2emu_req_cnt_sw_rd = sw_rd && emu_beq2emu_req_cnt_decode;

    always_comb begin
        emu_beq2emu_req_cnt_q = '0;
        emu_beq2emu_req_cnt_q[31: 0] = emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_q;
    end

    // masked version of return data
    assign emu_beq2emu_req_cnt_rdata = emu_beq2emu_req_cnt_sw_rd ? emu_beq2emu_req_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: emu_beq2emu_req_cnt
    // ------------------------------------------------------------
    assign emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_anded = & emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_q;
    assign emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_ored  = | emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_q;
    assign emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_xored = ^ emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_q;

    // next hardware value
    assign emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_next = emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_q <= 64'd0;
    end else begin
        // Hardware Write
        if (emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_we) begin
            emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_q <= emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_next;
        end
        // Software write
        else if (emu_beq2emu_req_cnt_sw_wr) begin
            emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_q <= ~sw_masked_data[31: 0] &  emu_beq2emu_req_cnt_emu_beq2emu_req_cnt_q;
        end
    end

endmodule: emu_dfx
