// This file was autogenerated by PeakRDL-verilog
module virtio_blk_desc_engine_dfx #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register VIRTIO_BLK_DESC_ENGINE_MAX_CHAIN_LEN
    output logic                     [19: 0] virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_q,              //! Current field value

    // Register VIRTIO_BLK_DESC_ENGINE_ALLOC_ERR
    input  logic                             virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_we,             //! Control HW write (active high)
    input  logic                     [63: 0] virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_wdata,          //! HW write data
    output logic                     [63: 0] virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_q,              //! Current field value

    // Register VIRTIO_BLK_DESC_ENGINE_FREE_ERR
    input  logic                             virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_we,             //! Control HW write (active high)
    input  logic                     [63: 0] virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_wdata,          //! HW write data
    output logic                     [63: 0] virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_q,              //! Current field value

    // Register VIRTIO_BLK_DESC_ENGINE_CORE_ERR
    input  logic                             virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_we,             //! Control HW write (active high)
    input  logic                     [63: 0] virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_wdata,          //! HW write data
    output logic                     [63: 0] virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_q,              //! Current field value

    // Register VIRTIO_BLK_DESC_ENGINE_ALLOC_STATUS
    input  logic                     [63: 0] virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_wdata,          //! HW write data

    // Register VIRTIO_BLK_DESC_ENGINE_FREE_STATUS
    input  logic                     [63: 0] virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_wdata,          //! HW write data

    // Register VIRTIO_BLK_DESC_ENGINE_CORE_STATUS
    input  logic                     [63: 0] virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_wdata,          //! HW write data

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [19: 0] virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_next;
    logic                             virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_anded;
    logic                             virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_ored;
    logic                             virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_xored;
    logic                           [63: 0] virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_next;
    logic                             virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_anded;
    logic                             virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_ored;
    logic                             virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_xored;
    logic                           [63: 0] virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_next;
    logic                             virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_anded;
    logic                             virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_ored;
    logic                             virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_xored;
    logic                           [63: 0] virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_next;
    logic                             virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_anded;
    logic                             virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_ored;
    logic                             virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_xored;
    logic                           [63: 0] virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_q;
    logic                           [63: 0] virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_next;
    logic                             virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_anded;
    logic                             virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_ored;
    logic                             virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_xored;
    logic                           [63: 0] virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_q;
    logic                           [63: 0] virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_next;
    logic                             virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_anded;
    logic                             virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_ored;
    logic                             virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_xored;
    logic                           [63: 0] virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_q;
    logic                           [63: 0] virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_next;
    logic                             virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_anded;
    logic                             virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_ored;
    logic                             virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [ADDR_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] virtio_blk_desc_engine_max_chain_len_rdata;
    logic                     [DATA_WIDTH-1:0] virtio_blk_desc_engine_alloc_err_rdata;
    logic                     [DATA_WIDTH-1:0] virtio_blk_desc_engine_free_err_rdata;
    logic                     [DATA_WIDTH-1:0] virtio_blk_desc_engine_core_err_rdata;
    logic                     [DATA_WIDTH-1:0] virtio_blk_desc_engine_alloc_status_rdata;
    logic                     [DATA_WIDTH-1:0] virtio_blk_desc_engine_free_status_rdata;
    logic                     [DATA_WIDTH-1:0] virtio_blk_desc_engine_core_status_rdata;

    assign sw_rdata = // or of each register return (masked)
                   virtio_blk_desc_engine_max_chain_len_rdata | 
                   virtio_blk_desc_engine_alloc_err_rdata | 
                   virtio_blk_desc_engine_free_err_rdata | 
                   virtio_blk_desc_engine_core_err_rdata | 
                   virtio_blk_desc_engine_alloc_status_rdata | 
                   virtio_blk_desc_engine_free_status_rdata | 
                   virtio_blk_desc_engine_core_status_rdata;
            
        
    // ============================================================
    // Register: VIRTIO_BLK_DESC_ENGINE_MAX_CHAIN_LEN
    //    [19: 0] virtio_blk_desc_engine_max_chain_len: hw=r     sw=rw    reset=0x8000
    // ============================================================
    logic                  virtio_blk_desc_engine_max_chain_len_decode;
    logic                  virtio_blk_desc_engine_max_chain_len_sw_wr;
    logic                  virtio_blk_desc_engine_max_chain_len_sw_rd;
    logic [DATA_WIDTH-1:0] virtio_blk_desc_engine_max_chain_len_q;

    assign virtio_blk_desc_engine_max_chain_len_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign virtio_blk_desc_engine_max_chain_len_sw_wr = sw_wr && virtio_blk_desc_engine_max_chain_len_decode;
    assign virtio_blk_desc_engine_max_chain_len_sw_rd = sw_rd && virtio_blk_desc_engine_max_chain_len_decode;

    always_comb begin
        virtio_blk_desc_engine_max_chain_len_q = '0;
        virtio_blk_desc_engine_max_chain_len_q[19: 0] = virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_q;
    end

    // masked version of return data
    assign virtio_blk_desc_engine_max_chain_len_rdata = virtio_blk_desc_engine_max_chain_len_sw_rd ? virtio_blk_desc_engine_max_chain_len_q : 'b0;

    // ------------------------------------------------------------
    // Field: virtio_blk_desc_engine_max_chain_len
    // ------------------------------------------------------------
    assign virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_anded = & virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_q;
    assign virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_ored  = | virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_q;
    assign virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_xored = ^ virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_q <= 64'd32768;
    end else begin
        // Software write
        if (virtio_blk_desc_engine_max_chain_len_sw_wr) begin
            virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_q <=  sw_masked_data[19: 0] | (virtio_blk_desc_engine_max_chain_len_virtio_blk_desc_engine_max_chain_len_q & ~sw_mask[19: 0]);
        end
    end
            
        
    // ============================================================
    // Register: VIRTIO_BLK_DESC_ENGINE_ALLOC_ERR
    //    [63: 0] virtio_blk_desc_engine_alloc_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  virtio_blk_desc_engine_alloc_err_decode;
    logic                  virtio_blk_desc_engine_alloc_err_sw_wr;
    logic                  virtio_blk_desc_engine_alloc_err_sw_rd;
    logic [DATA_WIDTH-1:0] virtio_blk_desc_engine_alloc_err_q;

    assign virtio_blk_desc_engine_alloc_err_decode = (addr == (ADDR_OFFSET+'h0+'h100));
    assign virtio_blk_desc_engine_alloc_err_sw_wr = sw_wr && virtio_blk_desc_engine_alloc_err_decode;
    assign virtio_blk_desc_engine_alloc_err_sw_rd = sw_rd && virtio_blk_desc_engine_alloc_err_decode;

    always_comb begin
        virtio_blk_desc_engine_alloc_err_q = '0;
        virtio_blk_desc_engine_alloc_err_q[63: 0] = virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_q;
    end

    // masked version of return data
    assign virtio_blk_desc_engine_alloc_err_rdata = virtio_blk_desc_engine_alloc_err_sw_rd ? virtio_blk_desc_engine_alloc_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: virtio_blk_desc_engine_alloc_err
    // ------------------------------------------------------------
    assign virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_anded = & virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_q;
    assign virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_ored  = | virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_q;
    assign virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_xored = ^ virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_q;

    // next hardware value
    assign virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_next = virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_q <= 64'd0;
    end else begin
        // Hardware Write
        if (virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_we) begin
            virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_q <= virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_next;
        end
        // Software write
        else if (virtio_blk_desc_engine_alloc_err_sw_wr) begin
            virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_q <= ~sw_masked_data[63: 0] &  virtio_blk_desc_engine_alloc_err_virtio_blk_desc_engine_alloc_err_q;
        end
    end
            
        
    // ============================================================
    // Register: VIRTIO_BLK_DESC_ENGINE_FREE_ERR
    //    [63: 0] virtio_blk_desc_engine_free_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  virtio_blk_desc_engine_free_err_decode;
    logic                  virtio_blk_desc_engine_free_err_sw_wr;
    logic                  virtio_blk_desc_engine_free_err_sw_rd;
    logic [DATA_WIDTH-1:0] virtio_blk_desc_engine_free_err_q;

    assign virtio_blk_desc_engine_free_err_decode = (addr == (ADDR_OFFSET+'h0+'h108));
    assign virtio_blk_desc_engine_free_err_sw_wr = sw_wr && virtio_blk_desc_engine_free_err_decode;
    assign virtio_blk_desc_engine_free_err_sw_rd = sw_rd && virtio_blk_desc_engine_free_err_decode;

    always_comb begin
        virtio_blk_desc_engine_free_err_q = '0;
        virtio_blk_desc_engine_free_err_q[63: 0] = virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_q;
    end

    // masked version of return data
    assign virtio_blk_desc_engine_free_err_rdata = virtio_blk_desc_engine_free_err_sw_rd ? virtio_blk_desc_engine_free_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: virtio_blk_desc_engine_free_err
    // ------------------------------------------------------------
    assign virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_anded = & virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_q;
    assign virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_ored  = | virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_q;
    assign virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_xored = ^ virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_q;

    // next hardware value
    assign virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_next = virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_q <= 64'd0;
    end else begin
        // Hardware Write
        if (virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_we) begin
            virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_q <= virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_next;
        end
        // Software write
        else if (virtio_blk_desc_engine_free_err_sw_wr) begin
            virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_q <= ~sw_masked_data[63: 0] &  virtio_blk_desc_engine_free_err_virtio_blk_desc_engine_free_err_q;
        end
    end
            
        
    // ============================================================
    // Register: VIRTIO_BLK_DESC_ENGINE_CORE_ERR
    //    [63: 0] virtio_blk_desc_engine_core_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  virtio_blk_desc_engine_core_err_decode;
    logic                  virtio_blk_desc_engine_core_err_sw_wr;
    logic                  virtio_blk_desc_engine_core_err_sw_rd;
    logic [DATA_WIDTH-1:0] virtio_blk_desc_engine_core_err_q;

    assign virtio_blk_desc_engine_core_err_decode = (addr == (ADDR_OFFSET+'h0+'h110));
    assign virtio_blk_desc_engine_core_err_sw_wr = sw_wr && virtio_blk_desc_engine_core_err_decode;
    assign virtio_blk_desc_engine_core_err_sw_rd = sw_rd && virtio_blk_desc_engine_core_err_decode;

    always_comb begin
        virtio_blk_desc_engine_core_err_q = '0;
        virtio_blk_desc_engine_core_err_q[63: 0] = virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_q;
    end

    // masked version of return data
    assign virtio_blk_desc_engine_core_err_rdata = virtio_blk_desc_engine_core_err_sw_rd ? virtio_blk_desc_engine_core_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: virtio_blk_desc_engine_core_err
    // ------------------------------------------------------------
    assign virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_anded = & virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_q;
    assign virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_ored  = | virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_q;
    assign virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_xored = ^ virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_q;

    // next hardware value
    assign virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_next = virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_q <= 64'd0;
    end else begin
        // Hardware Write
        if (virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_we) begin
            virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_q <= virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_next;
        end
        // Software write
        else if (virtio_blk_desc_engine_core_err_sw_wr) begin
            virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_q <= ~sw_masked_data[63: 0] &  virtio_blk_desc_engine_core_err_virtio_blk_desc_engine_core_err_q;
        end
    end
            
        
    // ============================================================
    // Register: VIRTIO_BLK_DESC_ENGINE_ALLOC_STATUS
    //    [63: 0] virtio_blk_desc_engine_alloc_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  virtio_blk_desc_engine_alloc_status_decode;
    logic                  virtio_blk_desc_engine_alloc_status_sw_wr;
    logic                  virtio_blk_desc_engine_alloc_status_sw_rd;
    logic [DATA_WIDTH-1:0] virtio_blk_desc_engine_alloc_status_q;

    assign virtio_blk_desc_engine_alloc_status_decode = (addr == (ADDR_OFFSET+'h0+'h120));
    assign virtio_blk_desc_engine_alloc_status_sw_wr = sw_wr && virtio_blk_desc_engine_alloc_status_decode;
    assign virtio_blk_desc_engine_alloc_status_sw_rd = sw_rd && virtio_blk_desc_engine_alloc_status_decode;

    always_comb begin
        virtio_blk_desc_engine_alloc_status_q = '0;
        virtio_blk_desc_engine_alloc_status_q[63: 0] = virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_q;
    end

    // masked version of return data
    assign virtio_blk_desc_engine_alloc_status_rdata = virtio_blk_desc_engine_alloc_status_sw_rd ? virtio_blk_desc_engine_alloc_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: virtio_blk_desc_engine_alloc_status (wire)
    // ------------------------------------------------------------
    assign virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_anded = & virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_q;
    assign virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_ored  = | virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_q;
    assign virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_xored = ^ virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_q;

    // next hardware value
    assign virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_next = virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_wdata;
    assign virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_q = virtio_blk_desc_engine_alloc_status_virtio_blk_desc_engine_alloc_status_next;
            
        
    // ============================================================
    // Register: VIRTIO_BLK_DESC_ENGINE_FREE_STATUS
    //    [63: 0] virtio_blk_desc_engine_free_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  virtio_blk_desc_engine_free_status_decode;
    logic                  virtio_blk_desc_engine_free_status_sw_wr;
    logic                  virtio_blk_desc_engine_free_status_sw_rd;
    logic [DATA_WIDTH-1:0] virtio_blk_desc_engine_free_status_q;

    assign virtio_blk_desc_engine_free_status_decode = (addr == (ADDR_OFFSET+'h0+'h128));
    assign virtio_blk_desc_engine_free_status_sw_wr = sw_wr && virtio_blk_desc_engine_free_status_decode;
    assign virtio_blk_desc_engine_free_status_sw_rd = sw_rd && virtio_blk_desc_engine_free_status_decode;

    always_comb begin
        virtio_blk_desc_engine_free_status_q = '0;
        virtio_blk_desc_engine_free_status_q[63: 0] = virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_q;
    end

    // masked version of return data
    assign virtio_blk_desc_engine_free_status_rdata = virtio_blk_desc_engine_free_status_sw_rd ? virtio_blk_desc_engine_free_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: virtio_blk_desc_engine_free_status (wire)
    // ------------------------------------------------------------
    assign virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_anded = & virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_q;
    assign virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_ored  = | virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_q;
    assign virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_xored = ^ virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_q;

    // next hardware value
    assign virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_next = virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_wdata;
    assign virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_q = virtio_blk_desc_engine_free_status_virtio_blk_desc_engine_free_status_next;
            
        
    // ============================================================
    // Register: VIRTIO_BLK_DESC_ENGINE_CORE_STATUS
    //    [63: 0] virtio_blk_desc_engine_core_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  virtio_blk_desc_engine_core_status_decode;
    logic                  virtio_blk_desc_engine_core_status_sw_wr;
    logic                  virtio_blk_desc_engine_core_status_sw_rd;
    logic [DATA_WIDTH-1:0] virtio_blk_desc_engine_core_status_q;

    assign virtio_blk_desc_engine_core_status_decode = (addr == (ADDR_OFFSET+'h0+'h130));
    assign virtio_blk_desc_engine_core_status_sw_wr = sw_wr && virtio_blk_desc_engine_core_status_decode;
    assign virtio_blk_desc_engine_core_status_sw_rd = sw_rd && virtio_blk_desc_engine_core_status_decode;

    always_comb begin
        virtio_blk_desc_engine_core_status_q = '0;
        virtio_blk_desc_engine_core_status_q[63: 0] = virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_q;
    end

    // masked version of return data
    assign virtio_blk_desc_engine_core_status_rdata = virtio_blk_desc_engine_core_status_sw_rd ? virtio_blk_desc_engine_core_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: virtio_blk_desc_engine_core_status (wire)
    // ------------------------------------------------------------
    assign virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_anded = & virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_q;
    assign virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_ored  = | virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_q;
    assign virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_xored = ^ virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_q;

    // next hardware value
    assign virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_next = virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_wdata;
    assign virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_q = virtio_blk_desc_engine_core_status_virtio_blk_desc_engine_core_status_next;

endmodule: virtio_blk_desc_engine_dfx
