// This file was autogenerated by PeakRDL-verilog
module beq_loop_test_dfx #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register EN_R
    output logic                     [ 9: 0] en_r_en_r_q,              //! Current field value

    // Register SEED_R0
    output logic                             seed_r0_seed_r0_swmod,          //! Indicates SW has modified this field
    output logic                     [31: 0] seed_r0_seed_r0_q,              //! Current field value

    // Register SEED_R1
    output logic                             seed_r1_seed_r1_swmod,          //! Indicates SW has modified this field
    output logic                     [31: 0] seed_r1_seed_r1_q,              //! Current field value

    // Register SEED_R2
    output logic                             seed_r2_seed_r2_swmod,          //! Indicates SW has modified this field
    output logic                     [31: 0] seed_r2_seed_r2_q,              //! Current field value

    // Register SEED_R3
    output logic                             seed_r3_seed_r3_swmod,          //! Indicates SW has modified this field
    output logic                     [31: 0] seed_r3_seed_r3_q,              //! Current field value

    // Register SEED_R4
    output logic                             seed_r4_seed_r4_swmod,          //! Indicates SW has modified this field
    output logic                     [31: 0] seed_r4_seed_r4_q,              //! Current field value

    // Register SEED_R5
    output logic                             seed_r5_seed_r5_swmod,          //! Indicates SW has modified this field
    output logic                     [31: 0] seed_r5_seed_r5_q,              //! Current field value

    // Register SEED_R6
    output logic                             seed_r6_seed_r6_swmod,          //! Indicates SW has modified this field
    output logic                     [31: 0] seed_r6_seed_r6_q,              //! Current field value

    // Register SEED_R7
    output logic                             seed_r7_seed_r7_swmod,          //! Indicates SW has modified this field
    output logic                     [31: 0] seed_r7_seed_r7_q,              //! Current field value

    // Register TCNTL_R
    input  logic                     [63: 0] tcntl_r_tcntl_r_wdata,          //! HW write data

    // Register TCNTH_R
    input  logic                     [63: 0] tcnth_r_tcnth_r_wdata,          //! HW write data

    // Register RCNTL_R
    input  logic                     [63: 0] rcntl_r_rcntl_r_wdata,          //! HW write data

    // Register RCNTH_R
    input  logic                     [63: 0] rcnth_r_rcnth_r_wdata,          //! HW write data

    // Register CLCCNT_R
    output logic                             clccnt_r_clccnt_r_swmod,          //! Indicates SW has modified this field
    output logic                     [ 0: 0] clccnt_r_clccnt_r_q,              //! Current field value

    // Register ERROR_R
    input  logic                             error_r_error_r_we,             //! Control HW write (active high)
    input  logic                     [ 0: 0] error_r_error_r_wdata,          //! HW write data

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [ 9: 0] en_r_en_r_next;
    logic                             en_r_en_r_anded;
    logic                             en_r_en_r_ored;
    logic                             en_r_en_r_xored;
    logic                           [31: 0] seed_r0_seed_r0_next;
    logic                             seed_r0_seed_r0_anded;
    logic                             seed_r0_seed_r0_ored;
    logic                             seed_r0_seed_r0_xored;
    logic                           [31: 0] seed_r1_seed_r1_next;
    logic                             seed_r1_seed_r1_anded;
    logic                             seed_r1_seed_r1_ored;
    logic                             seed_r1_seed_r1_xored;
    logic                           [31: 0] seed_r2_seed_r2_next;
    logic                             seed_r2_seed_r2_anded;
    logic                             seed_r2_seed_r2_ored;
    logic                             seed_r2_seed_r2_xored;
    logic                           [31: 0] seed_r3_seed_r3_next;
    logic                             seed_r3_seed_r3_anded;
    logic                             seed_r3_seed_r3_ored;
    logic                             seed_r3_seed_r3_xored;
    logic                           [31: 0] seed_r4_seed_r4_next;
    logic                             seed_r4_seed_r4_anded;
    logic                             seed_r4_seed_r4_ored;
    logic                             seed_r4_seed_r4_xored;
    logic                           [31: 0] seed_r5_seed_r5_next;
    logic                             seed_r5_seed_r5_anded;
    logic                             seed_r5_seed_r5_ored;
    logic                             seed_r5_seed_r5_xored;
    logic                           [31: 0] seed_r6_seed_r6_next;
    logic                             seed_r6_seed_r6_anded;
    logic                             seed_r6_seed_r6_ored;
    logic                             seed_r6_seed_r6_xored;
    logic                           [31: 0] seed_r7_seed_r7_next;
    logic                             seed_r7_seed_r7_anded;
    logic                             seed_r7_seed_r7_ored;
    logic                             seed_r7_seed_r7_xored;
    logic                           [63: 0] tcntl_r_tcntl_r_q;
    logic                           [63: 0] tcntl_r_tcntl_r_next;
    logic                             tcntl_r_tcntl_r_anded;
    logic                             tcntl_r_tcntl_r_ored;
    logic                             tcntl_r_tcntl_r_xored;
    logic                           [63: 0] tcnth_r_tcnth_r_q;
    logic                           [63: 0] tcnth_r_tcnth_r_next;
    logic                             tcnth_r_tcnth_r_anded;
    logic                             tcnth_r_tcnth_r_ored;
    logic                             tcnth_r_tcnth_r_xored;
    logic                           [63: 0] rcntl_r_rcntl_r_q;
    logic                           [63: 0] rcntl_r_rcntl_r_next;
    logic                             rcntl_r_rcntl_r_anded;
    logic                             rcntl_r_rcntl_r_ored;
    logic                             rcntl_r_rcntl_r_xored;
    logic                           [63: 0] rcnth_r_rcnth_r_q;
    logic                           [63: 0] rcnth_r_rcnth_r_next;
    logic                             rcnth_r_rcnth_r_anded;
    logic                             rcnth_r_rcnth_r_ored;
    logic                             rcnth_r_rcnth_r_xored;
    logic                           [ 0: 0] clccnt_r_clccnt_r_next;
    logic                             clccnt_r_clccnt_r_anded;
    logic                             clccnt_r_clccnt_r_ored;
    logic                             clccnt_r_clccnt_r_xored;
    logic                           [ 0: 0] error_r_error_r_q;
    logic                           [ 0: 0] error_r_error_r_next;
    logic                             error_r_error_r_anded;
    logic                             error_r_error_r_ored;
    logic                             error_r_error_r_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [DATA_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] en_r_rdata;
    logic                     [DATA_WIDTH-1:0] seed_r0_rdata;
    logic                     [DATA_WIDTH-1:0] seed_r1_rdata;
    logic                     [DATA_WIDTH-1:0] seed_r2_rdata;
    logic                     [DATA_WIDTH-1:0] seed_r3_rdata;
    logic                     [DATA_WIDTH-1:0] seed_r4_rdata;
    logic                     [DATA_WIDTH-1:0] seed_r5_rdata;
    logic                     [DATA_WIDTH-1:0] seed_r6_rdata;
    logic                     [DATA_WIDTH-1:0] seed_r7_rdata;
    logic                     [DATA_WIDTH-1:0] tcntl_r_rdata;
    logic                     [DATA_WIDTH-1:0] tcnth_r_rdata;
    logic                     [DATA_WIDTH-1:0] rcntl_r_rdata;
    logic                     [DATA_WIDTH-1:0] rcnth_r_rdata;
    logic                     [DATA_WIDTH-1:0] clccnt_r_rdata;
    logic                     [DATA_WIDTH-1:0] error_r_rdata;

    assign sw_rdata = // or of each register return (masked)
                   en_r_rdata | 
                   seed_r0_rdata | 
                   seed_r1_rdata | 
                   seed_r2_rdata | 
                   seed_r3_rdata | 
                   seed_r4_rdata | 
                   seed_r5_rdata | 
                   seed_r6_rdata | 
                   seed_r7_rdata | 
                   tcntl_r_rdata | 
                   tcnth_r_rdata | 
                   rcntl_r_rdata | 
                   rcnth_r_rdata | 
                   clccnt_r_rdata | 
                   error_r_rdata;
            
        
    // ============================================================
    // Register: EN_R
    //    [ 9: 0]                 en_r: hw=r     sw=rw    reset=0x0
    // ============================================================
    logic                  en_r_decode;
    logic                  en_r_sw_wr;
    logic                  en_r_sw_rd;
    logic [DATA_WIDTH-1:0] en_r_q;

    assign en_r_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign en_r_sw_wr = sw_wr && en_r_decode;
    assign en_r_sw_rd = sw_rd && en_r_decode;

    always_comb begin
        en_r_q = '0;
        en_r_q[ 9: 0] = en_r_en_r_q;
    end

    // masked version of return data
    assign en_r_rdata = en_r_sw_rd ? en_r_q : 'b0;

    // ------------------------------------------------------------
    // Field: en_r
    // ------------------------------------------------------------
    assign en_r_en_r_anded = & en_r_en_r_q;
    assign en_r_en_r_ored  = | en_r_en_r_q;
    assign en_r_en_r_xored = ^ en_r_en_r_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        en_r_en_r_q <= 0;
    end else begin
        // Software write
        if (en_r_sw_wr) begin
            en_r_en_r_q <=  sw_masked_data[ 9: 0] | (en_r_en_r_q & ~sw_mask[ 9: 0]);
        end
    end
            
        
    // ============================================================
    // Register: SEED_R0
    //    [31: 0]              seed_r0: hw=r     sw=rw    reset=0xc876fabd
    // ============================================================
    logic                  seed_r0_decode;
    logic                  seed_r0_sw_wr;
    logic                  seed_r0_sw_rd;
    logic [DATA_WIDTH-1:0] seed_r0_q;

    assign seed_r0_decode = (addr == (ADDR_OFFSET+'h0+'h8));
    assign seed_r0_sw_wr = sw_wr && seed_r0_decode;
    assign seed_r0_sw_rd = sw_rd && seed_r0_decode;

    always_comb begin
        seed_r0_q = '0;
        seed_r0_q[31: 0] = seed_r0_seed_r0_q;
    end

    // masked version of return data
    assign seed_r0_rdata = seed_r0_sw_rd ? seed_r0_q : 'b0;

    // ------------------------------------------------------------
    // Field: seed_r0
    // ------------------------------------------------------------
    assign seed_r0_seed_r0_anded = & seed_r0_seed_r0_q;
    assign seed_r0_seed_r0_ored  = | seed_r0_seed_r0_q;
    assign seed_r0_seed_r0_xored = ^ seed_r0_seed_r0_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        seed_r0_seed_r0_q <= 3363240637;
        seed_r0_seed_r0_swmod <= 1'b0;
    end else begin
        seed_r0_seed_r0_swmod <= 1'b0;
        // Software write
        if (seed_r0_sw_wr) begin
            seed_r0_seed_r0_swmod <= 1'b1;
            seed_r0_seed_r0_q <=  sw_masked_data[31: 0] | (seed_r0_seed_r0_q & ~sw_mask[31: 0]);
        end
    end
            
        
    // ============================================================
    // Register: SEED_R1
    //    [31: 0]              seed_r1: hw=r     sw=rw    reset=0xe43b7d5e
    // ============================================================
    logic                  seed_r1_decode;
    logic                  seed_r1_sw_wr;
    logic                  seed_r1_sw_rd;
    logic [DATA_WIDTH-1:0] seed_r1_q;

    assign seed_r1_decode = (addr == (ADDR_OFFSET+'h0+'h10));
    assign seed_r1_sw_wr = sw_wr && seed_r1_decode;
    assign seed_r1_sw_rd = sw_rd && seed_r1_decode;

    always_comb begin
        seed_r1_q = '0;
        seed_r1_q[31: 0] = seed_r1_seed_r1_q;
    end

    // masked version of return data
    assign seed_r1_rdata = seed_r1_sw_rd ? seed_r1_q : 'b0;

    // ------------------------------------------------------------
    // Field: seed_r1
    // ------------------------------------------------------------
    assign seed_r1_seed_r1_anded = & seed_r1_seed_r1_q;
    assign seed_r1_seed_r1_ored  = | seed_r1_seed_r1_q;
    assign seed_r1_seed_r1_xored = ^ seed_r1_seed_r1_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        seed_r1_seed_r1_q <= 3829103966;
        seed_r1_seed_r1_swmod <= 1'b0;
    end else begin
        seed_r1_seed_r1_swmod <= 1'b0;
        // Software write
        if (seed_r1_sw_wr) begin
            seed_r1_seed_r1_swmod <= 1'b1;
            seed_r1_seed_r1_q <=  sw_masked_data[31: 0] | (seed_r1_seed_r1_q & ~sw_mask[31: 0]);
        end
    end
            
        
    // ============================================================
    // Register: SEED_R2
    //    [31: 0]              seed_r2: hw=r     sw=rw    reset=0x721dbeaf
    // ============================================================
    logic                  seed_r2_decode;
    logic                  seed_r2_sw_wr;
    logic                  seed_r2_sw_rd;
    logic [DATA_WIDTH-1:0] seed_r2_q;

    assign seed_r2_decode = (addr == (ADDR_OFFSET+'h0+'h18));
    assign seed_r2_sw_wr = sw_wr && seed_r2_decode;
    assign seed_r2_sw_rd = sw_rd && seed_r2_decode;

    always_comb begin
        seed_r2_q = '0;
        seed_r2_q[31: 0] = seed_r2_seed_r2_q;
    end

    // masked version of return data
    assign seed_r2_rdata = seed_r2_sw_rd ? seed_r2_q : 'b0;

    // ------------------------------------------------------------
    // Field: seed_r2
    // ------------------------------------------------------------
    assign seed_r2_seed_r2_anded = & seed_r2_seed_r2_q;
    assign seed_r2_seed_r2_ored  = | seed_r2_seed_r2_q;
    assign seed_r2_seed_r2_xored = ^ seed_r2_seed_r2_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        seed_r2_seed_r2_q <= 1914551983;
        seed_r2_seed_r2_swmod <= 1'b0;
    end else begin
        seed_r2_seed_r2_swmod <= 1'b0;
        // Software write
        if (seed_r2_sw_wr) begin
            seed_r2_seed_r2_swmod <= 1'b1;
            seed_r2_seed_r2_q <=  sw_masked_data[31: 0] | (seed_r2_seed_r2_q & ~sw_mask[31: 0]);
        end
    end
            
        
    // ============================================================
    // Register: SEED_R3
    //    [31: 0]              seed_r3: hw=r     sw=rw    reset=0xb90edf57
    // ============================================================
    logic                  seed_r3_decode;
    logic                  seed_r3_sw_wr;
    logic                  seed_r3_sw_rd;
    logic [DATA_WIDTH-1:0] seed_r3_q;

    assign seed_r3_decode = (addr == (ADDR_OFFSET+'h0+'h20));
    assign seed_r3_sw_wr = sw_wr && seed_r3_decode;
    assign seed_r3_sw_rd = sw_rd && seed_r3_decode;

    always_comb begin
        seed_r3_q = '0;
        seed_r3_q[31: 0] = seed_r3_seed_r3_q;
    end

    // masked version of return data
    assign seed_r3_rdata = seed_r3_sw_rd ? seed_r3_q : 'b0;

    // ------------------------------------------------------------
    // Field: seed_r3
    // ------------------------------------------------------------
    assign seed_r3_seed_r3_anded = & seed_r3_seed_r3_q;
    assign seed_r3_seed_r3_ored  = | seed_r3_seed_r3_q;
    assign seed_r3_seed_r3_xored = ^ seed_r3_seed_r3_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        seed_r3_seed_r3_q <= 3104759639;
        seed_r3_seed_r3_swmod <= 1'b0;
    end else begin
        seed_r3_seed_r3_swmod <= 1'b0;
        // Software write
        if (seed_r3_sw_wr) begin
            seed_r3_seed_r3_swmod <= 1'b1;
            seed_r3_seed_r3_q <=  sw_masked_data[31: 0] | (seed_r3_seed_r3_q & ~sw_mask[31: 0]);
        end
    end
            
        
    // ============================================================
    // Register: SEED_R4
    //    [31: 0]              seed_r4: hw=r     sw=rw    reset=0xdc876fab
    // ============================================================
    logic                  seed_r4_decode;
    logic                  seed_r4_sw_wr;
    logic                  seed_r4_sw_rd;
    logic [DATA_WIDTH-1:0] seed_r4_q;

    assign seed_r4_decode = (addr == (ADDR_OFFSET+'h0+'h28));
    assign seed_r4_sw_wr = sw_wr && seed_r4_decode;
    assign seed_r4_sw_rd = sw_rd && seed_r4_decode;

    always_comb begin
        seed_r4_q = '0;
        seed_r4_q[31: 0] = seed_r4_seed_r4_q;
    end

    // masked version of return data
    assign seed_r4_rdata = seed_r4_sw_rd ? seed_r4_q : 'b0;

    // ------------------------------------------------------------
    // Field: seed_r4
    // ------------------------------------------------------------
    assign seed_r4_seed_r4_anded = & seed_r4_seed_r4_q;
    assign seed_r4_seed_r4_ored  = | seed_r4_seed_r4_q;
    assign seed_r4_seed_r4_xored = ^ seed_r4_seed_r4_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        seed_r4_seed_r4_q <= 3699863467;
        seed_r4_seed_r4_swmod <= 1'b0;
    end else begin
        seed_r4_seed_r4_swmod <= 1'b0;
        // Software write
        if (seed_r4_sw_wr) begin
            seed_r4_seed_r4_swmod <= 1'b1;
            seed_r4_seed_r4_q <=  sw_masked_data[31: 0] | (seed_r4_seed_r4_q & ~sw_mask[31: 0]);
        end
    end
            
        
    // ============================================================
    // Register: SEED_R5
    //    [31: 0]              seed_r5: hw=r     sw=rw    reset=0xee43b7d5
    // ============================================================
    logic                  seed_r5_decode;
    logic                  seed_r5_sw_wr;
    logic                  seed_r5_sw_rd;
    logic [DATA_WIDTH-1:0] seed_r5_q;

    assign seed_r5_decode = (addr == (ADDR_OFFSET+'h0+'h30));
    assign seed_r5_sw_wr = sw_wr && seed_r5_decode;
    assign seed_r5_sw_rd = sw_rd && seed_r5_decode;

    always_comb begin
        seed_r5_q = '0;
        seed_r5_q[31: 0] = seed_r5_seed_r5_q;
    end

    // masked version of return data
    assign seed_r5_rdata = seed_r5_sw_rd ? seed_r5_q : 'b0;

    // ------------------------------------------------------------
    // Field: seed_r5
    // ------------------------------------------------------------
    assign seed_r5_seed_r5_anded = & seed_r5_seed_r5_q;
    assign seed_r5_seed_r5_ored  = | seed_r5_seed_r5_q;
    assign seed_r5_seed_r5_xored = ^ seed_r5_seed_r5_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        seed_r5_seed_r5_q <= 3997415381;
        seed_r5_seed_r5_swmod <= 1'b0;
    end else begin
        seed_r5_seed_r5_swmod <= 1'b0;
        // Software write
        if (seed_r5_sw_wr) begin
            seed_r5_seed_r5_swmod <= 1'b1;
            seed_r5_seed_r5_q <=  sw_masked_data[31: 0] | (seed_r5_seed_r5_q & ~sw_mask[31: 0]);
        end
    end
            
        
    // ============================================================
    // Register: SEED_R6
    //    [31: 0]              seed_r6: hw=r     sw=rw    reset=0xf721dbea
    // ============================================================
    logic                  seed_r6_decode;
    logic                  seed_r6_sw_wr;
    logic                  seed_r6_sw_rd;
    logic [DATA_WIDTH-1:0] seed_r6_q;

    assign seed_r6_decode = (addr == (ADDR_OFFSET+'h0+'h38));
    assign seed_r6_sw_wr = sw_wr && seed_r6_decode;
    assign seed_r6_sw_rd = sw_rd && seed_r6_decode;

    always_comb begin
        seed_r6_q = '0;
        seed_r6_q[31: 0] = seed_r6_seed_r6_q;
    end

    // masked version of return data
    assign seed_r6_rdata = seed_r6_sw_rd ? seed_r6_q : 'b0;

    // ------------------------------------------------------------
    // Field: seed_r6
    // ------------------------------------------------------------
    assign seed_r6_seed_r6_anded = & seed_r6_seed_r6_q;
    assign seed_r6_seed_r6_ored  = | seed_r6_seed_r6_q;
    assign seed_r6_seed_r6_xored = ^ seed_r6_seed_r6_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        seed_r6_seed_r6_q <= 4146191338;
        seed_r6_seed_r6_swmod <= 1'b0;
    end else begin
        seed_r6_seed_r6_swmod <= 1'b0;
        // Software write
        if (seed_r6_sw_wr) begin
            seed_r6_seed_r6_swmod <= 1'b1;
            seed_r6_seed_r6_q <=  sw_masked_data[31: 0] | (seed_r6_seed_r6_q & ~sw_mask[31: 0]);
        end
    end
            
        
    // ============================================================
    // Register: SEED_R7
    //    [31: 0]              seed_r7: hw=r     sw=rw    reset=0x7b90edf5
    // ============================================================
    logic                  seed_r7_decode;
    logic                  seed_r7_sw_wr;
    logic                  seed_r7_sw_rd;
    logic [DATA_WIDTH-1:0] seed_r7_q;

    assign seed_r7_decode = (addr == (ADDR_OFFSET+'h0+'h40));
    assign seed_r7_sw_wr = sw_wr && seed_r7_decode;
    assign seed_r7_sw_rd = sw_rd && seed_r7_decode;

    always_comb begin
        seed_r7_q = '0;
        seed_r7_q[31: 0] = seed_r7_seed_r7_q;
    end

    // masked version of return data
    assign seed_r7_rdata = seed_r7_sw_rd ? seed_r7_q : 'b0;

    // ------------------------------------------------------------
    // Field: seed_r7
    // ------------------------------------------------------------
    assign seed_r7_seed_r7_anded = & seed_r7_seed_r7_q;
    assign seed_r7_seed_r7_ored  = | seed_r7_seed_r7_q;
    assign seed_r7_seed_r7_xored = ^ seed_r7_seed_r7_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        seed_r7_seed_r7_q <= 2073095669;
        seed_r7_seed_r7_swmod <= 1'b0;
    end else begin
        seed_r7_seed_r7_swmod <= 1'b0;
        // Software write
        if (seed_r7_sw_wr) begin
            seed_r7_seed_r7_swmod <= 1'b1;
            seed_r7_seed_r7_q <=  sw_masked_data[31: 0] | (seed_r7_seed_r7_q & ~sw_mask[31: 0]);
        end
    end
            
        
    // ============================================================
    // Register: TCNTL_R
    //    [63: 0]              tcntl_r: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  tcntl_r_decode;
    logic                  tcntl_r_sw_wr;
    logic                  tcntl_r_sw_rd;
    logic [DATA_WIDTH-1:0] tcntl_r_q;

    assign tcntl_r_decode = (addr == (ADDR_OFFSET+'h0+'h48));
    assign tcntl_r_sw_wr = sw_wr && tcntl_r_decode;
    assign tcntl_r_sw_rd = sw_rd && tcntl_r_decode;

    always_comb begin
        tcntl_r_q = '0;
        tcntl_r_q[63: 0] = tcntl_r_tcntl_r_q;
    end

    // masked version of return data
    assign tcntl_r_rdata = tcntl_r_sw_rd ? tcntl_r_q : 'b0;

    // ------------------------------------------------------------
    // Field: tcntl_r (wire)
    // ------------------------------------------------------------
    assign tcntl_r_tcntl_r_anded = & tcntl_r_tcntl_r_q;
    assign tcntl_r_tcntl_r_ored  = | tcntl_r_tcntl_r_q;
    assign tcntl_r_tcntl_r_xored = ^ tcntl_r_tcntl_r_q;

    // next hardware value
    assign tcntl_r_tcntl_r_next = tcntl_r_tcntl_r_wdata;
    assign tcntl_r_tcntl_r_q = tcntl_r_tcntl_r_next;
            
        
    // ============================================================
    // Register: TCNTH_R
    //    [63: 0]              tcnth_r: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  tcnth_r_decode;
    logic                  tcnth_r_sw_wr;
    logic                  tcnth_r_sw_rd;
    logic [DATA_WIDTH-1:0] tcnth_r_q;

    assign tcnth_r_decode = (addr == (ADDR_OFFSET+'h0+'h50));
    assign tcnth_r_sw_wr = sw_wr && tcnth_r_decode;
    assign tcnth_r_sw_rd = sw_rd && tcnth_r_decode;

    always_comb begin
        tcnth_r_q = '0;
        tcnth_r_q[63: 0] = tcnth_r_tcnth_r_q;
    end

    // masked version of return data
    assign tcnth_r_rdata = tcnth_r_sw_rd ? tcnth_r_q : 'b0;

    // ------------------------------------------------------------
    // Field: tcnth_r (wire)
    // ------------------------------------------------------------
    assign tcnth_r_tcnth_r_anded = & tcnth_r_tcnth_r_q;
    assign tcnth_r_tcnth_r_ored  = | tcnth_r_tcnth_r_q;
    assign tcnth_r_tcnth_r_xored = ^ tcnth_r_tcnth_r_q;

    // next hardware value
    assign tcnth_r_tcnth_r_next = tcnth_r_tcnth_r_wdata;
    assign tcnth_r_tcnth_r_q = tcnth_r_tcnth_r_next;
            
        
    // ============================================================
    // Register: RCNTL_R
    //    [63: 0]              rcntl_r: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  rcntl_r_decode;
    logic                  rcntl_r_sw_wr;
    logic                  rcntl_r_sw_rd;
    logic [DATA_WIDTH-1:0] rcntl_r_q;

    assign rcntl_r_decode = (addr == (ADDR_OFFSET+'h0+'h58));
    assign rcntl_r_sw_wr = sw_wr && rcntl_r_decode;
    assign rcntl_r_sw_rd = sw_rd && rcntl_r_decode;

    always_comb begin
        rcntl_r_q = '0;
        rcntl_r_q[63: 0] = rcntl_r_rcntl_r_q;
    end

    // masked version of return data
    assign rcntl_r_rdata = rcntl_r_sw_rd ? rcntl_r_q : 'b0;

    // ------------------------------------------------------------
    // Field: rcntl_r (wire)
    // ------------------------------------------------------------
    assign rcntl_r_rcntl_r_anded = & rcntl_r_rcntl_r_q;
    assign rcntl_r_rcntl_r_ored  = | rcntl_r_rcntl_r_q;
    assign rcntl_r_rcntl_r_xored = ^ rcntl_r_rcntl_r_q;

    // next hardware value
    assign rcntl_r_rcntl_r_next = rcntl_r_rcntl_r_wdata;
    assign rcntl_r_rcntl_r_q = rcntl_r_rcntl_r_next;
            
        
    // ============================================================
    // Register: RCNTH_R
    //    [63: 0]              rcnth_r: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  rcnth_r_decode;
    logic                  rcnth_r_sw_wr;
    logic                  rcnth_r_sw_rd;
    logic [DATA_WIDTH-1:0] rcnth_r_q;

    assign rcnth_r_decode = (addr == (ADDR_OFFSET+'h0+'h60));
    assign rcnth_r_sw_wr = sw_wr && rcnth_r_decode;
    assign rcnth_r_sw_rd = sw_rd && rcnth_r_decode;

    always_comb begin
        rcnth_r_q = '0;
        rcnth_r_q[63: 0] = rcnth_r_rcnth_r_q;
    end

    // masked version of return data
    assign rcnth_r_rdata = rcnth_r_sw_rd ? rcnth_r_q : 'b0;

    // ------------------------------------------------------------
    // Field: rcnth_r (wire)
    // ------------------------------------------------------------
    assign rcnth_r_rcnth_r_anded = & rcnth_r_rcnth_r_q;
    assign rcnth_r_rcnth_r_ored  = | rcnth_r_rcnth_r_q;
    assign rcnth_r_rcnth_r_xored = ^ rcnth_r_rcnth_r_q;

    // next hardware value
    assign rcnth_r_rcnth_r_next = rcnth_r_rcnth_r_wdata;
    assign rcnth_r_rcnth_r_q = rcnth_r_rcnth_r_next;
            
        
    // ============================================================
    // Register: CLCCNT_R
    //    [ 0: 0]             clccnt_r: hw=r     sw=rw    reset=0x0
    // ============================================================
    logic                  clccnt_r_decode;
    logic                  clccnt_r_sw_wr;
    logic                  clccnt_r_sw_rd;
    logic [DATA_WIDTH-1:0] clccnt_r_q;

    assign clccnt_r_decode = (addr == (ADDR_OFFSET+'h0+'h68));
    assign clccnt_r_sw_wr = sw_wr && clccnt_r_decode;
    assign clccnt_r_sw_rd = sw_rd && clccnt_r_decode;

    always_comb begin
        clccnt_r_q = '0;
        clccnt_r_q[ 0: 0] = clccnt_r_clccnt_r_q;
    end

    // masked version of return data
    assign clccnt_r_rdata = clccnt_r_sw_rd ? clccnt_r_q : 'b0;

    // ------------------------------------------------------------
    // Field: clccnt_r
    // ------------------------------------------------------------
    assign clccnt_r_clccnt_r_anded = & clccnt_r_clccnt_r_q;
    assign clccnt_r_clccnt_r_ored  = | clccnt_r_clccnt_r_q;
    assign clccnt_r_clccnt_r_xored = ^ clccnt_r_clccnt_r_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        clccnt_r_clccnt_r_q <= 0;
        clccnt_r_clccnt_r_swmod <= 1'b0;
    end else begin
        clccnt_r_clccnt_r_swmod <= 1'b0;
        // Software write
        if (clccnt_r_sw_wr) begin
            clccnt_r_clccnt_r_swmod <= 1'b1;
            clccnt_r_clccnt_r_q <=  sw_masked_data[ 0: 0] | (clccnt_r_clccnt_r_q & ~sw_mask[ 0: 0]);
        end
    end
            
        
    // ============================================================
    // Register: ERROR_R
    //    [ 0: 0]              error_r: hw=w     sw=rw    reset=0x0
    // ============================================================
    logic                  error_r_decode;
    logic                  error_r_sw_wr;
    logic                  error_r_sw_rd;
    logic [DATA_WIDTH-1:0] error_r_q;

    assign error_r_decode = (addr == (ADDR_OFFSET+'h0+'h70));
    assign error_r_sw_wr = sw_wr && error_r_decode;
    assign error_r_sw_rd = sw_rd && error_r_decode;

    always_comb begin
        error_r_q = '0;
        error_r_q[ 0: 0] = error_r_error_r_q;
    end

    // masked version of return data
    assign error_r_rdata = error_r_sw_rd ? error_r_q : 'b0;

    // ------------------------------------------------------------
    // Field: error_r
    // ------------------------------------------------------------
    assign error_r_error_r_anded = & error_r_error_r_q;
    assign error_r_error_r_ored  = | error_r_error_r_q;
    assign error_r_error_r_xored = ^ error_r_error_r_q;

    // next hardware value
    assign error_r_error_r_next = error_r_error_r_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        error_r_error_r_q <= 0;
    end else begin
        // Hardware Write
        if (error_r_error_r_we) begin
            error_r_error_r_q <= error_r_error_r_next;
        end
        // Software write
        if (error_r_sw_wr) begin
            error_r_error_r_q <= ~sw_masked_data[ 0: 0] &  error_r_error_r_q;
        end
    end

endmodule: beq_loop_test_dfx
