// This file was autogenerated by PeakRDL-verilog
module virtio_blk_downstream_dfx #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register BLK_DOWNSTREAM_ERR
    input  logic                             blk_downstream_err_blk_downstream_err_we,             //! Control HW write (active high)
    input  logic                     [63: 0] blk_downstream_err_blk_downstream_err_wdata,          //! HW write data
    output logic                     [63: 0] blk_downstream_err_blk_downstream_err_q,              //! Current field value

    // Register BLK_DOWNSTREAM_FF_STAT
    input  logic                     [63: 0] blk_downstream_ff_stat_blk_downstream_ff_stat_wdata,          //! HW write data

    // Register BLK_DOWNSTREAM_FSM_STAT
    input  logic                     [63: 0] blk_downstream_fsm_stat_blk_downstream_fsm_stat_wdata,          //! HW write data

    // Register BLK_DOWNSTREAM_ERR_CNT
    input  logic                             blk_downstream_err_cnt_blk_downstream_err_cnt_we,             //! Control HW write (active high)
    input  logic                     [63: 0] blk_downstream_err_cnt_blk_downstream_err_cnt_wdata,          //! HW write data
    output logic                     [63: 0] blk_downstream_err_cnt_blk_downstream_err_cnt_q,              //! Current field value

    // Register BLK_DOWNSTREAM_IF_CNT
    input  logic                             blk_downstream_if_cnt_blk_downstream_if_cnt_we,             //! Control HW write (active high)
    input  logic                     [63: 0] blk_downstream_if_cnt_blk_downstream_if_cnt_wdata,          //! HW write data
    output logic                     [63: 0] blk_downstream_if_cnt_blk_downstream_if_cnt_q,              //! Current field value

    // Register BLK_DESC_HS_RELATED_CNT
    input  logic                     [63: 0] blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_wdata,          //! HW write data

    // Register DMA_RD_REQ_BP_RELATED_CNT
    input  logic                     [63: 0] dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_wdata,          //! HW write data

    // Register DMA_RD_RSP_BP_VDATA_CNT
    input  logic                     [63: 0] dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_wdata,          //! HW write data

    // Register BLK_DOWNSTREAM_DMA_INFLIGHT_THRESHOLD
    output logic                     [ 9: 0] blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_q,              //! Current field value

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [63: 0] blk_downstream_err_blk_downstream_err_next;
    logic                             blk_downstream_err_blk_downstream_err_anded;
    logic                             blk_downstream_err_blk_downstream_err_ored;
    logic                             blk_downstream_err_blk_downstream_err_xored;
    logic                           [63: 0] blk_downstream_ff_stat_blk_downstream_ff_stat_q;
    logic                           [63: 0] blk_downstream_ff_stat_blk_downstream_ff_stat_next;
    logic                             blk_downstream_ff_stat_blk_downstream_ff_stat_anded;
    logic                             blk_downstream_ff_stat_blk_downstream_ff_stat_ored;
    logic                             blk_downstream_ff_stat_blk_downstream_ff_stat_xored;
    logic                           [63: 0] blk_downstream_fsm_stat_blk_downstream_fsm_stat_q;
    logic                           [63: 0] blk_downstream_fsm_stat_blk_downstream_fsm_stat_next;
    logic                             blk_downstream_fsm_stat_blk_downstream_fsm_stat_anded;
    logic                             blk_downstream_fsm_stat_blk_downstream_fsm_stat_ored;
    logic                             blk_downstream_fsm_stat_blk_downstream_fsm_stat_xored;
    logic                           [63: 0] blk_downstream_err_cnt_blk_downstream_err_cnt_next;
    logic                             blk_downstream_err_cnt_blk_downstream_err_cnt_anded;
    logic                             blk_downstream_err_cnt_blk_downstream_err_cnt_ored;
    logic                             blk_downstream_err_cnt_blk_downstream_err_cnt_xored;
    logic                           [63: 0] blk_downstream_if_cnt_blk_downstream_if_cnt_next;
    logic                             blk_downstream_if_cnt_blk_downstream_if_cnt_anded;
    logic                             blk_downstream_if_cnt_blk_downstream_if_cnt_ored;
    logic                             blk_downstream_if_cnt_blk_downstream_if_cnt_xored;
    logic                           [63: 0] blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_q;
    logic                           [63: 0] blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_next;
    logic                             blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_anded;
    logic                             blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_ored;
    logic                             blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_xored;
    logic                           [63: 0] dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_q;
    logic                           [63: 0] dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_next;
    logic                             dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_anded;
    logic                             dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_ored;
    logic                             dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_xored;
    logic                           [63: 0] dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_q;
    logic                           [63: 0] dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_next;
    logic                             dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_anded;
    logic                             dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_ored;
    logic                             dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_xored;
    logic                           [ 9: 0] blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_next;
    logic                             blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_anded;
    logic                             blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_ored;
    logic                             blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [ADDR_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] blk_downstream_err_rdata;
    logic                     [DATA_WIDTH-1:0] blk_downstream_ff_stat_rdata;
    logic                     [DATA_WIDTH-1:0] blk_downstream_fsm_stat_rdata;
    logic                     [DATA_WIDTH-1:0] blk_downstream_err_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] blk_downstream_if_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] blk_desc_hs_related_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dma_rd_req_bp_related_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dma_rd_rsp_bp_vdata_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] blk_downstream_dma_inflight_threshold_rdata;

    assign sw_rdata = // or of each register return (masked)
                   blk_downstream_err_rdata | 
                   blk_downstream_ff_stat_rdata | 
                   blk_downstream_fsm_stat_rdata | 
                   blk_downstream_err_cnt_rdata | 
                   blk_downstream_if_cnt_rdata | 
                   blk_desc_hs_related_cnt_rdata | 
                   dma_rd_req_bp_related_cnt_rdata | 
                   dma_rd_rsp_bp_vdata_cnt_rdata | 
                   blk_downstream_dma_inflight_threshold_rdata;
            
        
    // ============================================================
    // Register: BLK_DOWNSTREAM_ERR
    //    [63: 0]   blk_downstream_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  blk_downstream_err_decode;
    logic                  blk_downstream_err_sw_wr;
    logic                  blk_downstream_err_sw_rd;
    logic [DATA_WIDTH-1:0] blk_downstream_err_q;

    assign blk_downstream_err_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign blk_downstream_err_sw_wr = sw_wr && blk_downstream_err_decode;
    assign blk_downstream_err_sw_rd = sw_rd && blk_downstream_err_decode;

    always_comb begin
        blk_downstream_err_q = '0;
        blk_downstream_err_q[63: 0] = blk_downstream_err_blk_downstream_err_q;
    end

    // masked version of return data
    assign blk_downstream_err_rdata = blk_downstream_err_sw_rd ? blk_downstream_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: blk_downstream_err
    // ------------------------------------------------------------
    assign blk_downstream_err_blk_downstream_err_anded = & blk_downstream_err_blk_downstream_err_q;
    assign blk_downstream_err_blk_downstream_err_ored  = | blk_downstream_err_blk_downstream_err_q;
    assign blk_downstream_err_blk_downstream_err_xored = ^ blk_downstream_err_blk_downstream_err_q;

    // next hardware value
    assign blk_downstream_err_blk_downstream_err_next = blk_downstream_err_blk_downstream_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        blk_downstream_err_blk_downstream_err_q <= 64'd0;
    end else begin
        // Hardware Write
        if (blk_downstream_err_blk_downstream_err_we) begin
            blk_downstream_err_blk_downstream_err_q <= blk_downstream_err_blk_downstream_err_next;
        end
        // Software write
        else if (blk_downstream_err_sw_wr) begin
            blk_downstream_err_blk_downstream_err_q <= ~sw_masked_data[63: 0] &  blk_downstream_err_blk_downstream_err_q;
        end
    end
            
        
    // ============================================================
    // Register: BLK_DOWNSTREAM_FF_STAT
    //    [63: 0] blk_downstream_ff_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  blk_downstream_ff_stat_decode;
    logic                  blk_downstream_ff_stat_sw_wr;
    logic                  blk_downstream_ff_stat_sw_rd;
    logic [DATA_WIDTH-1:0] blk_downstream_ff_stat_q;

    assign blk_downstream_ff_stat_decode = (addr == (ADDR_OFFSET+'h0+'h100));
    assign blk_downstream_ff_stat_sw_wr = sw_wr && blk_downstream_ff_stat_decode;
    assign blk_downstream_ff_stat_sw_rd = sw_rd && blk_downstream_ff_stat_decode;

    always_comb begin
        blk_downstream_ff_stat_q = '0;
        blk_downstream_ff_stat_q[63: 0] = blk_downstream_ff_stat_blk_downstream_ff_stat_q;
    end

    // masked version of return data
    assign blk_downstream_ff_stat_rdata = blk_downstream_ff_stat_sw_rd ? blk_downstream_ff_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: blk_downstream_ff_stat (wire)
    // ------------------------------------------------------------
    assign blk_downstream_ff_stat_blk_downstream_ff_stat_anded = & blk_downstream_ff_stat_blk_downstream_ff_stat_q;
    assign blk_downstream_ff_stat_blk_downstream_ff_stat_ored  = | blk_downstream_ff_stat_blk_downstream_ff_stat_q;
    assign blk_downstream_ff_stat_blk_downstream_ff_stat_xored = ^ blk_downstream_ff_stat_blk_downstream_ff_stat_q;

    // next hardware value
    assign blk_downstream_ff_stat_blk_downstream_ff_stat_next = blk_downstream_ff_stat_blk_downstream_ff_stat_wdata;
    assign blk_downstream_ff_stat_blk_downstream_ff_stat_q = blk_downstream_ff_stat_blk_downstream_ff_stat_next;
            
        
    // ============================================================
    // Register: BLK_DOWNSTREAM_FSM_STAT
    //    [63: 0] blk_downstream_fsm_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  blk_downstream_fsm_stat_decode;
    logic                  blk_downstream_fsm_stat_sw_wr;
    logic                  blk_downstream_fsm_stat_sw_rd;
    logic [DATA_WIDTH-1:0] blk_downstream_fsm_stat_q;

    assign blk_downstream_fsm_stat_decode = (addr == (ADDR_OFFSET+'h0+'h108));
    assign blk_downstream_fsm_stat_sw_wr = sw_wr && blk_downstream_fsm_stat_decode;
    assign blk_downstream_fsm_stat_sw_rd = sw_rd && blk_downstream_fsm_stat_decode;

    always_comb begin
        blk_downstream_fsm_stat_q = '0;
        blk_downstream_fsm_stat_q[63: 0] = blk_downstream_fsm_stat_blk_downstream_fsm_stat_q;
    end

    // masked version of return data
    assign blk_downstream_fsm_stat_rdata = blk_downstream_fsm_stat_sw_rd ? blk_downstream_fsm_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: blk_downstream_fsm_stat (wire)
    // ------------------------------------------------------------
    assign blk_downstream_fsm_stat_blk_downstream_fsm_stat_anded = & blk_downstream_fsm_stat_blk_downstream_fsm_stat_q;
    assign blk_downstream_fsm_stat_blk_downstream_fsm_stat_ored  = | blk_downstream_fsm_stat_blk_downstream_fsm_stat_q;
    assign blk_downstream_fsm_stat_blk_downstream_fsm_stat_xored = ^ blk_downstream_fsm_stat_blk_downstream_fsm_stat_q;

    // next hardware value
    assign blk_downstream_fsm_stat_blk_downstream_fsm_stat_next = blk_downstream_fsm_stat_blk_downstream_fsm_stat_wdata;
    assign blk_downstream_fsm_stat_blk_downstream_fsm_stat_q = blk_downstream_fsm_stat_blk_downstream_fsm_stat_next;
            
        
    // ============================================================
    // Register: BLK_DOWNSTREAM_ERR_CNT
    //    [63: 0] blk_downstream_err_cnt: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  blk_downstream_err_cnt_decode;
    logic                  blk_downstream_err_cnt_sw_wr;
    logic                  blk_downstream_err_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] blk_downstream_err_cnt_q;

    assign blk_downstream_err_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h200));
    assign blk_downstream_err_cnt_sw_wr = sw_wr && blk_downstream_err_cnt_decode;
    assign blk_downstream_err_cnt_sw_rd = sw_rd && blk_downstream_err_cnt_decode;

    always_comb begin
        blk_downstream_err_cnt_q = '0;
        blk_downstream_err_cnt_q[63: 0] = blk_downstream_err_cnt_blk_downstream_err_cnt_q;
    end

    // masked version of return data
    assign blk_downstream_err_cnt_rdata = blk_downstream_err_cnt_sw_rd ? blk_downstream_err_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: blk_downstream_err_cnt
    // ------------------------------------------------------------
    assign blk_downstream_err_cnt_blk_downstream_err_cnt_anded = & blk_downstream_err_cnt_blk_downstream_err_cnt_q;
    assign blk_downstream_err_cnt_blk_downstream_err_cnt_ored  = | blk_downstream_err_cnt_blk_downstream_err_cnt_q;
    assign blk_downstream_err_cnt_blk_downstream_err_cnt_xored = ^ blk_downstream_err_cnt_blk_downstream_err_cnt_q;

    // next hardware value
    assign blk_downstream_err_cnt_blk_downstream_err_cnt_next = blk_downstream_err_cnt_blk_downstream_err_cnt_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        blk_downstream_err_cnt_blk_downstream_err_cnt_q <= 64'd0;
    end else begin
        // Hardware Write
        if (blk_downstream_err_cnt_blk_downstream_err_cnt_we) begin
            blk_downstream_err_cnt_blk_downstream_err_cnt_q <= blk_downstream_err_cnt_blk_downstream_err_cnt_next;
        end
        // Software write
        else if (blk_downstream_err_cnt_sw_wr) begin
            blk_downstream_err_cnt_blk_downstream_err_cnt_q <= ~sw_masked_data[63: 0] &  blk_downstream_err_cnt_blk_downstream_err_cnt_q;
        end
    end
            
        
    // ============================================================
    // Register: BLK_DOWNSTREAM_IF_CNT
    //    [63: 0] blk_downstream_if_cnt: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  blk_downstream_if_cnt_decode;
    logic                  blk_downstream_if_cnt_sw_wr;
    logic                  blk_downstream_if_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] blk_downstream_if_cnt_q;

    assign blk_downstream_if_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h208));
    assign blk_downstream_if_cnt_sw_wr = sw_wr && blk_downstream_if_cnt_decode;
    assign blk_downstream_if_cnt_sw_rd = sw_rd && blk_downstream_if_cnt_decode;

    always_comb begin
        blk_downstream_if_cnt_q = '0;
        blk_downstream_if_cnt_q[63: 0] = blk_downstream_if_cnt_blk_downstream_if_cnt_q;
    end

    // masked version of return data
    assign blk_downstream_if_cnt_rdata = blk_downstream_if_cnt_sw_rd ? blk_downstream_if_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: blk_downstream_if_cnt
    // ------------------------------------------------------------
    assign blk_downstream_if_cnt_blk_downstream_if_cnt_anded = & blk_downstream_if_cnt_blk_downstream_if_cnt_q;
    assign blk_downstream_if_cnt_blk_downstream_if_cnt_ored  = | blk_downstream_if_cnt_blk_downstream_if_cnt_q;
    assign blk_downstream_if_cnt_blk_downstream_if_cnt_xored = ^ blk_downstream_if_cnt_blk_downstream_if_cnt_q;

    // next hardware value
    assign blk_downstream_if_cnt_blk_downstream_if_cnt_next = blk_downstream_if_cnt_blk_downstream_if_cnt_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        blk_downstream_if_cnt_blk_downstream_if_cnt_q <= 64'd0;
    end else begin
        // Hardware Write
        if (blk_downstream_if_cnt_blk_downstream_if_cnt_we) begin
            blk_downstream_if_cnt_blk_downstream_if_cnt_q <= blk_downstream_if_cnt_blk_downstream_if_cnt_next;
        end
        // Software write
        else if (blk_downstream_if_cnt_sw_wr) begin
            blk_downstream_if_cnt_blk_downstream_if_cnt_q <= ~sw_masked_data[63: 0] &  blk_downstream_if_cnt_blk_downstream_if_cnt_q;
        end
    end
            
        
    // ============================================================
    // Register: BLK_DESC_HS_RELATED_CNT
    //    [63: 0] blk_desc_hs_related_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  blk_desc_hs_related_cnt_decode;
    logic                  blk_desc_hs_related_cnt_sw_wr;
    logic                  blk_desc_hs_related_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] blk_desc_hs_related_cnt_q;

    assign blk_desc_hs_related_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h210));
    assign blk_desc_hs_related_cnt_sw_wr = sw_wr && blk_desc_hs_related_cnt_decode;
    assign blk_desc_hs_related_cnt_sw_rd = sw_rd && blk_desc_hs_related_cnt_decode;

    always_comb begin
        blk_desc_hs_related_cnt_q = '0;
        blk_desc_hs_related_cnt_q[63: 0] = blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_q;
    end

    // masked version of return data
    assign blk_desc_hs_related_cnt_rdata = blk_desc_hs_related_cnt_sw_rd ? blk_desc_hs_related_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: blk_desc_hs_related_cnt (wire)
    // ------------------------------------------------------------
    assign blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_anded = & blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_q;
    assign blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_ored  = | blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_q;
    assign blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_xored = ^ blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_q;

    // next hardware value
    assign blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_next = blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_wdata;
    assign blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_q = blk_desc_hs_related_cnt_blk_desc_hs_related_cnt_next;
            
        
    // ============================================================
    // Register: DMA_RD_REQ_BP_RELATED_CNT
    //    [63: 0] dma_rd_req_bp_related_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dma_rd_req_bp_related_cnt_decode;
    logic                  dma_rd_req_bp_related_cnt_sw_wr;
    logic                  dma_rd_req_bp_related_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dma_rd_req_bp_related_cnt_q;

    assign dma_rd_req_bp_related_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h218));
    assign dma_rd_req_bp_related_cnt_sw_wr = sw_wr && dma_rd_req_bp_related_cnt_decode;
    assign dma_rd_req_bp_related_cnt_sw_rd = sw_rd && dma_rd_req_bp_related_cnt_decode;

    always_comb begin
        dma_rd_req_bp_related_cnt_q = '0;
        dma_rd_req_bp_related_cnt_q[63: 0] = dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_q;
    end

    // masked version of return data
    assign dma_rd_req_bp_related_cnt_rdata = dma_rd_req_bp_related_cnt_sw_rd ? dma_rd_req_bp_related_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dma_rd_req_bp_related_cnt (wire)
    // ------------------------------------------------------------
    assign dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_anded = & dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_q;
    assign dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_ored  = | dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_q;
    assign dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_xored = ^ dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_q;

    // next hardware value
    assign dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_next = dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_wdata;
    assign dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_q = dma_rd_req_bp_related_cnt_dma_rd_req_bp_related_cnt_next;
            
        
    // ============================================================
    // Register: DMA_RD_RSP_BP_VDATA_CNT
    //    [63: 0] dma_rd_rsp_bp_vdata_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dma_rd_rsp_bp_vdata_cnt_decode;
    logic                  dma_rd_rsp_bp_vdata_cnt_sw_wr;
    logic                  dma_rd_rsp_bp_vdata_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dma_rd_rsp_bp_vdata_cnt_q;

    assign dma_rd_rsp_bp_vdata_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h220));
    assign dma_rd_rsp_bp_vdata_cnt_sw_wr = sw_wr && dma_rd_rsp_bp_vdata_cnt_decode;
    assign dma_rd_rsp_bp_vdata_cnt_sw_rd = sw_rd && dma_rd_rsp_bp_vdata_cnt_decode;

    always_comb begin
        dma_rd_rsp_bp_vdata_cnt_q = '0;
        dma_rd_rsp_bp_vdata_cnt_q[63: 0] = dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_q;
    end

    // masked version of return data
    assign dma_rd_rsp_bp_vdata_cnt_rdata = dma_rd_rsp_bp_vdata_cnt_sw_rd ? dma_rd_rsp_bp_vdata_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dma_rd_rsp_bp_vdata_cnt (wire)
    // ------------------------------------------------------------
    assign dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_anded = & dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_q;
    assign dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_ored  = | dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_q;
    assign dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_xored = ^ dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_q;

    // next hardware value
    assign dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_next = dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_wdata;
    assign dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_q = dma_rd_rsp_bp_vdata_cnt_dma_rd_rsp_bp_vdata_cnt_next;
            
        
    // ============================================================
    // Register: BLK_DOWNSTREAM_DMA_INFLIGHT_THRESHOLD
    //    [ 9: 0] blk_downstream_dma_inflight_threshold: hw=r     sw=rw    reset=0x190
    // ============================================================
    logic                  blk_downstream_dma_inflight_threshold_decode;
    logic                  blk_downstream_dma_inflight_threshold_sw_wr;
    logic                  blk_downstream_dma_inflight_threshold_sw_rd;
    logic [DATA_WIDTH-1:0] blk_downstream_dma_inflight_threshold_q;

    assign blk_downstream_dma_inflight_threshold_decode = (addr == (ADDR_OFFSET+'h0+'h500));
    assign blk_downstream_dma_inflight_threshold_sw_wr = sw_wr && blk_downstream_dma_inflight_threshold_decode;
    assign blk_downstream_dma_inflight_threshold_sw_rd = sw_rd && blk_downstream_dma_inflight_threshold_decode;

    always_comb begin
        blk_downstream_dma_inflight_threshold_q = '0;
        blk_downstream_dma_inflight_threshold_q[ 9: 0] = blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_q;
    end

    // masked version of return data
    assign blk_downstream_dma_inflight_threshold_rdata = blk_downstream_dma_inflight_threshold_sw_rd ? blk_downstream_dma_inflight_threshold_q : 'b0;

    // ------------------------------------------------------------
    // Field: blk_downstream_dma_inflight_threshold
    // ------------------------------------------------------------
    assign blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_anded = & blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_q;
    assign blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_ored  = | blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_q;
    assign blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_xored = ^ blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_q <= 64'd400;
    end else begin
        // Software write
        if (blk_downstream_dma_inflight_threshold_sw_wr) begin
            blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_q <=  sw_masked_data[ 9: 0] | (blk_downstream_dma_inflight_threshold_blk_downstream_dma_inflight_threshold_q & ~sw_mask[ 9: 0]);
        end
    end

endmodule: virtio_blk_downstream_dfx
