//==================================================
// This file contains the Excluded objects
// Generated By User: matao
// Format Version: 2
// Date: Fri Oct 24 17:48:14 2025
// ExclMode: default
//==================================================
CHECKSUM: "817296025 4273683015"
INSTANCE: virtio_irq_merge_core_tb.u_virtio_irq_merge_core_top.u_mux_nto1
Condition 3 "2590495169" "(mux_in_vld & mux_in_rdy) 1 -1"
CHECKSUM: "2983548662 3129635948"
INSTANCE: virtio_irq_merge_core_tb.u_virtio_irq_merge_core_top.CORE_ENG[0].u_virtio_irq_merge_core_eng
Toggle eng_id "logic eng_id[2:0]"
CHECKSUM: "2983548662 3129635948"
INSTANCE: virtio_irq_merge_core_tb.u_virtio_irq_merge_core_top.CORE_ENG[1].u_virtio_irq_merge_core_eng
Toggle eng_id "logic eng_id[2:0]"
CHECKSUM: "2983548662 3129635948"
INSTANCE: virtio_irq_merge_core_tb.u_virtio_irq_merge_core_top.CORE_ENG[2].u_virtio_irq_merge_core_eng
Toggle eng_id "logic eng_id[2:0]"
CHECKSUM: "2983548662 3129635948"
INSTANCE: virtio_irq_merge_core_tb.u_virtio_irq_merge_core_top.CORE_ENG[3].u_virtio_irq_merge_core_eng
Toggle eng_id "logic eng_id[2:0]"
CHECKSUM: "2983548662 3129635948"
INSTANCE: virtio_irq_merge_core_tb.u_virtio_irq_merge_core_top.CORE_ENG[4].u_virtio_irq_merge_core_eng
Toggle eng_id "logic eng_id[2:0]"
CHECKSUM: "2983548662 3129635948"
INSTANCE: virtio_irq_merge_core_tb.u_virtio_irq_merge_core_top.CORE_ENG[5].u_virtio_irq_merge_core_eng
Toggle eng_id "logic eng_id[2:0]"
CHECKSUM: "2983548662 3129635948"
INSTANCE: virtio_irq_merge_core_tb.u_virtio_irq_merge_core_top.CORE_ENG[6].u_virtio_irq_merge_core_eng
Toggle eng_id "logic eng_id[2:0]"
CHECKSUM: "2983548662 3129635948"
INSTANCE: virtio_irq_merge_core_tb.u_virtio_irq_merge_core_top.CORE_ENG[7].u_virtio_irq_merge_core_eng
Toggle eng_id "logic eng_id[2:0]"
CHECKSUM: "2692878591 3782818635"
INSTANCE: virtio_irq_merge_core_tb.u_virtio_irq_merge_core_top
Toggle dfx_irq_merge_core_err "logic dfx_irq_merge_core_err[3:0]"
Toggle msix_aggregation_threshold_rd_req_vld_eng_err "logic msix_aggregation_threshold_rd_req_vld_eng_err"
Toggle eng_out_ff_underflow "logic eng_out_ff_underflow"
Toggle eng_out_ff_overflow "logic eng_out_ff_overflow"
Toggle eng_out_ff_err "logic eng_out_ff_err[1:0]"
