// This file was autogenerated by PeakRDL-verilog
module beq_common_dfx #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register DFX_CTX_ERR
    input  logic                             dfx_ctx_err_dfx_ctx_err_we,             //! Control HW write (active high)
    input  logic                     [23: 0] dfx_ctx_err_dfx_ctx_err_wdata,          //! HW write data
    output logic                     [23: 0] dfx_ctx_err_dfx_ctx_err_q,              //! Current field value

    // Register DFX_ERR_HANDLER_ERR
    input  logic                             dfx_err_handler_err_dfx_err_handler_err_we,             //! Control HW write (active high)
    input  logic                     [ 3: 0] dfx_err_handler_err_dfx_err_handler_err_wdata,          //! HW write data
    output logic                     [ 3: 0] dfx_err_handler_err_dfx_err_handler_err_q,              //! Current field value

    // Register DFX_RR_SCH_ERR
    input  logic                             dfx_rr_sch_err_dfx_rr_sch_err_we,             //! Control HW write (active high)
    input  logic                     [13: 0] dfx_rr_sch_err_dfx_rr_sch_err_wdata,          //! HW write data
    output logic                     [13: 0] dfx_rr_sch_err_dfx_rr_sch_err_q,              //! Current field value

    // Register DFX_WRR_SCH_ERR
    input  logic                             dfx_wrr_sch_err_dfx_wrr_sch_err_we,             //! Control HW write (active high)
    input  logic                     [11: 0] dfx_wrr_sch_err_dfx_wrr_sch_err_wdata,          //! HW write data
    output logic                     [11: 0] dfx_wrr_sch_err_dfx_wrr_sch_err_q,              //! Current field value

    // Register DFX_FEQ2BID_ERR
    input  logic                             dfx_feq2bid_err_dfx_feq2bid_err_we,             //! Control HW write (active high)
    input  logic                     [ 3: 0] dfx_feq2bid_err_dfx_feq2bid_err_wdata,          //! HW write data
    output logic                     [ 3: 0] dfx_feq2bid_err_dfx_feq2bid_err_q,              //! Current field value

    // Register DFX_BEQ_MON_ERR
    input  logic                             dfx_beq_mon_err_dfx_beq_mon_err_we,             //! Control HW write (active high)
    input  logic                     [ 5: 0] dfx_beq_mon_err_dfx_beq_mon_err_wdata,          //! HW write data
    output logic                     [ 5: 0] dfx_beq_mon_err_dfx_beq_mon_err_q,              //! Current field value

    // Register DFX_CTX_STATUS
    input  logic                     [18: 0] dfx_ctx_status_dfx_ctx_status_wdata,          //! HW write data

    // Register DFX_ERR_HANDLER_STATUS
    input  logic                     [ 1: 0] dfx_err_handler_status_dfx_err_handler_status_wdata,          //! HW write data

    // Register DFX_RR_SCH_STATUS
    input  logic                     [11: 0] dfx_rr_sch_status_dfx_rr_sch_status_wdata,          //! HW write data

    // Register DFX_WRR_SCH_STATUS
    input  logic                     [18: 0] dfx_wrr_sch_status_dfx_wrr_sch_status_wdata,          //! HW write data

    // Register DFX_FEQ2BID_STATUS
    input  logic                     [ 6: 0] dfx_feq2bid_status_dfx_feq2bid_status_wdata,          //! HW write data

    // Register DFX_RR_SCH_NOTIFY_CNT
    input  logic                     [15: 0] dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_wdata,          //! HW write data

    // Register DFX_WRR_SCH_NOTIFY_CNT
    input  logic                     [15: 0] dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_wdata,          //! HW write data

    // Register DFX_BEQ2USER0_BACKPRESSURE_CNT
    input  logic                     [63: 0] dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_wdata,          //! HW write data

    // Register DFX_BEQ2USER1_BACKPRESSURE_CNT
    input  logic                     [63: 0] dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_wdata,          //! HW write data

    // Register DFX_BEQ2USER2_BACKPRESSURE_CNT
    input  logic                     [63: 0] dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_wdata,          //! HW write data

    // Register DFX_BEQ2USER3_BACKPRESSURE_CNT
    input  logic                     [63: 0] dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_wdata,          //! HW write data

    // Register DFX_USER2BEQ0_BACKPRESSURE_CNT
    input  logic                     [63: 0] dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_wdata,          //! HW write data

    // Register DFX_USER2BEQ1_BACKPRESSURE_CNT
    input  logic                     [63: 0] dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_wdata,          //! HW write data

    // Register DFX_USER2BEQ2_BACKPRESSURE_CNT
    input  logic                     [63: 0] dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_wdata,          //! HW write data

    // Register DFX_USER2BEQ3_BACKPRESSURE_CNT
    input  logic                     [63: 0] dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_wdata,          //! HW write data

    // Register RR_SCH_WEIGHT
    output logic                     [ 7: 0] rr_sch_weight_rr_sch_weight_q,              //! Current field value

    // Register WRR_SCH_WEIGHT
    output logic                     [15: 0] wrr_sch_weight_wrr_sch_weight_q,              //! Current field value

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [23: 0] dfx_ctx_err_dfx_ctx_err_next;
    logic                             dfx_ctx_err_dfx_ctx_err_anded;
    logic                             dfx_ctx_err_dfx_ctx_err_ored;
    logic                             dfx_ctx_err_dfx_ctx_err_xored;
    logic                           [ 3: 0] dfx_err_handler_err_dfx_err_handler_err_next;
    logic                             dfx_err_handler_err_dfx_err_handler_err_anded;
    logic                             dfx_err_handler_err_dfx_err_handler_err_ored;
    logic                             dfx_err_handler_err_dfx_err_handler_err_xored;
    logic                           [13: 0] dfx_rr_sch_err_dfx_rr_sch_err_next;
    logic                             dfx_rr_sch_err_dfx_rr_sch_err_anded;
    logic                             dfx_rr_sch_err_dfx_rr_sch_err_ored;
    logic                             dfx_rr_sch_err_dfx_rr_sch_err_xored;
    logic                           [11: 0] dfx_wrr_sch_err_dfx_wrr_sch_err_next;
    logic                             dfx_wrr_sch_err_dfx_wrr_sch_err_anded;
    logic                             dfx_wrr_sch_err_dfx_wrr_sch_err_ored;
    logic                             dfx_wrr_sch_err_dfx_wrr_sch_err_xored;
    logic                           [ 3: 0] dfx_feq2bid_err_dfx_feq2bid_err_next;
    logic                             dfx_feq2bid_err_dfx_feq2bid_err_anded;
    logic                             dfx_feq2bid_err_dfx_feq2bid_err_ored;
    logic                             dfx_feq2bid_err_dfx_feq2bid_err_xored;
    logic                           [ 5: 0] dfx_beq_mon_err_dfx_beq_mon_err_next;
    logic                             dfx_beq_mon_err_dfx_beq_mon_err_anded;
    logic                             dfx_beq_mon_err_dfx_beq_mon_err_ored;
    logic                             dfx_beq_mon_err_dfx_beq_mon_err_xored;
    logic                           [18: 0] dfx_ctx_status_dfx_ctx_status_q;
    logic                           [18: 0] dfx_ctx_status_dfx_ctx_status_next;
    logic                             dfx_ctx_status_dfx_ctx_status_anded;
    logic                             dfx_ctx_status_dfx_ctx_status_ored;
    logic                             dfx_ctx_status_dfx_ctx_status_xored;
    logic                           [ 1: 0] dfx_err_handler_status_dfx_err_handler_status_q;
    logic                           [ 1: 0] dfx_err_handler_status_dfx_err_handler_status_next;
    logic                             dfx_err_handler_status_dfx_err_handler_status_anded;
    logic                             dfx_err_handler_status_dfx_err_handler_status_ored;
    logic                             dfx_err_handler_status_dfx_err_handler_status_xored;
    logic                           [11: 0] dfx_rr_sch_status_dfx_rr_sch_status_q;
    logic                           [11: 0] dfx_rr_sch_status_dfx_rr_sch_status_next;
    logic                             dfx_rr_sch_status_dfx_rr_sch_status_anded;
    logic                             dfx_rr_sch_status_dfx_rr_sch_status_ored;
    logic                             dfx_rr_sch_status_dfx_rr_sch_status_xored;
    logic                           [18: 0] dfx_wrr_sch_status_dfx_wrr_sch_status_q;
    logic                           [18: 0] dfx_wrr_sch_status_dfx_wrr_sch_status_next;
    logic                             dfx_wrr_sch_status_dfx_wrr_sch_status_anded;
    logic                             dfx_wrr_sch_status_dfx_wrr_sch_status_ored;
    logic                             dfx_wrr_sch_status_dfx_wrr_sch_status_xored;
    logic                           [ 6: 0] dfx_feq2bid_status_dfx_feq2bid_status_q;
    logic                           [ 6: 0] dfx_feq2bid_status_dfx_feq2bid_status_next;
    logic                             dfx_feq2bid_status_dfx_feq2bid_status_anded;
    logic                             dfx_feq2bid_status_dfx_feq2bid_status_ored;
    logic                             dfx_feq2bid_status_dfx_feq2bid_status_xored;
    logic                           [15: 0] dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_q;
    logic                           [15: 0] dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_next;
    logic                             dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_anded;
    logic                             dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_ored;
    logic                             dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_xored;
    logic                           [15: 0] dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_q;
    logic                           [15: 0] dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_next;
    logic                             dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_anded;
    logic                             dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_ored;
    logic                             dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_xored;
    logic                           [63: 0] dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_q;
    logic                           [63: 0] dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_next;
    logic                             dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_anded;
    logic                             dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_ored;
    logic                             dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_xored;
    logic                           [63: 0] dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_q;
    logic                           [63: 0] dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_next;
    logic                             dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_anded;
    logic                             dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_ored;
    logic                             dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_xored;
    logic                           [63: 0] dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_q;
    logic                           [63: 0] dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_next;
    logic                             dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_anded;
    logic                             dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_ored;
    logic                             dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_xored;
    logic                           [63: 0] dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_q;
    logic                           [63: 0] dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_next;
    logic                             dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_anded;
    logic                             dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_ored;
    logic                             dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_xored;
    logic                           [63: 0] dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_q;
    logic                           [63: 0] dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_next;
    logic                             dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_anded;
    logic                             dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_ored;
    logic                             dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_xored;
    logic                           [63: 0] dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_q;
    logic                           [63: 0] dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_next;
    logic                             dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_anded;
    logic                             dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_ored;
    logic                             dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_xored;
    logic                           [63: 0] dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_q;
    logic                           [63: 0] dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_next;
    logic                             dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_anded;
    logic                             dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_ored;
    logic                             dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_xored;
    logic                           [63: 0] dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_q;
    logic                           [63: 0] dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_next;
    logic                             dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_anded;
    logic                             dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_ored;
    logic                             dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_xored;
    logic                           [ 7: 0] rr_sch_weight_rr_sch_weight_next;
    logic                             rr_sch_weight_rr_sch_weight_anded;
    logic                             rr_sch_weight_rr_sch_weight_ored;
    logic                             rr_sch_weight_rr_sch_weight_xored;
    logic                           [15: 0] wrr_sch_weight_wrr_sch_weight_next;
    logic                             wrr_sch_weight_wrr_sch_weight_anded;
    logic                             wrr_sch_weight_wrr_sch_weight_ored;
    logic                             wrr_sch_weight_wrr_sch_weight_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [ADDR_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] dfx_ctx_err_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_err_handler_err_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_rr_sch_err_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_wrr_sch_err_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_feq2bid_err_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_beq_mon_err_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_ctx_status_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_err_handler_status_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_rr_sch_status_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_wrr_sch_status_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_feq2bid_status_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_rr_sch_notify_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_wrr_sch_notify_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_beq2user0_backpressure_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_beq2user1_backpressure_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_beq2user2_backpressure_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_beq2user3_backpressure_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_user2beq0_backpressure_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_user2beq1_backpressure_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_user2beq2_backpressure_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] dfx_user2beq3_backpressure_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] rr_sch_weight_rdata;
    logic                     [DATA_WIDTH-1:0] wrr_sch_weight_rdata;

    assign sw_rdata = // or of each register return (masked)
                   dfx_ctx_err_rdata | 
                   dfx_err_handler_err_rdata | 
                   dfx_rr_sch_err_rdata | 
                   dfx_wrr_sch_err_rdata | 
                   dfx_feq2bid_err_rdata | 
                   dfx_beq_mon_err_rdata | 
                   dfx_ctx_status_rdata | 
                   dfx_err_handler_status_rdata | 
                   dfx_rr_sch_status_rdata | 
                   dfx_wrr_sch_status_rdata | 
                   dfx_feq2bid_status_rdata | 
                   dfx_rr_sch_notify_cnt_rdata | 
                   dfx_wrr_sch_notify_cnt_rdata | 
                   dfx_beq2user0_backpressure_cnt_rdata | 
                   dfx_beq2user1_backpressure_cnt_rdata | 
                   dfx_beq2user2_backpressure_cnt_rdata | 
                   dfx_beq2user3_backpressure_cnt_rdata | 
                   dfx_user2beq0_backpressure_cnt_rdata | 
                   dfx_user2beq1_backpressure_cnt_rdata | 
                   dfx_user2beq2_backpressure_cnt_rdata | 
                   dfx_user2beq3_backpressure_cnt_rdata | 
                   rr_sch_weight_rdata | 
                   wrr_sch_weight_rdata;
            
        
    // ============================================================
    // Register: DFX_CTX_ERR
    //    [23: 0]          dfx_ctx_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  dfx_ctx_err_decode;
    logic                  dfx_ctx_err_sw_wr;
    logic                  dfx_ctx_err_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_ctx_err_q;

    assign dfx_ctx_err_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign dfx_ctx_err_sw_wr = sw_wr && dfx_ctx_err_decode;
    assign dfx_ctx_err_sw_rd = sw_rd && dfx_ctx_err_decode;

    always_comb begin
        dfx_ctx_err_q = '0;
        dfx_ctx_err_q[23: 0] = dfx_ctx_err_dfx_ctx_err_q;
    end

    // masked version of return data
    assign dfx_ctx_err_rdata = dfx_ctx_err_sw_rd ? dfx_ctx_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_ctx_err
    // ------------------------------------------------------------
    assign dfx_ctx_err_dfx_ctx_err_anded = & dfx_ctx_err_dfx_ctx_err_q;
    assign dfx_ctx_err_dfx_ctx_err_ored  = | dfx_ctx_err_dfx_ctx_err_q;
    assign dfx_ctx_err_dfx_ctx_err_xored = ^ dfx_ctx_err_dfx_ctx_err_q;

    // next hardware value
    assign dfx_ctx_err_dfx_ctx_err_next = dfx_ctx_err_dfx_ctx_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        dfx_ctx_err_dfx_ctx_err_q <= 0;
    end else begin
        // Hardware Write
        if (dfx_ctx_err_dfx_ctx_err_we) begin
            dfx_ctx_err_dfx_ctx_err_q <= dfx_ctx_err_dfx_ctx_err_next;
        end
        // Software write
        else if (dfx_ctx_err_sw_wr) begin
            dfx_ctx_err_dfx_ctx_err_q <= ~sw_masked_data[23: 0] &  dfx_ctx_err_dfx_ctx_err_q;
        end
    end
            
        
    // ============================================================
    // Register: DFX_ERR_HANDLER_ERR
    //    [ 3: 0]  dfx_err_handler_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  dfx_err_handler_err_decode;
    logic                  dfx_err_handler_err_sw_wr;
    logic                  dfx_err_handler_err_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_err_handler_err_q;

    assign dfx_err_handler_err_decode = (addr == (ADDR_OFFSET+'h0+'h8));
    assign dfx_err_handler_err_sw_wr = sw_wr && dfx_err_handler_err_decode;
    assign dfx_err_handler_err_sw_rd = sw_rd && dfx_err_handler_err_decode;

    always_comb begin
        dfx_err_handler_err_q = '0;
        dfx_err_handler_err_q[ 3: 0] = dfx_err_handler_err_dfx_err_handler_err_q;
    end

    // masked version of return data
    assign dfx_err_handler_err_rdata = dfx_err_handler_err_sw_rd ? dfx_err_handler_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_err_handler_err
    // ------------------------------------------------------------
    assign dfx_err_handler_err_dfx_err_handler_err_anded = & dfx_err_handler_err_dfx_err_handler_err_q;
    assign dfx_err_handler_err_dfx_err_handler_err_ored  = | dfx_err_handler_err_dfx_err_handler_err_q;
    assign dfx_err_handler_err_dfx_err_handler_err_xored = ^ dfx_err_handler_err_dfx_err_handler_err_q;

    // next hardware value
    assign dfx_err_handler_err_dfx_err_handler_err_next = dfx_err_handler_err_dfx_err_handler_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        dfx_err_handler_err_dfx_err_handler_err_q <= 0;
    end else begin
        // Hardware Write
        if (dfx_err_handler_err_dfx_err_handler_err_we) begin
            dfx_err_handler_err_dfx_err_handler_err_q <= dfx_err_handler_err_dfx_err_handler_err_next;
        end
        // Software write
        else if (dfx_err_handler_err_sw_wr) begin
            dfx_err_handler_err_dfx_err_handler_err_q <= ~sw_masked_data[ 3: 0] &  dfx_err_handler_err_dfx_err_handler_err_q;
        end
    end
            
        
    // ============================================================
    // Register: DFX_RR_SCH_ERR
    //    [13: 0]       dfx_rr_sch_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  dfx_rr_sch_err_decode;
    logic                  dfx_rr_sch_err_sw_wr;
    logic                  dfx_rr_sch_err_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_rr_sch_err_q;

    assign dfx_rr_sch_err_decode = (addr == (ADDR_OFFSET+'h0+'h10));
    assign dfx_rr_sch_err_sw_wr = sw_wr && dfx_rr_sch_err_decode;
    assign dfx_rr_sch_err_sw_rd = sw_rd && dfx_rr_sch_err_decode;

    always_comb begin
        dfx_rr_sch_err_q = '0;
        dfx_rr_sch_err_q[13: 0] = dfx_rr_sch_err_dfx_rr_sch_err_q;
    end

    // masked version of return data
    assign dfx_rr_sch_err_rdata = dfx_rr_sch_err_sw_rd ? dfx_rr_sch_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_rr_sch_err
    // ------------------------------------------------------------
    assign dfx_rr_sch_err_dfx_rr_sch_err_anded = & dfx_rr_sch_err_dfx_rr_sch_err_q;
    assign dfx_rr_sch_err_dfx_rr_sch_err_ored  = | dfx_rr_sch_err_dfx_rr_sch_err_q;
    assign dfx_rr_sch_err_dfx_rr_sch_err_xored = ^ dfx_rr_sch_err_dfx_rr_sch_err_q;

    // next hardware value
    assign dfx_rr_sch_err_dfx_rr_sch_err_next = dfx_rr_sch_err_dfx_rr_sch_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        dfx_rr_sch_err_dfx_rr_sch_err_q <= 0;
    end else begin
        // Hardware Write
        if (dfx_rr_sch_err_dfx_rr_sch_err_we) begin
            dfx_rr_sch_err_dfx_rr_sch_err_q <= dfx_rr_sch_err_dfx_rr_sch_err_next;
        end
        // Software write
        else if (dfx_rr_sch_err_sw_wr) begin
            dfx_rr_sch_err_dfx_rr_sch_err_q <= ~sw_masked_data[13: 0] &  dfx_rr_sch_err_dfx_rr_sch_err_q;
        end
    end
            
        
    // ============================================================
    // Register: DFX_WRR_SCH_ERR
    //    [11: 0]      dfx_wrr_sch_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  dfx_wrr_sch_err_decode;
    logic                  dfx_wrr_sch_err_sw_wr;
    logic                  dfx_wrr_sch_err_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_wrr_sch_err_q;

    assign dfx_wrr_sch_err_decode = (addr == (ADDR_OFFSET+'h0+'h18));
    assign dfx_wrr_sch_err_sw_wr = sw_wr && dfx_wrr_sch_err_decode;
    assign dfx_wrr_sch_err_sw_rd = sw_rd && dfx_wrr_sch_err_decode;

    always_comb begin
        dfx_wrr_sch_err_q = '0;
        dfx_wrr_sch_err_q[11: 0] = dfx_wrr_sch_err_dfx_wrr_sch_err_q;
    end

    // masked version of return data
    assign dfx_wrr_sch_err_rdata = dfx_wrr_sch_err_sw_rd ? dfx_wrr_sch_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_wrr_sch_err
    // ------------------------------------------------------------
    assign dfx_wrr_sch_err_dfx_wrr_sch_err_anded = & dfx_wrr_sch_err_dfx_wrr_sch_err_q;
    assign dfx_wrr_sch_err_dfx_wrr_sch_err_ored  = | dfx_wrr_sch_err_dfx_wrr_sch_err_q;
    assign dfx_wrr_sch_err_dfx_wrr_sch_err_xored = ^ dfx_wrr_sch_err_dfx_wrr_sch_err_q;

    // next hardware value
    assign dfx_wrr_sch_err_dfx_wrr_sch_err_next = dfx_wrr_sch_err_dfx_wrr_sch_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        dfx_wrr_sch_err_dfx_wrr_sch_err_q <= 0;
    end else begin
        // Hardware Write
        if (dfx_wrr_sch_err_dfx_wrr_sch_err_we) begin
            dfx_wrr_sch_err_dfx_wrr_sch_err_q <= dfx_wrr_sch_err_dfx_wrr_sch_err_next;
        end
        // Software write
        else if (dfx_wrr_sch_err_sw_wr) begin
            dfx_wrr_sch_err_dfx_wrr_sch_err_q <= ~sw_masked_data[11: 0] &  dfx_wrr_sch_err_dfx_wrr_sch_err_q;
        end
    end
            
        
    // ============================================================
    // Register: DFX_FEQ2BID_ERR
    //    [ 3: 0]      dfx_feq2bid_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  dfx_feq2bid_err_decode;
    logic                  dfx_feq2bid_err_sw_wr;
    logic                  dfx_feq2bid_err_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_feq2bid_err_q;

    assign dfx_feq2bid_err_decode = (addr == (ADDR_OFFSET+'h0+'h20));
    assign dfx_feq2bid_err_sw_wr = sw_wr && dfx_feq2bid_err_decode;
    assign dfx_feq2bid_err_sw_rd = sw_rd && dfx_feq2bid_err_decode;

    always_comb begin
        dfx_feq2bid_err_q = '0;
        dfx_feq2bid_err_q[ 3: 0] = dfx_feq2bid_err_dfx_feq2bid_err_q;
    end

    // masked version of return data
    assign dfx_feq2bid_err_rdata = dfx_feq2bid_err_sw_rd ? dfx_feq2bid_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_feq2bid_err
    // ------------------------------------------------------------
    assign dfx_feq2bid_err_dfx_feq2bid_err_anded = & dfx_feq2bid_err_dfx_feq2bid_err_q;
    assign dfx_feq2bid_err_dfx_feq2bid_err_ored  = | dfx_feq2bid_err_dfx_feq2bid_err_q;
    assign dfx_feq2bid_err_dfx_feq2bid_err_xored = ^ dfx_feq2bid_err_dfx_feq2bid_err_q;

    // next hardware value
    assign dfx_feq2bid_err_dfx_feq2bid_err_next = dfx_feq2bid_err_dfx_feq2bid_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        dfx_feq2bid_err_dfx_feq2bid_err_q <= 0;
    end else begin
        // Hardware Write
        if (dfx_feq2bid_err_dfx_feq2bid_err_we) begin
            dfx_feq2bid_err_dfx_feq2bid_err_q <= dfx_feq2bid_err_dfx_feq2bid_err_next;
        end
        // Software write
        else if (dfx_feq2bid_err_sw_wr) begin
            dfx_feq2bid_err_dfx_feq2bid_err_q <= ~sw_masked_data[ 3: 0] &  dfx_feq2bid_err_dfx_feq2bid_err_q;
        end
    end
            
        
    // ============================================================
    // Register: DFX_BEQ_MON_ERR
    //    [ 5: 0]      dfx_beq_mon_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  dfx_beq_mon_err_decode;
    logic                  dfx_beq_mon_err_sw_wr;
    logic                  dfx_beq_mon_err_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_beq_mon_err_q;

    assign dfx_beq_mon_err_decode = (addr == (ADDR_OFFSET+'h0+'h28));
    assign dfx_beq_mon_err_sw_wr = sw_wr && dfx_beq_mon_err_decode;
    assign dfx_beq_mon_err_sw_rd = sw_rd && dfx_beq_mon_err_decode;

    always_comb begin
        dfx_beq_mon_err_q = '0;
        dfx_beq_mon_err_q[ 5: 0] = dfx_beq_mon_err_dfx_beq_mon_err_q;
    end

    // masked version of return data
    assign dfx_beq_mon_err_rdata = dfx_beq_mon_err_sw_rd ? dfx_beq_mon_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_beq_mon_err
    // ------------------------------------------------------------
    assign dfx_beq_mon_err_dfx_beq_mon_err_anded = & dfx_beq_mon_err_dfx_beq_mon_err_q;
    assign dfx_beq_mon_err_dfx_beq_mon_err_ored  = | dfx_beq_mon_err_dfx_beq_mon_err_q;
    assign dfx_beq_mon_err_dfx_beq_mon_err_xored = ^ dfx_beq_mon_err_dfx_beq_mon_err_q;

    // next hardware value
    assign dfx_beq_mon_err_dfx_beq_mon_err_next = dfx_beq_mon_err_dfx_beq_mon_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        dfx_beq_mon_err_dfx_beq_mon_err_q <= 0;
    end else begin
        // Hardware Write
        if (dfx_beq_mon_err_dfx_beq_mon_err_we) begin
            dfx_beq_mon_err_dfx_beq_mon_err_q <= dfx_beq_mon_err_dfx_beq_mon_err_next;
        end
        // Software write
        else if (dfx_beq_mon_err_sw_wr) begin
            dfx_beq_mon_err_dfx_beq_mon_err_q <= ~sw_masked_data[ 5: 0] &  dfx_beq_mon_err_dfx_beq_mon_err_q;
        end
    end
            
        
    // ============================================================
    // Register: DFX_CTX_STATUS
    //    [18: 0]       dfx_ctx_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_ctx_status_decode;
    logic                  dfx_ctx_status_sw_wr;
    logic                  dfx_ctx_status_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_ctx_status_q;

    assign dfx_ctx_status_decode = (addr == (ADDR_OFFSET+'h0+'h40));
    assign dfx_ctx_status_sw_wr = sw_wr && dfx_ctx_status_decode;
    assign dfx_ctx_status_sw_rd = sw_rd && dfx_ctx_status_decode;

    always_comb begin
        dfx_ctx_status_q = '0;
        dfx_ctx_status_q[18: 0] = dfx_ctx_status_dfx_ctx_status_q;
    end

    // masked version of return data
    assign dfx_ctx_status_rdata = dfx_ctx_status_sw_rd ? dfx_ctx_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_ctx_status (wire)
    // ------------------------------------------------------------
    assign dfx_ctx_status_dfx_ctx_status_anded = & dfx_ctx_status_dfx_ctx_status_q;
    assign dfx_ctx_status_dfx_ctx_status_ored  = | dfx_ctx_status_dfx_ctx_status_q;
    assign dfx_ctx_status_dfx_ctx_status_xored = ^ dfx_ctx_status_dfx_ctx_status_q;

    // next hardware value
    assign dfx_ctx_status_dfx_ctx_status_next = dfx_ctx_status_dfx_ctx_status_wdata;
    assign dfx_ctx_status_dfx_ctx_status_q = dfx_ctx_status_dfx_ctx_status_next;
            
        
    // ============================================================
    // Register: DFX_ERR_HANDLER_STATUS
    //    [ 1: 0] dfx_err_handler_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_err_handler_status_decode;
    logic                  dfx_err_handler_status_sw_wr;
    logic                  dfx_err_handler_status_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_err_handler_status_q;

    assign dfx_err_handler_status_decode = (addr == (ADDR_OFFSET+'h0+'h48));
    assign dfx_err_handler_status_sw_wr = sw_wr && dfx_err_handler_status_decode;
    assign dfx_err_handler_status_sw_rd = sw_rd && dfx_err_handler_status_decode;

    always_comb begin
        dfx_err_handler_status_q = '0;
        dfx_err_handler_status_q[ 1: 0] = dfx_err_handler_status_dfx_err_handler_status_q;
    end

    // masked version of return data
    assign dfx_err_handler_status_rdata = dfx_err_handler_status_sw_rd ? dfx_err_handler_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_err_handler_status (wire)
    // ------------------------------------------------------------
    assign dfx_err_handler_status_dfx_err_handler_status_anded = & dfx_err_handler_status_dfx_err_handler_status_q;
    assign dfx_err_handler_status_dfx_err_handler_status_ored  = | dfx_err_handler_status_dfx_err_handler_status_q;
    assign dfx_err_handler_status_dfx_err_handler_status_xored = ^ dfx_err_handler_status_dfx_err_handler_status_q;

    // next hardware value
    assign dfx_err_handler_status_dfx_err_handler_status_next = dfx_err_handler_status_dfx_err_handler_status_wdata;
    assign dfx_err_handler_status_dfx_err_handler_status_q = dfx_err_handler_status_dfx_err_handler_status_next;
            
        
    // ============================================================
    // Register: DFX_RR_SCH_STATUS
    //    [11: 0]    dfx_rr_sch_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_rr_sch_status_decode;
    logic                  dfx_rr_sch_status_sw_wr;
    logic                  dfx_rr_sch_status_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_rr_sch_status_q;

    assign dfx_rr_sch_status_decode = (addr == (ADDR_OFFSET+'h0+'h50));
    assign dfx_rr_sch_status_sw_wr = sw_wr && dfx_rr_sch_status_decode;
    assign dfx_rr_sch_status_sw_rd = sw_rd && dfx_rr_sch_status_decode;

    always_comb begin
        dfx_rr_sch_status_q = '0;
        dfx_rr_sch_status_q[11: 0] = dfx_rr_sch_status_dfx_rr_sch_status_q;
    end

    // masked version of return data
    assign dfx_rr_sch_status_rdata = dfx_rr_sch_status_sw_rd ? dfx_rr_sch_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_rr_sch_status (wire)
    // ------------------------------------------------------------
    assign dfx_rr_sch_status_dfx_rr_sch_status_anded = & dfx_rr_sch_status_dfx_rr_sch_status_q;
    assign dfx_rr_sch_status_dfx_rr_sch_status_ored  = | dfx_rr_sch_status_dfx_rr_sch_status_q;
    assign dfx_rr_sch_status_dfx_rr_sch_status_xored = ^ dfx_rr_sch_status_dfx_rr_sch_status_q;

    // next hardware value
    assign dfx_rr_sch_status_dfx_rr_sch_status_next = dfx_rr_sch_status_dfx_rr_sch_status_wdata;
    assign dfx_rr_sch_status_dfx_rr_sch_status_q = dfx_rr_sch_status_dfx_rr_sch_status_next;
            
        
    // ============================================================
    // Register: DFX_WRR_SCH_STATUS
    //    [18: 0]   dfx_wrr_sch_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_wrr_sch_status_decode;
    logic                  dfx_wrr_sch_status_sw_wr;
    logic                  dfx_wrr_sch_status_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_wrr_sch_status_q;

    assign dfx_wrr_sch_status_decode = (addr == (ADDR_OFFSET+'h0+'h58));
    assign dfx_wrr_sch_status_sw_wr = sw_wr && dfx_wrr_sch_status_decode;
    assign dfx_wrr_sch_status_sw_rd = sw_rd && dfx_wrr_sch_status_decode;

    always_comb begin
        dfx_wrr_sch_status_q = '0;
        dfx_wrr_sch_status_q[18: 0] = dfx_wrr_sch_status_dfx_wrr_sch_status_q;
    end

    // masked version of return data
    assign dfx_wrr_sch_status_rdata = dfx_wrr_sch_status_sw_rd ? dfx_wrr_sch_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_wrr_sch_status (wire)
    // ------------------------------------------------------------
    assign dfx_wrr_sch_status_dfx_wrr_sch_status_anded = & dfx_wrr_sch_status_dfx_wrr_sch_status_q;
    assign dfx_wrr_sch_status_dfx_wrr_sch_status_ored  = | dfx_wrr_sch_status_dfx_wrr_sch_status_q;
    assign dfx_wrr_sch_status_dfx_wrr_sch_status_xored = ^ dfx_wrr_sch_status_dfx_wrr_sch_status_q;

    // next hardware value
    assign dfx_wrr_sch_status_dfx_wrr_sch_status_next = dfx_wrr_sch_status_dfx_wrr_sch_status_wdata;
    assign dfx_wrr_sch_status_dfx_wrr_sch_status_q = dfx_wrr_sch_status_dfx_wrr_sch_status_next;
            
        
    // ============================================================
    // Register: DFX_FEQ2BID_STATUS
    //    [ 6: 0]   dfx_feq2bid_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_feq2bid_status_decode;
    logic                  dfx_feq2bid_status_sw_wr;
    logic                  dfx_feq2bid_status_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_feq2bid_status_q;

    assign dfx_feq2bid_status_decode = (addr == (ADDR_OFFSET+'h0+'h60));
    assign dfx_feq2bid_status_sw_wr = sw_wr && dfx_feq2bid_status_decode;
    assign dfx_feq2bid_status_sw_rd = sw_rd && dfx_feq2bid_status_decode;

    always_comb begin
        dfx_feq2bid_status_q = '0;
        dfx_feq2bid_status_q[ 6: 0] = dfx_feq2bid_status_dfx_feq2bid_status_q;
    end

    // masked version of return data
    assign dfx_feq2bid_status_rdata = dfx_feq2bid_status_sw_rd ? dfx_feq2bid_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_feq2bid_status (wire)
    // ------------------------------------------------------------
    assign dfx_feq2bid_status_dfx_feq2bid_status_anded = & dfx_feq2bid_status_dfx_feq2bid_status_q;
    assign dfx_feq2bid_status_dfx_feq2bid_status_ored  = | dfx_feq2bid_status_dfx_feq2bid_status_q;
    assign dfx_feq2bid_status_dfx_feq2bid_status_xored = ^ dfx_feq2bid_status_dfx_feq2bid_status_q;

    // next hardware value
    assign dfx_feq2bid_status_dfx_feq2bid_status_next = dfx_feq2bid_status_dfx_feq2bid_status_wdata;
    assign dfx_feq2bid_status_dfx_feq2bid_status_q = dfx_feq2bid_status_dfx_feq2bid_status_next;
            
        
    // ============================================================
    // Register: DFX_RR_SCH_NOTIFY_CNT
    //    [15: 0] dfx_rr_sch_notify_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_rr_sch_notify_cnt_decode;
    logic                  dfx_rr_sch_notify_cnt_sw_wr;
    logic                  dfx_rr_sch_notify_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_rr_sch_notify_cnt_q;

    assign dfx_rr_sch_notify_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h100));
    assign dfx_rr_sch_notify_cnt_sw_wr = sw_wr && dfx_rr_sch_notify_cnt_decode;
    assign dfx_rr_sch_notify_cnt_sw_rd = sw_rd && dfx_rr_sch_notify_cnt_decode;

    always_comb begin
        dfx_rr_sch_notify_cnt_q = '0;
        dfx_rr_sch_notify_cnt_q[15: 0] = dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_q;
    end

    // masked version of return data
    assign dfx_rr_sch_notify_cnt_rdata = dfx_rr_sch_notify_cnt_sw_rd ? dfx_rr_sch_notify_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_rr_sch_notify_cnt (wire)
    // ------------------------------------------------------------
    assign dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_anded = & dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_q;
    assign dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_ored  = | dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_q;
    assign dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_xored = ^ dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_q;

    // next hardware value
    assign dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_next = dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_wdata;
    assign dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_q = dfx_rr_sch_notify_cnt_dfx_rr_sch_notify_cnt_next;
            
        
    // ============================================================
    // Register: DFX_WRR_SCH_NOTIFY_CNT
    //    [15: 0] dfx_wrr_sch_notify_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_wrr_sch_notify_cnt_decode;
    logic                  dfx_wrr_sch_notify_cnt_sw_wr;
    logic                  dfx_wrr_sch_notify_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_wrr_sch_notify_cnt_q;

    assign dfx_wrr_sch_notify_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h108));
    assign dfx_wrr_sch_notify_cnt_sw_wr = sw_wr && dfx_wrr_sch_notify_cnt_decode;
    assign dfx_wrr_sch_notify_cnt_sw_rd = sw_rd && dfx_wrr_sch_notify_cnt_decode;

    always_comb begin
        dfx_wrr_sch_notify_cnt_q = '0;
        dfx_wrr_sch_notify_cnt_q[15: 0] = dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_q;
    end

    // masked version of return data
    assign dfx_wrr_sch_notify_cnt_rdata = dfx_wrr_sch_notify_cnt_sw_rd ? dfx_wrr_sch_notify_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_wrr_sch_notify_cnt (wire)
    // ------------------------------------------------------------
    assign dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_anded = & dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_q;
    assign dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_ored  = | dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_q;
    assign dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_xored = ^ dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_q;

    // next hardware value
    assign dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_next = dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_wdata;
    assign dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_q = dfx_wrr_sch_notify_cnt_dfx_wrr_sch_notify_cnt_next;
            
        
    // ============================================================
    // Register: DFX_BEQ2USER0_BACKPRESSURE_CNT
    //    [63: 0] dfx_beq2user0_backpressure_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_beq2user0_backpressure_cnt_decode;
    logic                  dfx_beq2user0_backpressure_cnt_sw_wr;
    logic                  dfx_beq2user0_backpressure_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_beq2user0_backpressure_cnt_q;

    assign dfx_beq2user0_backpressure_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h110));
    assign dfx_beq2user0_backpressure_cnt_sw_wr = sw_wr && dfx_beq2user0_backpressure_cnt_decode;
    assign dfx_beq2user0_backpressure_cnt_sw_rd = sw_rd && dfx_beq2user0_backpressure_cnt_decode;

    always_comb begin
        dfx_beq2user0_backpressure_cnt_q = '0;
        dfx_beq2user0_backpressure_cnt_q[63: 0] = dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_q;
    end

    // masked version of return data
    assign dfx_beq2user0_backpressure_cnt_rdata = dfx_beq2user0_backpressure_cnt_sw_rd ? dfx_beq2user0_backpressure_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_beq2user0_backpressure_cnt (wire)
    // ------------------------------------------------------------
    assign dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_anded = & dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_q;
    assign dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_ored  = | dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_q;
    assign dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_xored = ^ dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_q;

    // next hardware value
    assign dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_next = dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_wdata;
    assign dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_q = dfx_beq2user0_backpressure_cnt_dfx_beq2user0_backpressure_cnt_next;
            
        
    // ============================================================
    // Register: DFX_BEQ2USER1_BACKPRESSURE_CNT
    //    [63: 0] dfx_beq2user1_backpressure_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_beq2user1_backpressure_cnt_decode;
    logic                  dfx_beq2user1_backpressure_cnt_sw_wr;
    logic                  dfx_beq2user1_backpressure_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_beq2user1_backpressure_cnt_q;

    assign dfx_beq2user1_backpressure_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h118));
    assign dfx_beq2user1_backpressure_cnt_sw_wr = sw_wr && dfx_beq2user1_backpressure_cnt_decode;
    assign dfx_beq2user1_backpressure_cnt_sw_rd = sw_rd && dfx_beq2user1_backpressure_cnt_decode;

    always_comb begin
        dfx_beq2user1_backpressure_cnt_q = '0;
        dfx_beq2user1_backpressure_cnt_q[63: 0] = dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_q;
    end

    // masked version of return data
    assign dfx_beq2user1_backpressure_cnt_rdata = dfx_beq2user1_backpressure_cnt_sw_rd ? dfx_beq2user1_backpressure_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_beq2user1_backpressure_cnt (wire)
    // ------------------------------------------------------------
    assign dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_anded = & dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_q;
    assign dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_ored  = | dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_q;
    assign dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_xored = ^ dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_q;

    // next hardware value
    assign dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_next = dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_wdata;
    assign dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_q = dfx_beq2user1_backpressure_cnt_dfx_beq2user1_backpressure_cnt_next;
            
        
    // ============================================================
    // Register: DFX_BEQ2USER2_BACKPRESSURE_CNT
    //    [63: 0] dfx_beq2user2_backpressure_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_beq2user2_backpressure_cnt_decode;
    logic                  dfx_beq2user2_backpressure_cnt_sw_wr;
    logic                  dfx_beq2user2_backpressure_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_beq2user2_backpressure_cnt_q;

    assign dfx_beq2user2_backpressure_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h120));
    assign dfx_beq2user2_backpressure_cnt_sw_wr = sw_wr && dfx_beq2user2_backpressure_cnt_decode;
    assign dfx_beq2user2_backpressure_cnt_sw_rd = sw_rd && dfx_beq2user2_backpressure_cnt_decode;

    always_comb begin
        dfx_beq2user2_backpressure_cnt_q = '0;
        dfx_beq2user2_backpressure_cnt_q[63: 0] = dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_q;
    end

    // masked version of return data
    assign dfx_beq2user2_backpressure_cnt_rdata = dfx_beq2user2_backpressure_cnt_sw_rd ? dfx_beq2user2_backpressure_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_beq2user2_backpressure_cnt (wire)
    // ------------------------------------------------------------
    assign dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_anded = & dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_q;
    assign dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_ored  = | dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_q;
    assign dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_xored = ^ dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_q;

    // next hardware value
    assign dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_next = dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_wdata;
    assign dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_q = dfx_beq2user2_backpressure_cnt_dfx_beq2user2_backpressure_cnt_next;
            
        
    // ============================================================
    // Register: DFX_BEQ2USER3_BACKPRESSURE_CNT
    //    [63: 0] dfx_beq2user3_backpressure_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_beq2user3_backpressure_cnt_decode;
    logic                  dfx_beq2user3_backpressure_cnt_sw_wr;
    logic                  dfx_beq2user3_backpressure_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_beq2user3_backpressure_cnt_q;

    assign dfx_beq2user3_backpressure_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h128));
    assign dfx_beq2user3_backpressure_cnt_sw_wr = sw_wr && dfx_beq2user3_backpressure_cnt_decode;
    assign dfx_beq2user3_backpressure_cnt_sw_rd = sw_rd && dfx_beq2user3_backpressure_cnt_decode;

    always_comb begin
        dfx_beq2user3_backpressure_cnt_q = '0;
        dfx_beq2user3_backpressure_cnt_q[63: 0] = dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_q;
    end

    // masked version of return data
    assign dfx_beq2user3_backpressure_cnt_rdata = dfx_beq2user3_backpressure_cnt_sw_rd ? dfx_beq2user3_backpressure_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_beq2user3_backpressure_cnt (wire)
    // ------------------------------------------------------------
    assign dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_anded = & dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_q;
    assign dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_ored  = | dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_q;
    assign dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_xored = ^ dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_q;

    // next hardware value
    assign dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_next = dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_wdata;
    assign dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_q = dfx_beq2user3_backpressure_cnt_dfx_beq2user3_backpressure_cnt_next;
            
        
    // ============================================================
    // Register: DFX_USER2BEQ0_BACKPRESSURE_CNT
    //    [63: 0] dfx_user2beq0_backpressure_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_user2beq0_backpressure_cnt_decode;
    logic                  dfx_user2beq0_backpressure_cnt_sw_wr;
    logic                  dfx_user2beq0_backpressure_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_user2beq0_backpressure_cnt_q;

    assign dfx_user2beq0_backpressure_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h130));
    assign dfx_user2beq0_backpressure_cnt_sw_wr = sw_wr && dfx_user2beq0_backpressure_cnt_decode;
    assign dfx_user2beq0_backpressure_cnt_sw_rd = sw_rd && dfx_user2beq0_backpressure_cnt_decode;

    always_comb begin
        dfx_user2beq0_backpressure_cnt_q = '0;
        dfx_user2beq0_backpressure_cnt_q[63: 0] = dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_q;
    end

    // masked version of return data
    assign dfx_user2beq0_backpressure_cnt_rdata = dfx_user2beq0_backpressure_cnt_sw_rd ? dfx_user2beq0_backpressure_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_user2beq0_backpressure_cnt (wire)
    // ------------------------------------------------------------
    assign dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_anded = & dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_q;
    assign dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_ored  = | dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_q;
    assign dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_xored = ^ dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_q;

    // next hardware value
    assign dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_next = dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_wdata;
    assign dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_q = dfx_user2beq0_backpressure_cnt_dfx_user2beq0_backpressure_cnt_next;
            
        
    // ============================================================
    // Register: DFX_USER2BEQ1_BACKPRESSURE_CNT
    //    [63: 0] dfx_user2beq1_backpressure_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_user2beq1_backpressure_cnt_decode;
    logic                  dfx_user2beq1_backpressure_cnt_sw_wr;
    logic                  dfx_user2beq1_backpressure_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_user2beq1_backpressure_cnt_q;

    assign dfx_user2beq1_backpressure_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h138));
    assign dfx_user2beq1_backpressure_cnt_sw_wr = sw_wr && dfx_user2beq1_backpressure_cnt_decode;
    assign dfx_user2beq1_backpressure_cnt_sw_rd = sw_rd && dfx_user2beq1_backpressure_cnt_decode;

    always_comb begin
        dfx_user2beq1_backpressure_cnt_q = '0;
        dfx_user2beq1_backpressure_cnt_q[63: 0] = dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_q;
    end

    // masked version of return data
    assign dfx_user2beq1_backpressure_cnt_rdata = dfx_user2beq1_backpressure_cnt_sw_rd ? dfx_user2beq1_backpressure_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_user2beq1_backpressure_cnt (wire)
    // ------------------------------------------------------------
    assign dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_anded = & dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_q;
    assign dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_ored  = | dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_q;
    assign dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_xored = ^ dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_q;

    // next hardware value
    assign dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_next = dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_wdata;
    assign dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_q = dfx_user2beq1_backpressure_cnt_dfx_user2beq1_backpressure_cnt_next;
            
        
    // ============================================================
    // Register: DFX_USER2BEQ2_BACKPRESSURE_CNT
    //    [63: 0] dfx_user2beq2_backpressure_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_user2beq2_backpressure_cnt_decode;
    logic                  dfx_user2beq2_backpressure_cnt_sw_wr;
    logic                  dfx_user2beq2_backpressure_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_user2beq2_backpressure_cnt_q;

    assign dfx_user2beq2_backpressure_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h140));
    assign dfx_user2beq2_backpressure_cnt_sw_wr = sw_wr && dfx_user2beq2_backpressure_cnt_decode;
    assign dfx_user2beq2_backpressure_cnt_sw_rd = sw_rd && dfx_user2beq2_backpressure_cnt_decode;

    always_comb begin
        dfx_user2beq2_backpressure_cnt_q = '0;
        dfx_user2beq2_backpressure_cnt_q[63: 0] = dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_q;
    end

    // masked version of return data
    assign dfx_user2beq2_backpressure_cnt_rdata = dfx_user2beq2_backpressure_cnt_sw_rd ? dfx_user2beq2_backpressure_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_user2beq2_backpressure_cnt (wire)
    // ------------------------------------------------------------
    assign dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_anded = & dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_q;
    assign dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_ored  = | dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_q;
    assign dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_xored = ^ dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_q;

    // next hardware value
    assign dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_next = dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_wdata;
    assign dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_q = dfx_user2beq2_backpressure_cnt_dfx_user2beq2_backpressure_cnt_next;
            
        
    // ============================================================
    // Register: DFX_USER2BEQ3_BACKPRESSURE_CNT
    //    [63: 0] dfx_user2beq3_backpressure_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  dfx_user2beq3_backpressure_cnt_decode;
    logic                  dfx_user2beq3_backpressure_cnt_sw_wr;
    logic                  dfx_user2beq3_backpressure_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] dfx_user2beq3_backpressure_cnt_q;

    assign dfx_user2beq3_backpressure_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h148));
    assign dfx_user2beq3_backpressure_cnt_sw_wr = sw_wr && dfx_user2beq3_backpressure_cnt_decode;
    assign dfx_user2beq3_backpressure_cnt_sw_rd = sw_rd && dfx_user2beq3_backpressure_cnt_decode;

    always_comb begin
        dfx_user2beq3_backpressure_cnt_q = '0;
        dfx_user2beq3_backpressure_cnt_q[63: 0] = dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_q;
    end

    // masked version of return data
    assign dfx_user2beq3_backpressure_cnt_rdata = dfx_user2beq3_backpressure_cnt_sw_rd ? dfx_user2beq3_backpressure_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: dfx_user2beq3_backpressure_cnt (wire)
    // ------------------------------------------------------------
    assign dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_anded = & dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_q;
    assign dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_ored  = | dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_q;
    assign dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_xored = ^ dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_q;

    // next hardware value
    assign dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_next = dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_wdata;
    assign dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_q = dfx_user2beq3_backpressure_cnt_dfx_user2beq3_backpressure_cnt_next;
            
        
    // ============================================================
    // Register: RR_SCH_WEIGHT
    //    [ 7: 0]        rr_sch_weight: hw=r     sw=rw    reset=0x12
    // ============================================================
    logic                  rr_sch_weight_decode;
    logic                  rr_sch_weight_sw_wr;
    logic                  rr_sch_weight_sw_rd;
    logic [DATA_WIDTH-1:0] rr_sch_weight_q;

    assign rr_sch_weight_decode = (addr == (ADDR_OFFSET+'h0+'h800));
    assign rr_sch_weight_sw_wr = sw_wr && rr_sch_weight_decode;
    assign rr_sch_weight_sw_rd = sw_rd && rr_sch_weight_decode;

    always_comb begin
        rr_sch_weight_q = '0;
        rr_sch_weight_q[ 7: 0] = rr_sch_weight_rr_sch_weight_q;
    end

    // masked version of return data
    assign rr_sch_weight_rdata = rr_sch_weight_sw_rd ? rr_sch_weight_q : 'b0;

    // ------------------------------------------------------------
    // Field: rr_sch_weight
    // ------------------------------------------------------------
    assign rr_sch_weight_rr_sch_weight_anded = & rr_sch_weight_rr_sch_weight_q;
    assign rr_sch_weight_rr_sch_weight_ored  = | rr_sch_weight_rr_sch_weight_q;
    assign rr_sch_weight_rr_sch_weight_xored = ^ rr_sch_weight_rr_sch_weight_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        rr_sch_weight_rr_sch_weight_q <= 18;
    end else begin
        // Software write
        if (rr_sch_weight_sw_wr) begin
            rr_sch_weight_rr_sch_weight_q <=  sw_masked_data[ 7: 0] | (rr_sch_weight_rr_sch_weight_q & ~sw_mask[ 7: 0]);
        end
    end
            
        
    // ============================================================
    // Register: WRR_SCH_WEIGHT
    //    [15: 0]       wrr_sch_weight: hw=r     sw=rw    reset=0x2114
    // ============================================================
    logic                  wrr_sch_weight_decode;
    logic                  wrr_sch_weight_sw_wr;
    logic                  wrr_sch_weight_sw_rd;
    logic [DATA_WIDTH-1:0] wrr_sch_weight_q;

    assign wrr_sch_weight_decode = (addr == (ADDR_OFFSET+'h0+'h810));
    assign wrr_sch_weight_sw_wr = sw_wr && wrr_sch_weight_decode;
    assign wrr_sch_weight_sw_rd = sw_rd && wrr_sch_weight_decode;

    always_comb begin
        wrr_sch_weight_q = '0;
        wrr_sch_weight_q[15: 0] = wrr_sch_weight_wrr_sch_weight_q;
    end

    // masked version of return data
    assign wrr_sch_weight_rdata = wrr_sch_weight_sw_rd ? wrr_sch_weight_q : 'b0;

    // ------------------------------------------------------------
    // Field: wrr_sch_weight
    // ------------------------------------------------------------
    assign wrr_sch_weight_wrr_sch_weight_anded = & wrr_sch_weight_wrr_sch_weight_q;
    assign wrr_sch_weight_wrr_sch_weight_ored  = | wrr_sch_weight_wrr_sch_weight_q;
    assign wrr_sch_weight_wrr_sch_weight_xored = ^ wrr_sch_weight_wrr_sch_weight_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        wrr_sch_weight_wrr_sch_weight_q <= 8468;
    end else begin
        // Software write
        if (wrr_sch_weight_sw_wr) begin
            wrr_sch_weight_wrr_sch_weight_q <=  sw_masked_data[15: 0] | (wrr_sch_weight_wrr_sch_weight_q & ~sw_mask[15: 0]);
        end
    end

endmodule: beq_common_dfx
