// This file was autogenerated by PeakRDL-verilog
module reg_mgmt #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register VERSION
    input  logic                     [31: 0] version_version_wdata,          //! HW write data

    // Register GIT_HASH
    input  logic                     [31: 0] git_hash_git_hash_wdata,          //! HW write data

    // Register CHIP_VENDOR_ID
    input  logic                     [31: 0] chip_vendor_id_chip_vendor_id_wdata,          //! HW write data

    // Register TIMESTAMP
    input  logic                     [63: 0] timestamp_timestamp_wdata,          //! HW write data

    // Register PCIE_STATUS
    input  logic                     [31: 0] pcie_status_pcie_status_wdata,          //! HW write data

    // Register HOST_PCIE_STATUS
    input  logic                     [31: 0] host_pcie_status_host_pcie_status_wdata,          //! HW write data

    // Register PCIE_ERR_CNT
    input  logic                     [63: 0] pcie_err_cnt_pcie_err_cnt_wdata,          //! HW write data

    // Register HOST_PCIE_RST_TO_LINK_TIME_CNT
    input  logic                     [63: 0] host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_wdata,          //! HW write data

    // Register TEMP_SENSOR
    input  logic                     [31: 0] temp_sensor_temp_sensor_wdata,          //! HW write data

    // Register VOLTAGE_SENSOR
    input  logic                     [63: 0] voltage_sensor_voltage_sensor_wdata,          //! HW write data

    // Register SEU_STATUS_0
    input  logic                     [63: 0] seu_status_0_seu_status_0_wdata,          //! HW write data

    // Register SEU_STATUS_1
    input  logic                     [63: 0] seu_status_1_seu_status_1_wdata,          //! HW write data

    // Register CHIP_ID
    input  logic                     [63: 0] chip_id_chip_id_wdata,          //! HW write data

    // Register REG_IDX_TBL_STATUS
    input  logic                     [31: 0] reg_idx_tbl_status_reg_idx_tbl_status_wdata,          //! HW write data

    // Register REG_IDX_TBL_ERR
    input  logic                             reg_idx_tbl_err_reg_idx_tbl_err_we,             //! Control HW write (active high)
    input  logic                     [31: 0] reg_idx_tbl_err_reg_idx_tbl_err_wdata,          //! HW write data
    output logic                     [31: 0] reg_idx_tbl_err_reg_idx_tbl_err_q,              //! Current field value

    // Register EMR_ERR
    input  logic                     [ 0: 0] emr_err_emr_err_wdata,          //! HW write data

    // Register EMR_READ
    output logic                             emr_read_emr_read_swmod,          //! Indicates SW has modified this field
    output logic                     [ 0: 0] emr_read_emr_read_q,              //! Current field value

    // Register EMR_DATA_0_L
    input  logic                     [63: 0] emr_data_0_l_emr_data_0_l_wdata,          //! HW write data

    // Register EMR_DATA_0_H
    input  logic                     [63: 0] emr_data_0_h_emr_data_0_h_wdata,          //! HW write data

    // Register EMR_DATA_1_L
    input  logic                     [63: 0] emr_data_1_l_emr_data_1_l_wdata,          //! HW write data

    // Register EMR_DATA_1_H
    input  logic                     [63: 0] emr_data_1_h_emr_data_1_h_wdata,          //! HW write data

    // Register EMR_DATA_2_L
    input  logic                     [63: 0] emr_data_2_l_emr_data_2_l_wdata,          //! HW write data

    // Register EMR_DATA_2_H
    input  logic                     [63: 0] emr_data_2_h_emr_data_2_h_wdata,          //! HW write data

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [31: 0] version_version_q;
    logic                           [31: 0] version_version_next;
    logic                             version_version_anded;
    logic                             version_version_ored;
    logic                             version_version_xored;
    logic                           [31: 0] git_hash_git_hash_q;
    logic                           [31: 0] git_hash_git_hash_next;
    logic                             git_hash_git_hash_anded;
    logic                             git_hash_git_hash_ored;
    logic                             git_hash_git_hash_xored;
    logic                           [31: 0] chip_vendor_id_chip_vendor_id_q;
    logic                           [31: 0] chip_vendor_id_chip_vendor_id_next;
    logic                             chip_vendor_id_chip_vendor_id_anded;
    logic                             chip_vendor_id_chip_vendor_id_ored;
    logic                             chip_vendor_id_chip_vendor_id_xored;
    logic                           [63: 0] timestamp_timestamp_q;
    logic                           [63: 0] timestamp_timestamp_next;
    logic                             timestamp_timestamp_anded;
    logic                             timestamp_timestamp_ored;
    logic                             timestamp_timestamp_xored;
    logic                           [31: 0] pcie_status_pcie_status_q;
    logic                           [31: 0] pcie_status_pcie_status_next;
    logic                             pcie_status_pcie_status_anded;
    logic                             pcie_status_pcie_status_ored;
    logic                             pcie_status_pcie_status_xored;
    logic                           [31: 0] host_pcie_status_host_pcie_status_q;
    logic                           [31: 0] host_pcie_status_host_pcie_status_next;
    logic                             host_pcie_status_host_pcie_status_anded;
    logic                             host_pcie_status_host_pcie_status_ored;
    logic                             host_pcie_status_host_pcie_status_xored;
    logic                           [63: 0] pcie_err_cnt_pcie_err_cnt_q;
    logic                           [63: 0] pcie_err_cnt_pcie_err_cnt_next;
    logic                             pcie_err_cnt_pcie_err_cnt_anded;
    logic                             pcie_err_cnt_pcie_err_cnt_ored;
    logic                             pcie_err_cnt_pcie_err_cnt_xored;
    logic                           [63: 0] host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_q;
    logic                           [63: 0] host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_next;
    logic                             host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_anded;
    logic                             host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_ored;
    logic                             host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_xored;
    logic                           [31: 0] temp_sensor_temp_sensor_q;
    logic                           [31: 0] temp_sensor_temp_sensor_next;
    logic                             temp_sensor_temp_sensor_anded;
    logic                             temp_sensor_temp_sensor_ored;
    logic                             temp_sensor_temp_sensor_xored;
    logic                           [63: 0] voltage_sensor_voltage_sensor_q;
    logic                           [63: 0] voltage_sensor_voltage_sensor_next;
    logic                             voltage_sensor_voltage_sensor_anded;
    logic                             voltage_sensor_voltage_sensor_ored;
    logic                             voltage_sensor_voltage_sensor_xored;
    logic                           [63: 0] seu_status_0_seu_status_0_q;
    logic                           [63: 0] seu_status_0_seu_status_0_next;
    logic                             seu_status_0_seu_status_0_anded;
    logic                             seu_status_0_seu_status_0_ored;
    logic                             seu_status_0_seu_status_0_xored;
    logic                           [63: 0] seu_status_1_seu_status_1_q;
    logic                           [63: 0] seu_status_1_seu_status_1_next;
    logic                             seu_status_1_seu_status_1_anded;
    logic                             seu_status_1_seu_status_1_ored;
    logic                             seu_status_1_seu_status_1_xored;
    logic                           [63: 0] chip_id_chip_id_q;
    logic                           [63: 0] chip_id_chip_id_next;
    logic                             chip_id_chip_id_anded;
    logic                             chip_id_chip_id_ored;
    logic                             chip_id_chip_id_xored;
    logic                           [31: 0] reg_idx_tbl_status_reg_idx_tbl_status_q;
    logic                           [31: 0] reg_idx_tbl_status_reg_idx_tbl_status_next;
    logic                             reg_idx_tbl_status_reg_idx_tbl_status_anded;
    logic                             reg_idx_tbl_status_reg_idx_tbl_status_ored;
    logic                             reg_idx_tbl_status_reg_idx_tbl_status_xored;
    logic                           [31: 0] reg_idx_tbl_err_reg_idx_tbl_err_next;
    logic                             reg_idx_tbl_err_reg_idx_tbl_err_anded;
    logic                             reg_idx_tbl_err_reg_idx_tbl_err_ored;
    logic                             reg_idx_tbl_err_reg_idx_tbl_err_xored;
    logic                           [ 0: 0] emr_err_emr_err_q;
    logic                           [ 0: 0] emr_err_emr_err_next;
    logic                             emr_err_emr_err_anded;
    logic                             emr_err_emr_err_ored;
    logic                             emr_err_emr_err_xored;
    logic                           [ 0: 0] emr_read_emr_read_next;
    logic                             emr_read_emr_read_anded;
    logic                             emr_read_emr_read_ored;
    logic                             emr_read_emr_read_xored;
    logic                           [63: 0] emr_data_0_l_emr_data_0_l_q;
    logic                           [63: 0] emr_data_0_l_emr_data_0_l_next;
    logic                             emr_data_0_l_emr_data_0_l_anded;
    logic                             emr_data_0_l_emr_data_0_l_ored;
    logic                             emr_data_0_l_emr_data_0_l_xored;
    logic                           [63: 0] emr_data_0_h_emr_data_0_h_q;
    logic                           [63: 0] emr_data_0_h_emr_data_0_h_next;
    logic                             emr_data_0_h_emr_data_0_h_anded;
    logic                             emr_data_0_h_emr_data_0_h_ored;
    logic                             emr_data_0_h_emr_data_0_h_xored;
    logic                           [63: 0] emr_data_1_l_emr_data_1_l_q;
    logic                           [63: 0] emr_data_1_l_emr_data_1_l_next;
    logic                             emr_data_1_l_emr_data_1_l_anded;
    logic                             emr_data_1_l_emr_data_1_l_ored;
    logic                             emr_data_1_l_emr_data_1_l_xored;
    logic                           [63: 0] emr_data_1_h_emr_data_1_h_q;
    logic                           [63: 0] emr_data_1_h_emr_data_1_h_next;
    logic                             emr_data_1_h_emr_data_1_h_anded;
    logic                             emr_data_1_h_emr_data_1_h_ored;
    logic                             emr_data_1_h_emr_data_1_h_xored;
    logic                           [63: 0] emr_data_2_l_emr_data_2_l_q;
    logic                           [63: 0] emr_data_2_l_emr_data_2_l_next;
    logic                             emr_data_2_l_emr_data_2_l_anded;
    logic                             emr_data_2_l_emr_data_2_l_ored;
    logic                             emr_data_2_l_emr_data_2_l_xored;
    logic                           [63: 0] emr_data_2_h_emr_data_2_h_q;
    logic                           [63: 0] emr_data_2_h_emr_data_2_h_next;
    logic                             emr_data_2_h_emr_data_2_h_anded;
    logic                             emr_data_2_h_emr_data_2_h_ored;
    logic                             emr_data_2_h_emr_data_2_h_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [ADDR_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] version_rdata;
    logic                     [DATA_WIDTH-1:0] git_hash_rdata;
    logic                     [DATA_WIDTH-1:0] chip_vendor_id_rdata;
    logic                     [DATA_WIDTH-1:0] timestamp_rdata;
    logic                     [DATA_WIDTH-1:0] pcie_status_rdata;
    logic                     [DATA_WIDTH-1:0] host_pcie_status_rdata;
    logic                     [DATA_WIDTH-1:0] pcie_err_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] host_pcie_rst_to_link_time_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] temp_sensor_rdata;
    logic                     [DATA_WIDTH-1:0] voltage_sensor_rdata;
    logic                     [DATA_WIDTH-1:0] seu_status_0_rdata;
    logic                     [DATA_WIDTH-1:0] seu_status_1_rdata;
    logic                     [DATA_WIDTH-1:0] chip_id_rdata;
    logic                     [DATA_WIDTH-1:0] reg_idx_tbl_status_rdata;
    logic                     [DATA_WIDTH-1:0] reg_idx_tbl_err_rdata;
    logic                     [DATA_WIDTH-1:0] emr_err_rdata;
    logic                     [DATA_WIDTH-1:0] emr_read_rdata;
    logic                     [DATA_WIDTH-1:0] emr_data_0_l_rdata;
    logic                     [DATA_WIDTH-1:0] emr_data_0_h_rdata;
    logic                     [DATA_WIDTH-1:0] emr_data_1_l_rdata;
    logic                     [DATA_WIDTH-1:0] emr_data_1_h_rdata;
    logic                     [DATA_WIDTH-1:0] emr_data_2_l_rdata;
    logic                     [DATA_WIDTH-1:0] emr_data_2_h_rdata;

    assign sw_rdata = // or of each register return (masked)
                   version_rdata | 
                   git_hash_rdata | 
                   chip_vendor_id_rdata | 
                   timestamp_rdata | 
                   pcie_status_rdata | 
                   host_pcie_status_rdata | 
                   pcie_err_cnt_rdata | 
                   host_pcie_rst_to_link_time_cnt_rdata | 
                   temp_sensor_rdata | 
                   voltage_sensor_rdata | 
                   seu_status_0_rdata | 
                   seu_status_1_rdata | 
                   chip_id_rdata | 
                   reg_idx_tbl_status_rdata | 
                   reg_idx_tbl_err_rdata | 
                   emr_err_rdata | 
                   emr_read_rdata | 
                   emr_data_0_l_rdata | 
                   emr_data_0_h_rdata | 
                   emr_data_1_l_rdata | 
                   emr_data_1_h_rdata | 
                   emr_data_2_l_rdata | 
                   emr_data_2_h_rdata;
            
        
    // ============================================================
    // Register: VERSION
    //    [31: 0]              version: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  version_decode;
    logic                  version_sw_wr;
    logic                  version_sw_rd;
    logic [DATA_WIDTH-1:0] version_q;

    assign version_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign version_sw_wr = sw_wr && version_decode;
    assign version_sw_rd = sw_rd && version_decode;

    always_comb begin
        version_q = '0;
        version_q[31: 0] = version_version_q;
    end

    // masked version of return data
    assign version_rdata = version_sw_rd ? version_q : 'b0;

    // ------------------------------------------------------------
    // Field: version (wire)
    // ------------------------------------------------------------
    assign version_version_anded = & version_version_q;
    assign version_version_ored  = | version_version_q;
    assign version_version_xored = ^ version_version_q;

    // next hardware value
    assign version_version_next = version_version_wdata;
    assign version_version_q = version_version_next;
            
        
    // ============================================================
    // Register: GIT_HASH
    //    [31: 0]             git_hash: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  git_hash_decode;
    logic                  git_hash_sw_wr;
    logic                  git_hash_sw_rd;
    logic [DATA_WIDTH-1:0] git_hash_q;

    assign git_hash_decode = (addr == (ADDR_OFFSET+'h0+'h8));
    assign git_hash_sw_wr = sw_wr && git_hash_decode;
    assign git_hash_sw_rd = sw_rd && git_hash_decode;

    always_comb begin
        git_hash_q = '0;
        git_hash_q[31: 0] = git_hash_git_hash_q;
    end

    // masked version of return data
    assign git_hash_rdata = git_hash_sw_rd ? git_hash_q : 'b0;

    // ------------------------------------------------------------
    // Field: git_hash (wire)
    // ------------------------------------------------------------
    assign git_hash_git_hash_anded = & git_hash_git_hash_q;
    assign git_hash_git_hash_ored  = | git_hash_git_hash_q;
    assign git_hash_git_hash_xored = ^ git_hash_git_hash_q;

    // next hardware value
    assign git_hash_git_hash_next = git_hash_git_hash_wdata;
    assign git_hash_git_hash_q = git_hash_git_hash_next;
            
        
    // ============================================================
    // Register: CHIP_VENDOR_ID
    //    [31: 0]       chip_vendor_id: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  chip_vendor_id_decode;
    logic                  chip_vendor_id_sw_wr;
    logic                  chip_vendor_id_sw_rd;
    logic [DATA_WIDTH-1:0] chip_vendor_id_q;

    assign chip_vendor_id_decode = (addr == (ADDR_OFFSET+'h0+'h10));
    assign chip_vendor_id_sw_wr = sw_wr && chip_vendor_id_decode;
    assign chip_vendor_id_sw_rd = sw_rd && chip_vendor_id_decode;

    always_comb begin
        chip_vendor_id_q = '0;
        chip_vendor_id_q[31: 0] = chip_vendor_id_chip_vendor_id_q;
    end

    // masked version of return data
    assign chip_vendor_id_rdata = chip_vendor_id_sw_rd ? chip_vendor_id_q : 'b0;

    // ------------------------------------------------------------
    // Field: chip_vendor_id (wire)
    // ------------------------------------------------------------
    assign chip_vendor_id_chip_vendor_id_anded = & chip_vendor_id_chip_vendor_id_q;
    assign chip_vendor_id_chip_vendor_id_ored  = | chip_vendor_id_chip_vendor_id_q;
    assign chip_vendor_id_chip_vendor_id_xored = ^ chip_vendor_id_chip_vendor_id_q;

    // next hardware value
    assign chip_vendor_id_chip_vendor_id_next = chip_vendor_id_chip_vendor_id_wdata;
    assign chip_vendor_id_chip_vendor_id_q = chip_vendor_id_chip_vendor_id_next;
            
        
    // ============================================================
    // Register: TIMESTAMP
    //    [63: 0]            timestamp: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  timestamp_decode;
    logic                  timestamp_sw_wr;
    logic                  timestamp_sw_rd;
    logic [DATA_WIDTH-1:0] timestamp_q;

    assign timestamp_decode = (addr == (ADDR_OFFSET+'h0+'h18));
    assign timestamp_sw_wr = sw_wr && timestamp_decode;
    assign timestamp_sw_rd = sw_rd && timestamp_decode;

    always_comb begin
        timestamp_q = '0;
        timestamp_q[63: 0] = timestamp_timestamp_q;
    end

    // masked version of return data
    assign timestamp_rdata = timestamp_sw_rd ? timestamp_q : 'b0;

    // ------------------------------------------------------------
    // Field: timestamp (wire)
    // ------------------------------------------------------------
    assign timestamp_timestamp_anded = & timestamp_timestamp_q;
    assign timestamp_timestamp_ored  = | timestamp_timestamp_q;
    assign timestamp_timestamp_xored = ^ timestamp_timestamp_q;

    // next hardware value
    assign timestamp_timestamp_next = timestamp_timestamp_wdata;
    assign timestamp_timestamp_q = timestamp_timestamp_next;
            
        
    // ============================================================
    // Register: PCIE_STATUS
    //    [31: 0]          pcie_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  pcie_status_decode;
    logic                  pcie_status_sw_wr;
    logic                  pcie_status_sw_rd;
    logic [DATA_WIDTH-1:0] pcie_status_q;

    assign pcie_status_decode = (addr == (ADDR_OFFSET+'h0+'h40));
    assign pcie_status_sw_wr = sw_wr && pcie_status_decode;
    assign pcie_status_sw_rd = sw_rd && pcie_status_decode;

    always_comb begin
        pcie_status_q = '0;
        pcie_status_q[31: 0] = pcie_status_pcie_status_q;
    end

    // masked version of return data
    assign pcie_status_rdata = pcie_status_sw_rd ? pcie_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: pcie_status (wire)
    // ------------------------------------------------------------
    assign pcie_status_pcie_status_anded = & pcie_status_pcie_status_q;
    assign pcie_status_pcie_status_ored  = | pcie_status_pcie_status_q;
    assign pcie_status_pcie_status_xored = ^ pcie_status_pcie_status_q;

    // next hardware value
    assign pcie_status_pcie_status_next = pcie_status_pcie_status_wdata;
    assign pcie_status_pcie_status_q = pcie_status_pcie_status_next;
            
        
    // ============================================================
    // Register: HOST_PCIE_STATUS
    //    [31: 0]     host_pcie_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  host_pcie_status_decode;
    logic                  host_pcie_status_sw_wr;
    logic                  host_pcie_status_sw_rd;
    logic [DATA_WIDTH-1:0] host_pcie_status_q;

    assign host_pcie_status_decode = (addr == (ADDR_OFFSET+'h0+'h48));
    assign host_pcie_status_sw_wr = sw_wr && host_pcie_status_decode;
    assign host_pcie_status_sw_rd = sw_rd && host_pcie_status_decode;

    always_comb begin
        host_pcie_status_q = '0;
        host_pcie_status_q[31: 0] = host_pcie_status_host_pcie_status_q;
    end

    // masked version of return data
    assign host_pcie_status_rdata = host_pcie_status_sw_rd ? host_pcie_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: host_pcie_status (wire)
    // ------------------------------------------------------------
    assign host_pcie_status_host_pcie_status_anded = & host_pcie_status_host_pcie_status_q;
    assign host_pcie_status_host_pcie_status_ored  = | host_pcie_status_host_pcie_status_q;
    assign host_pcie_status_host_pcie_status_xored = ^ host_pcie_status_host_pcie_status_q;

    // next hardware value
    assign host_pcie_status_host_pcie_status_next = host_pcie_status_host_pcie_status_wdata;
    assign host_pcie_status_host_pcie_status_q = host_pcie_status_host_pcie_status_next;
            
        
    // ============================================================
    // Register: PCIE_ERR_CNT
    //    [63: 0]         pcie_err_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  pcie_err_cnt_decode;
    logic                  pcie_err_cnt_sw_wr;
    logic                  pcie_err_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] pcie_err_cnt_q;

    assign pcie_err_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h50));
    assign pcie_err_cnt_sw_wr = sw_wr && pcie_err_cnt_decode;
    assign pcie_err_cnt_sw_rd = sw_rd && pcie_err_cnt_decode;

    always_comb begin
        pcie_err_cnt_q = '0;
        pcie_err_cnt_q[63: 0] = pcie_err_cnt_pcie_err_cnt_q;
    end

    // masked version of return data
    assign pcie_err_cnt_rdata = pcie_err_cnt_sw_rd ? pcie_err_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: pcie_err_cnt (wire)
    // ------------------------------------------------------------
    assign pcie_err_cnt_pcie_err_cnt_anded = & pcie_err_cnt_pcie_err_cnt_q;
    assign pcie_err_cnt_pcie_err_cnt_ored  = | pcie_err_cnt_pcie_err_cnt_q;
    assign pcie_err_cnt_pcie_err_cnt_xored = ^ pcie_err_cnt_pcie_err_cnt_q;

    // next hardware value
    assign pcie_err_cnt_pcie_err_cnt_next = pcie_err_cnt_pcie_err_cnt_wdata;
    assign pcie_err_cnt_pcie_err_cnt_q = pcie_err_cnt_pcie_err_cnt_next;
            
        
    // ============================================================
    // Register: HOST_PCIE_RST_TO_LINK_TIME_CNT
    //    [63: 0] host_pcie_rst_to_link_time_cnt: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  host_pcie_rst_to_link_time_cnt_decode;
    logic                  host_pcie_rst_to_link_time_cnt_sw_wr;
    logic                  host_pcie_rst_to_link_time_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] host_pcie_rst_to_link_time_cnt_q;

    assign host_pcie_rst_to_link_time_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h58));
    assign host_pcie_rst_to_link_time_cnt_sw_wr = sw_wr && host_pcie_rst_to_link_time_cnt_decode;
    assign host_pcie_rst_to_link_time_cnt_sw_rd = sw_rd && host_pcie_rst_to_link_time_cnt_decode;

    always_comb begin
        host_pcie_rst_to_link_time_cnt_q = '0;
        host_pcie_rst_to_link_time_cnt_q[63: 0] = host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_q;
    end

    // masked version of return data
    assign host_pcie_rst_to_link_time_cnt_rdata = host_pcie_rst_to_link_time_cnt_sw_rd ? host_pcie_rst_to_link_time_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: host_pcie_rst_to_link_time_cnt (wire)
    // ------------------------------------------------------------
    assign host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_anded = & host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_q;
    assign host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_ored  = | host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_q;
    assign host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_xored = ^ host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_q;

    // next hardware value
    assign host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_next = host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_wdata;
    assign host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_q = host_pcie_rst_to_link_time_cnt_host_pcie_rst_to_link_time_cnt_next;
            
        
    // ============================================================
    // Register: TEMP_SENSOR
    //    [31: 0]          temp_sensor: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  temp_sensor_decode;
    logic                  temp_sensor_sw_wr;
    logic                  temp_sensor_sw_rd;
    logic [DATA_WIDTH-1:0] temp_sensor_q;

    assign temp_sensor_decode = (addr == (ADDR_OFFSET+'h0+'h80));
    assign temp_sensor_sw_wr = sw_wr && temp_sensor_decode;
    assign temp_sensor_sw_rd = sw_rd && temp_sensor_decode;

    always_comb begin
        temp_sensor_q = '0;
        temp_sensor_q[31: 0] = temp_sensor_temp_sensor_q;
    end

    // masked version of return data
    assign temp_sensor_rdata = temp_sensor_sw_rd ? temp_sensor_q : 'b0;

    // ------------------------------------------------------------
    // Field: temp_sensor (wire)
    // ------------------------------------------------------------
    assign temp_sensor_temp_sensor_anded = & temp_sensor_temp_sensor_q;
    assign temp_sensor_temp_sensor_ored  = | temp_sensor_temp_sensor_q;
    assign temp_sensor_temp_sensor_xored = ^ temp_sensor_temp_sensor_q;

    // next hardware value
    assign temp_sensor_temp_sensor_next = temp_sensor_temp_sensor_wdata;
    assign temp_sensor_temp_sensor_q = temp_sensor_temp_sensor_next;
            
        
    // ============================================================
    // Register: VOLTAGE_SENSOR
    //    [63: 0]       voltage_sensor: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  voltage_sensor_decode;
    logic                  voltage_sensor_sw_wr;
    logic                  voltage_sensor_sw_rd;
    logic [DATA_WIDTH-1:0] voltage_sensor_q;

    assign voltage_sensor_decode = (addr == (ADDR_OFFSET+'h0+'h90));
    assign voltage_sensor_sw_wr = sw_wr && voltage_sensor_decode;
    assign voltage_sensor_sw_rd = sw_rd && voltage_sensor_decode;

    always_comb begin
        voltage_sensor_q = '0;
        voltage_sensor_q[63: 0] = voltage_sensor_voltage_sensor_q;
    end

    // masked version of return data
    assign voltage_sensor_rdata = voltage_sensor_sw_rd ? voltage_sensor_q : 'b0;

    // ------------------------------------------------------------
    // Field: voltage_sensor (wire)
    // ------------------------------------------------------------
    assign voltage_sensor_voltage_sensor_anded = & voltage_sensor_voltage_sensor_q;
    assign voltage_sensor_voltage_sensor_ored  = | voltage_sensor_voltage_sensor_q;
    assign voltage_sensor_voltage_sensor_xored = ^ voltage_sensor_voltage_sensor_q;

    // next hardware value
    assign voltage_sensor_voltage_sensor_next = voltage_sensor_voltage_sensor_wdata;
    assign voltage_sensor_voltage_sensor_q = voltage_sensor_voltage_sensor_next;
            
        
    // ============================================================
    // Register: SEU_STATUS_0
    //    [63: 0]         seu_status_0: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  seu_status_0_decode;
    logic                  seu_status_0_sw_wr;
    logic                  seu_status_0_sw_rd;
    logic [DATA_WIDTH-1:0] seu_status_0_q;

    assign seu_status_0_decode = (addr == (ADDR_OFFSET+'h0+'h100));
    assign seu_status_0_sw_wr = sw_wr && seu_status_0_decode;
    assign seu_status_0_sw_rd = sw_rd && seu_status_0_decode;

    always_comb begin
        seu_status_0_q = '0;
        seu_status_0_q[63: 0] = seu_status_0_seu_status_0_q;
    end

    // masked version of return data
    assign seu_status_0_rdata = seu_status_0_sw_rd ? seu_status_0_q : 'b0;

    // ------------------------------------------------------------
    // Field: seu_status_0 (wire)
    // ------------------------------------------------------------
    assign seu_status_0_seu_status_0_anded = & seu_status_0_seu_status_0_q;
    assign seu_status_0_seu_status_0_ored  = | seu_status_0_seu_status_0_q;
    assign seu_status_0_seu_status_0_xored = ^ seu_status_0_seu_status_0_q;

    // next hardware value
    assign seu_status_0_seu_status_0_next = seu_status_0_seu_status_0_wdata;
    assign seu_status_0_seu_status_0_q = seu_status_0_seu_status_0_next;
            
        
    // ============================================================
    // Register: SEU_STATUS_1
    //    [63: 0]         seu_status_1: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  seu_status_1_decode;
    logic                  seu_status_1_sw_wr;
    logic                  seu_status_1_sw_rd;
    logic [DATA_WIDTH-1:0] seu_status_1_q;

    assign seu_status_1_decode = (addr == (ADDR_OFFSET+'h0+'h108));
    assign seu_status_1_sw_wr = sw_wr && seu_status_1_decode;
    assign seu_status_1_sw_rd = sw_rd && seu_status_1_decode;

    always_comb begin
        seu_status_1_q = '0;
        seu_status_1_q[63: 0] = seu_status_1_seu_status_1_q;
    end

    // masked version of return data
    assign seu_status_1_rdata = seu_status_1_sw_rd ? seu_status_1_q : 'b0;

    // ------------------------------------------------------------
    // Field: seu_status_1 (wire)
    // ------------------------------------------------------------
    assign seu_status_1_seu_status_1_anded = & seu_status_1_seu_status_1_q;
    assign seu_status_1_seu_status_1_ored  = | seu_status_1_seu_status_1_q;
    assign seu_status_1_seu_status_1_xored = ^ seu_status_1_seu_status_1_q;

    // next hardware value
    assign seu_status_1_seu_status_1_next = seu_status_1_seu_status_1_wdata;
    assign seu_status_1_seu_status_1_q = seu_status_1_seu_status_1_next;
            
        
    // ============================================================
    // Register: CHIP_ID
    //    [63: 0]              chip_id: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  chip_id_decode;
    logic                  chip_id_sw_wr;
    logic                  chip_id_sw_rd;
    logic [DATA_WIDTH-1:0] chip_id_q;

    assign chip_id_decode = (addr == (ADDR_OFFSET+'h0+'h120));
    assign chip_id_sw_wr = sw_wr && chip_id_decode;
    assign chip_id_sw_rd = sw_rd && chip_id_decode;

    always_comb begin
        chip_id_q = '0;
        chip_id_q[63: 0] = chip_id_chip_id_q;
    end

    // masked version of return data
    assign chip_id_rdata = chip_id_sw_rd ? chip_id_q : 'b0;

    // ------------------------------------------------------------
    // Field: chip_id (wire)
    // ------------------------------------------------------------
    assign chip_id_chip_id_anded = & chip_id_chip_id_q;
    assign chip_id_chip_id_ored  = | chip_id_chip_id_q;
    assign chip_id_chip_id_xored = ^ chip_id_chip_id_q;

    // next hardware value
    assign chip_id_chip_id_next = chip_id_chip_id_wdata;
    assign chip_id_chip_id_q = chip_id_chip_id_next;
            
        
    // ============================================================
    // Register: REG_IDX_TBL_STATUS
    //    [31: 0]   reg_idx_tbl_status: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  reg_idx_tbl_status_decode;
    logic                  reg_idx_tbl_status_sw_wr;
    logic                  reg_idx_tbl_status_sw_rd;
    logic [DATA_WIDTH-1:0] reg_idx_tbl_status_q;

    assign reg_idx_tbl_status_decode = (addr == (ADDR_OFFSET+'h0+'h130));
    assign reg_idx_tbl_status_sw_wr = sw_wr && reg_idx_tbl_status_decode;
    assign reg_idx_tbl_status_sw_rd = sw_rd && reg_idx_tbl_status_decode;

    always_comb begin
        reg_idx_tbl_status_q = '0;
        reg_idx_tbl_status_q[31: 0] = reg_idx_tbl_status_reg_idx_tbl_status_q;
    end

    // masked version of return data
    assign reg_idx_tbl_status_rdata = reg_idx_tbl_status_sw_rd ? reg_idx_tbl_status_q : 'b0;

    // ------------------------------------------------------------
    // Field: reg_idx_tbl_status (wire)
    // ------------------------------------------------------------
    assign reg_idx_tbl_status_reg_idx_tbl_status_anded = & reg_idx_tbl_status_reg_idx_tbl_status_q;
    assign reg_idx_tbl_status_reg_idx_tbl_status_ored  = | reg_idx_tbl_status_reg_idx_tbl_status_q;
    assign reg_idx_tbl_status_reg_idx_tbl_status_xored = ^ reg_idx_tbl_status_reg_idx_tbl_status_q;

    // next hardware value
    assign reg_idx_tbl_status_reg_idx_tbl_status_next = reg_idx_tbl_status_reg_idx_tbl_status_wdata;
    assign reg_idx_tbl_status_reg_idx_tbl_status_q = reg_idx_tbl_status_reg_idx_tbl_status_next;
            
        
    // ============================================================
    // Register: REG_IDX_TBL_ERR
    //    [31: 0]      reg_idx_tbl_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  reg_idx_tbl_err_decode;
    logic                  reg_idx_tbl_err_sw_wr;
    logic                  reg_idx_tbl_err_sw_rd;
    logic [DATA_WIDTH-1:0] reg_idx_tbl_err_q;

    assign reg_idx_tbl_err_decode = (addr == (ADDR_OFFSET+'h0+'h138));
    assign reg_idx_tbl_err_sw_wr = sw_wr && reg_idx_tbl_err_decode;
    assign reg_idx_tbl_err_sw_rd = sw_rd && reg_idx_tbl_err_decode;

    always_comb begin
        reg_idx_tbl_err_q = '0;
        reg_idx_tbl_err_q[31: 0] = reg_idx_tbl_err_reg_idx_tbl_err_q;
    end

    // masked version of return data
    assign reg_idx_tbl_err_rdata = reg_idx_tbl_err_sw_rd ? reg_idx_tbl_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: reg_idx_tbl_err
    // ------------------------------------------------------------
    assign reg_idx_tbl_err_reg_idx_tbl_err_anded = & reg_idx_tbl_err_reg_idx_tbl_err_q;
    assign reg_idx_tbl_err_reg_idx_tbl_err_ored  = | reg_idx_tbl_err_reg_idx_tbl_err_q;
    assign reg_idx_tbl_err_reg_idx_tbl_err_xored = ^ reg_idx_tbl_err_reg_idx_tbl_err_q;

    // next hardware value
    assign reg_idx_tbl_err_reg_idx_tbl_err_next = reg_idx_tbl_err_reg_idx_tbl_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        reg_idx_tbl_err_reg_idx_tbl_err_q <= 0;
    end else begin
        // Hardware Write
        if (reg_idx_tbl_err_reg_idx_tbl_err_we) begin
            reg_idx_tbl_err_reg_idx_tbl_err_q <= reg_idx_tbl_err_reg_idx_tbl_err_next;
        end
        // Software write
        else if (reg_idx_tbl_err_sw_wr) begin
            reg_idx_tbl_err_reg_idx_tbl_err_q <= ~sw_masked_data[31: 0] &  reg_idx_tbl_err_reg_idx_tbl_err_q;
        end
    end
            
        
    // ============================================================
    // Register: EMR_ERR
    //    [ 0: 0]              emr_err: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emr_err_decode;
    logic                  emr_err_sw_wr;
    logic                  emr_err_sw_rd;
    logic [DATA_WIDTH-1:0] emr_err_q;

    assign emr_err_decode = (addr == (ADDR_OFFSET+'h0+'h140));
    assign emr_err_sw_wr = sw_wr && emr_err_decode;
    assign emr_err_sw_rd = sw_rd && emr_err_decode;

    always_comb begin
        emr_err_q = '0;
        emr_err_q[ 0: 0] = emr_err_emr_err_q;
    end

    // masked version of return data
    assign emr_err_rdata = emr_err_sw_rd ? emr_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: emr_err (wire)
    // ------------------------------------------------------------
    assign emr_err_emr_err_anded = & emr_err_emr_err_q;
    assign emr_err_emr_err_ored  = | emr_err_emr_err_q;
    assign emr_err_emr_err_xored = ^ emr_err_emr_err_q;

    // next hardware value
    assign emr_err_emr_err_next = emr_err_emr_err_wdata;
    assign emr_err_emr_err_q = emr_err_emr_err_next;
            
        
    // ============================================================
    // Register: EMR_READ
    //    [ 0: 0]             emr_read: hw=r     sw=rw    reset=0x0
    // ============================================================
    logic                  emr_read_decode;
    logic                  emr_read_sw_wr;
    logic                  emr_read_sw_rd;
    logic [DATA_WIDTH-1:0] emr_read_q;

    assign emr_read_decode = (addr == (ADDR_OFFSET+'h0+'h148));
    assign emr_read_sw_wr = sw_wr && emr_read_decode;
    assign emr_read_sw_rd = sw_rd && emr_read_decode;

    always_comb begin
        emr_read_q = '0;
        emr_read_q[ 0: 0] = emr_read_emr_read_q;
    end

    // masked version of return data
    assign emr_read_rdata = emr_read_sw_rd ? emr_read_q : 'b0;

    // ------------------------------------------------------------
    // Field: emr_read
    // ------------------------------------------------------------
    assign emr_read_emr_read_anded = & emr_read_emr_read_q;
    assign emr_read_emr_read_ored  = | emr_read_emr_read_q;
    assign emr_read_emr_read_xored = ^ emr_read_emr_read_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        emr_read_emr_read_q <= 0;
        emr_read_emr_read_swmod <= 1'b0;
    end else begin
        emr_read_emr_read_swmod <= 1'b0;
        // Software write
        if (emr_read_sw_wr) begin
            emr_read_emr_read_swmod <= 1'b1;
            emr_read_emr_read_q <=  sw_masked_data[ 0: 0] | (emr_read_emr_read_q & ~sw_mask[ 0: 0]);
        end
    end
            
        
    // ============================================================
    // Register: EMR_DATA_0_L
    //    [63: 0]         emr_data_0_l: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emr_data_0_l_decode;
    logic                  emr_data_0_l_sw_wr;
    logic                  emr_data_0_l_sw_rd;
    logic [DATA_WIDTH-1:0] emr_data_0_l_q;

    assign emr_data_0_l_decode = (addr == (ADDR_OFFSET+'h0+'h150));
    assign emr_data_0_l_sw_wr = sw_wr && emr_data_0_l_decode;
    assign emr_data_0_l_sw_rd = sw_rd && emr_data_0_l_decode;

    always_comb begin
        emr_data_0_l_q = '0;
        emr_data_0_l_q[63: 0] = emr_data_0_l_emr_data_0_l_q;
    end

    // masked version of return data
    assign emr_data_0_l_rdata = emr_data_0_l_sw_rd ? emr_data_0_l_q : 'b0;

    // ------------------------------------------------------------
    // Field: emr_data_0_l (wire)
    // ------------------------------------------------------------
    assign emr_data_0_l_emr_data_0_l_anded = & emr_data_0_l_emr_data_0_l_q;
    assign emr_data_0_l_emr_data_0_l_ored  = | emr_data_0_l_emr_data_0_l_q;
    assign emr_data_0_l_emr_data_0_l_xored = ^ emr_data_0_l_emr_data_0_l_q;

    // next hardware value
    assign emr_data_0_l_emr_data_0_l_next = emr_data_0_l_emr_data_0_l_wdata;
    assign emr_data_0_l_emr_data_0_l_q = emr_data_0_l_emr_data_0_l_next;
            
        
    // ============================================================
    // Register: EMR_DATA_0_H
    //    [63: 0]         emr_data_0_h: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emr_data_0_h_decode;
    logic                  emr_data_0_h_sw_wr;
    logic                  emr_data_0_h_sw_rd;
    logic [DATA_WIDTH-1:0] emr_data_0_h_q;

    assign emr_data_0_h_decode = (addr == (ADDR_OFFSET+'h0+'h158));
    assign emr_data_0_h_sw_wr = sw_wr && emr_data_0_h_decode;
    assign emr_data_0_h_sw_rd = sw_rd && emr_data_0_h_decode;

    always_comb begin
        emr_data_0_h_q = '0;
        emr_data_0_h_q[63: 0] = emr_data_0_h_emr_data_0_h_q;
    end

    // masked version of return data
    assign emr_data_0_h_rdata = emr_data_0_h_sw_rd ? emr_data_0_h_q : 'b0;

    // ------------------------------------------------------------
    // Field: emr_data_0_h (wire)
    // ------------------------------------------------------------
    assign emr_data_0_h_emr_data_0_h_anded = & emr_data_0_h_emr_data_0_h_q;
    assign emr_data_0_h_emr_data_0_h_ored  = | emr_data_0_h_emr_data_0_h_q;
    assign emr_data_0_h_emr_data_0_h_xored = ^ emr_data_0_h_emr_data_0_h_q;

    // next hardware value
    assign emr_data_0_h_emr_data_0_h_next = emr_data_0_h_emr_data_0_h_wdata;
    assign emr_data_0_h_emr_data_0_h_q = emr_data_0_h_emr_data_0_h_next;
            
        
    // ============================================================
    // Register: EMR_DATA_1_L
    //    [63: 0]         emr_data_1_l: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emr_data_1_l_decode;
    logic                  emr_data_1_l_sw_wr;
    logic                  emr_data_1_l_sw_rd;
    logic [DATA_WIDTH-1:0] emr_data_1_l_q;

    assign emr_data_1_l_decode = (addr == (ADDR_OFFSET+'h0+'h160));
    assign emr_data_1_l_sw_wr = sw_wr && emr_data_1_l_decode;
    assign emr_data_1_l_sw_rd = sw_rd && emr_data_1_l_decode;

    always_comb begin
        emr_data_1_l_q = '0;
        emr_data_1_l_q[63: 0] = emr_data_1_l_emr_data_1_l_q;
    end

    // masked version of return data
    assign emr_data_1_l_rdata = emr_data_1_l_sw_rd ? emr_data_1_l_q : 'b0;

    // ------------------------------------------------------------
    // Field: emr_data_1_l (wire)
    // ------------------------------------------------------------
    assign emr_data_1_l_emr_data_1_l_anded = & emr_data_1_l_emr_data_1_l_q;
    assign emr_data_1_l_emr_data_1_l_ored  = | emr_data_1_l_emr_data_1_l_q;
    assign emr_data_1_l_emr_data_1_l_xored = ^ emr_data_1_l_emr_data_1_l_q;

    // next hardware value
    assign emr_data_1_l_emr_data_1_l_next = emr_data_1_l_emr_data_1_l_wdata;
    assign emr_data_1_l_emr_data_1_l_q = emr_data_1_l_emr_data_1_l_next;
            
        
    // ============================================================
    // Register: EMR_DATA_1_H
    //    [63: 0]         emr_data_1_h: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emr_data_1_h_decode;
    logic                  emr_data_1_h_sw_wr;
    logic                  emr_data_1_h_sw_rd;
    logic [DATA_WIDTH-1:0] emr_data_1_h_q;

    assign emr_data_1_h_decode = (addr == (ADDR_OFFSET+'h0+'h168));
    assign emr_data_1_h_sw_wr = sw_wr && emr_data_1_h_decode;
    assign emr_data_1_h_sw_rd = sw_rd && emr_data_1_h_decode;

    always_comb begin
        emr_data_1_h_q = '0;
        emr_data_1_h_q[63: 0] = emr_data_1_h_emr_data_1_h_q;
    end

    // masked version of return data
    assign emr_data_1_h_rdata = emr_data_1_h_sw_rd ? emr_data_1_h_q : 'b0;

    // ------------------------------------------------------------
    // Field: emr_data_1_h (wire)
    // ------------------------------------------------------------
    assign emr_data_1_h_emr_data_1_h_anded = & emr_data_1_h_emr_data_1_h_q;
    assign emr_data_1_h_emr_data_1_h_ored  = | emr_data_1_h_emr_data_1_h_q;
    assign emr_data_1_h_emr_data_1_h_xored = ^ emr_data_1_h_emr_data_1_h_q;

    // next hardware value
    assign emr_data_1_h_emr_data_1_h_next = emr_data_1_h_emr_data_1_h_wdata;
    assign emr_data_1_h_emr_data_1_h_q = emr_data_1_h_emr_data_1_h_next;
            
        
    // ============================================================
    // Register: EMR_DATA_2_L
    //    [63: 0]         emr_data_2_l: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emr_data_2_l_decode;
    logic                  emr_data_2_l_sw_wr;
    logic                  emr_data_2_l_sw_rd;
    logic [DATA_WIDTH-1:0] emr_data_2_l_q;

    assign emr_data_2_l_decode = (addr == (ADDR_OFFSET+'h0+'h170));
    assign emr_data_2_l_sw_wr = sw_wr && emr_data_2_l_decode;
    assign emr_data_2_l_sw_rd = sw_rd && emr_data_2_l_decode;

    always_comb begin
        emr_data_2_l_q = '0;
        emr_data_2_l_q[63: 0] = emr_data_2_l_emr_data_2_l_q;
    end

    // masked version of return data
    assign emr_data_2_l_rdata = emr_data_2_l_sw_rd ? emr_data_2_l_q : 'b0;

    // ------------------------------------------------------------
    // Field: emr_data_2_l (wire)
    // ------------------------------------------------------------
    assign emr_data_2_l_emr_data_2_l_anded = & emr_data_2_l_emr_data_2_l_q;
    assign emr_data_2_l_emr_data_2_l_ored  = | emr_data_2_l_emr_data_2_l_q;
    assign emr_data_2_l_emr_data_2_l_xored = ^ emr_data_2_l_emr_data_2_l_q;

    // next hardware value
    assign emr_data_2_l_emr_data_2_l_next = emr_data_2_l_emr_data_2_l_wdata;
    assign emr_data_2_l_emr_data_2_l_q = emr_data_2_l_emr_data_2_l_next;
            
        
    // ============================================================
    // Register: EMR_DATA_2_H
    //    [63: 0]         emr_data_2_h: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  emr_data_2_h_decode;
    logic                  emr_data_2_h_sw_wr;
    logic                  emr_data_2_h_sw_rd;
    logic [DATA_WIDTH-1:0] emr_data_2_h_q;

    assign emr_data_2_h_decode = (addr == (ADDR_OFFSET+'h0+'h178));
    assign emr_data_2_h_sw_wr = sw_wr && emr_data_2_h_decode;
    assign emr_data_2_h_sw_rd = sw_rd && emr_data_2_h_decode;

    always_comb begin
        emr_data_2_h_q = '0;
        emr_data_2_h_q[63: 0] = emr_data_2_h_emr_data_2_h_q;
    end

    // masked version of return data
    assign emr_data_2_h_rdata = emr_data_2_h_sw_rd ? emr_data_2_h_q : 'b0;

    // ------------------------------------------------------------
    // Field: emr_data_2_h (wire)
    // ------------------------------------------------------------
    assign emr_data_2_h_emr_data_2_h_anded = & emr_data_2_h_emr_data_2_h_q;
    assign emr_data_2_h_emr_data_2_h_ored  = | emr_data_2_h_emr_data_2_h_q;
    assign emr_data_2_h_emr_data_2_h_xored = ^ emr_data_2_h_emr_data_2_h_q;

    // next hardware value
    assign emr_data_2_h_emr_data_2_h_next = emr_data_2_h_emr_data_2_h_wdata;
    assign emr_data_2_h_emr_data_2_h_q = emr_data_2_h_emr_data_2_h_next;

endmodule: reg_mgmt
