// This file was autogenerated by PeakRDL-verilog
module sgdma_dfx #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              rst,  //! Default reset

    // Register SGDMA_ERR
    input  logic                             sgdma_err_sgdma_err_we,             //! Control HW write (active high)
    input  logic                     [31: 0] sgdma_err_sgdma_err_wdata,          //! HW write data
    output logic                     [31: 0] sgdma_err_sgdma_err_q,              //! Current field value

    // Register SGDMA_FF_STAT
    input  logic                     [31: 0] sgdma_ff_stat_sgdma_ff_stat_wdata,          //! HW write data

    // Register SGDMA_FSM_IF_STAT
    input  logic                     [31: 0] sgdma_fsm_if_stat_sgdma_fsm_if_stat_wdata,          //! HW write data

    // Register SGDMA_DMA_CNT
    input  logic                             sgdma_dma_cnt_sgdma_dma_cnt_we,             //! Control HW write (active high)
    input  logic                     [31: 0] sgdma_dma_cnt_sgdma_dma_cnt_wdata,          //! HW write data
    output logic                     [31: 0] sgdma_dma_cnt_sgdma_dma_cnt_q,              //! Current field value

    // Register SGDMA_BEQ_CNT
    input  logic                             sgdma_beq_cnt_sgdma_beq_cnt_we,             //! Control HW write (active high)
    input  logic                     [31: 0] sgdma_beq_cnt_sgdma_beq_cnt_wdata,          //! HW write data
    output logic                     [31: 0] sgdma_beq_cnt_sgdma_beq_cnt_q,              //! Current field value

    // Register Bus
    mlite_if.slave                           csr_if

);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [31: 0] sgdma_err_sgdma_err_next;
    logic                             sgdma_err_sgdma_err_anded;
    logic                             sgdma_err_sgdma_err_ored;
    logic                             sgdma_err_sgdma_err_xored;
    logic                           [31: 0] sgdma_ff_stat_sgdma_ff_stat_q;
    logic                           [31: 0] sgdma_ff_stat_sgdma_ff_stat_next;
    logic                             sgdma_ff_stat_sgdma_ff_stat_anded;
    logic                             sgdma_ff_stat_sgdma_ff_stat_ored;
    logic                             sgdma_ff_stat_sgdma_ff_stat_xored;
    logic                           [31: 0] sgdma_fsm_if_stat_sgdma_fsm_if_stat_q;
    logic                           [31: 0] sgdma_fsm_if_stat_sgdma_fsm_if_stat_next;
    logic                             sgdma_fsm_if_stat_sgdma_fsm_if_stat_anded;
    logic                             sgdma_fsm_if_stat_sgdma_fsm_if_stat_ored;
    logic                             sgdma_fsm_if_stat_sgdma_fsm_if_stat_xored;
    logic                           [31: 0] sgdma_dma_cnt_sgdma_dma_cnt_next;
    logic                             sgdma_dma_cnt_sgdma_dma_cnt_anded;
    logic                             sgdma_dma_cnt_sgdma_dma_cnt_ored;
    logic                             sgdma_dma_cnt_sgdma_dma_cnt_xored;
    logic                           [31: 0] sgdma_beq_cnt_sgdma_beq_cnt_next;
    logic                             sgdma_beq_cnt_sgdma_beq_cnt_anded;
    logic                             sgdma_beq_cnt_sgdma_beq_cnt_ored;
    logic                             sgdma_beq_cnt_sgdma_beq_cnt_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    logic [ADDR_WIDTH-1:0]      csr_if_addr;
    logic [DATA_WIDTH-1:0]      csr_if_wdata;
    logic [DATA_WIDTH-1:0]      csr_if_rdata;
    logic [DATA_WIDTH/8-1:0]    csr_if_wmask;


    logic [ADDR_WIDTH-1:0]      addr;
    logic [DATA_WIDTH-1:0]      rdata;
    logic [DATA_WIDTH/8-1:0]    wmask;

    // convert byte mask to bit mask
    always @(*) begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    enum logic [3:0]  { 
        IDLE     = 4'b0001,
        WRITE    = 4'b0010,
        READ     = 4'b0100,
        READ_RSP = 4'b1000
    } cstat, nstat;

    always @(posedge clk) begin
        if(rst)begin
            cstat <= IDLE;
        end else begin
            cstat <= nstat;
        end
    end

    always @(*)begin
        nstat = cstat;
        case (cstat)
            IDLE: begin
                if(csr_if.ready && csr_if.valid)begin
                    if(!csr_if.read)begin
                        nstat = WRITE;
                    end else begin
                        nstat = READ;
                    end
                end
            end
            WRITE:begin
                nstat = IDLE;
            end
            READ:begin
                nstat = READ_RSP;
            end
            READ_RSP:begin
                if(csr_if.rready)begin
                    nstat = IDLE;
                end
            end
            default:begin
                nstat = cstat;
            end
        endcase
    end

    always @(posedge clk) begin
        if(cstat == IDLE)begin
            csr_if_addr   <= csr_if.addr;
            csr_if_wdata  <= csr_if.wdata;
            csr_if_wmask  <= csr_if.wmask;
        end
    end


    assign addr     = csr_if_addr;
    assign sw_wr    = cstat == WRITE;
    assign sw_rd    = cstat == READ;
    assign sw_wdata = csr_if_wdata;
    assign wmask    = csr_if_wmask;
    assign rdata    = sw_rdata;

    always @(posedge clk) begin
        if(cstat == READ)begin
            csr_if_rdata <= rdata;
        end
    end

    assign csr_if.ready   = cstat == IDLE;
    assign csr_if.rvalid  = cstat == READ_RSP;
    assign csr_if.rdata   = csr_if_rdata;

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] sgdma_err_rdata;
    logic                     [DATA_WIDTH-1:0] sgdma_ff_stat_rdata;
    logic                     [DATA_WIDTH-1:0] sgdma_fsm_if_stat_rdata;
    logic                     [DATA_WIDTH-1:0] sgdma_dma_cnt_rdata;
    logic                     [DATA_WIDTH-1:0] sgdma_beq_cnt_rdata;

    assign sw_rdata = // or of each register return (masked)
                   sgdma_err_rdata | 
                   sgdma_ff_stat_rdata | 
                   sgdma_fsm_if_stat_rdata | 
                   sgdma_dma_cnt_rdata | 
                   sgdma_beq_cnt_rdata;
            
        
    // ============================================================
    // Register: SGDMA_ERR
    //    [31: 0]            sgdma_err: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  sgdma_err_decode;
    logic                  sgdma_err_sw_wr;
    logic                  sgdma_err_sw_rd;
    logic [DATA_WIDTH-1:0] sgdma_err_q;

    assign sgdma_err_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign sgdma_err_sw_wr = sw_wr && sgdma_err_decode;
    assign sgdma_err_sw_rd = sw_rd && sgdma_err_decode;

    always_comb begin
        sgdma_err_q = '0;
        sgdma_err_q[31: 0] = sgdma_err_sgdma_err_q;
    end

    // masked version of return data
    assign sgdma_err_rdata = sgdma_err_sw_rd ? sgdma_err_q : 'b0;

    // ------------------------------------------------------------
    // Field: sgdma_err
    // ------------------------------------------------------------
    assign sgdma_err_sgdma_err_anded = & sgdma_err_sgdma_err_q;
    assign sgdma_err_sgdma_err_ored  = | sgdma_err_sgdma_err_q;
    assign sgdma_err_sgdma_err_xored = ^ sgdma_err_sgdma_err_q;

    // next hardware value
    assign sgdma_err_sgdma_err_next = sgdma_err_sgdma_err_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        sgdma_err_sgdma_err_q <= 0;
    end else begin
        // Hardware Write
        if (sgdma_err_sgdma_err_we) begin
            sgdma_err_sgdma_err_q <= sgdma_err_sgdma_err_next;
        end
        // Software write
        else if (sgdma_err_sw_wr) begin
            sgdma_err_sgdma_err_q <= ~sw_masked_data[31: 0] &  sgdma_err_sgdma_err_q;
        end
    end
            
        
    // ============================================================
    // Register: SGDMA_FF_STAT
    //    [31: 0]        sgdma_ff_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  sgdma_ff_stat_decode;
    logic                  sgdma_ff_stat_sw_wr;
    logic                  sgdma_ff_stat_sw_rd;
    logic [DATA_WIDTH-1:0] sgdma_ff_stat_q;

    assign sgdma_ff_stat_decode = (addr == (ADDR_OFFSET+'h0+'h100));
    assign sgdma_ff_stat_sw_wr = sw_wr && sgdma_ff_stat_decode;
    assign sgdma_ff_stat_sw_rd = sw_rd && sgdma_ff_stat_decode;

    always_comb begin
        sgdma_ff_stat_q = '0;
        sgdma_ff_stat_q[31: 0] = sgdma_ff_stat_sgdma_ff_stat_q;
    end

    // masked version of return data
    assign sgdma_ff_stat_rdata = sgdma_ff_stat_sw_rd ? sgdma_ff_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: sgdma_ff_stat (wire)
    // ------------------------------------------------------------
    assign sgdma_ff_stat_sgdma_ff_stat_anded = & sgdma_ff_stat_sgdma_ff_stat_q;
    assign sgdma_ff_stat_sgdma_ff_stat_ored  = | sgdma_ff_stat_sgdma_ff_stat_q;
    assign sgdma_ff_stat_sgdma_ff_stat_xored = ^ sgdma_ff_stat_sgdma_ff_stat_q;

    // next hardware value
    assign sgdma_ff_stat_sgdma_ff_stat_next = sgdma_ff_stat_sgdma_ff_stat_wdata;
    assign sgdma_ff_stat_sgdma_ff_stat_q = sgdma_ff_stat_sgdma_ff_stat_next;
            
        
    // ============================================================
    // Register: SGDMA_FSM_IF_STAT
    //    [31: 0]    sgdma_fsm_if_stat: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  sgdma_fsm_if_stat_decode;
    logic                  sgdma_fsm_if_stat_sw_wr;
    logic                  sgdma_fsm_if_stat_sw_rd;
    logic [DATA_WIDTH-1:0] sgdma_fsm_if_stat_q;

    assign sgdma_fsm_if_stat_decode = (addr == (ADDR_OFFSET+'h0+'h108));
    assign sgdma_fsm_if_stat_sw_wr = sw_wr && sgdma_fsm_if_stat_decode;
    assign sgdma_fsm_if_stat_sw_rd = sw_rd && sgdma_fsm_if_stat_decode;

    always_comb begin
        sgdma_fsm_if_stat_q = '0;
        sgdma_fsm_if_stat_q[31: 0] = sgdma_fsm_if_stat_sgdma_fsm_if_stat_q;
    end

    // masked version of return data
    assign sgdma_fsm_if_stat_rdata = sgdma_fsm_if_stat_sw_rd ? sgdma_fsm_if_stat_q : 'b0;

    // ------------------------------------------------------------
    // Field: sgdma_fsm_if_stat (wire)
    // ------------------------------------------------------------
    assign sgdma_fsm_if_stat_sgdma_fsm_if_stat_anded = & sgdma_fsm_if_stat_sgdma_fsm_if_stat_q;
    assign sgdma_fsm_if_stat_sgdma_fsm_if_stat_ored  = | sgdma_fsm_if_stat_sgdma_fsm_if_stat_q;
    assign sgdma_fsm_if_stat_sgdma_fsm_if_stat_xored = ^ sgdma_fsm_if_stat_sgdma_fsm_if_stat_q;

    // next hardware value
    assign sgdma_fsm_if_stat_sgdma_fsm_if_stat_next = sgdma_fsm_if_stat_sgdma_fsm_if_stat_wdata;
    assign sgdma_fsm_if_stat_sgdma_fsm_if_stat_q = sgdma_fsm_if_stat_sgdma_fsm_if_stat_next;
            
        
    // ============================================================
    // Register: SGDMA_DMA_CNT
    //    [31: 0]        sgdma_dma_cnt: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  sgdma_dma_cnt_decode;
    logic                  sgdma_dma_cnt_sw_wr;
    logic                  sgdma_dma_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] sgdma_dma_cnt_q;

    assign sgdma_dma_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h200));
    assign sgdma_dma_cnt_sw_wr = sw_wr && sgdma_dma_cnt_decode;
    assign sgdma_dma_cnt_sw_rd = sw_rd && sgdma_dma_cnt_decode;

    always_comb begin
        sgdma_dma_cnt_q = '0;
        sgdma_dma_cnt_q[31: 0] = sgdma_dma_cnt_sgdma_dma_cnt_q;
    end

    // masked version of return data
    assign sgdma_dma_cnt_rdata = sgdma_dma_cnt_sw_rd ? sgdma_dma_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: sgdma_dma_cnt
    // ------------------------------------------------------------
    assign sgdma_dma_cnt_sgdma_dma_cnt_anded = & sgdma_dma_cnt_sgdma_dma_cnt_q;
    assign sgdma_dma_cnt_sgdma_dma_cnt_ored  = | sgdma_dma_cnt_sgdma_dma_cnt_q;
    assign sgdma_dma_cnt_sgdma_dma_cnt_xored = ^ sgdma_dma_cnt_sgdma_dma_cnt_q;

    // next hardware value
    assign sgdma_dma_cnt_sgdma_dma_cnt_next = sgdma_dma_cnt_sgdma_dma_cnt_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        sgdma_dma_cnt_sgdma_dma_cnt_q <= 0;
    end else begin
        // Hardware Write
        if (sgdma_dma_cnt_sgdma_dma_cnt_we) begin
            sgdma_dma_cnt_sgdma_dma_cnt_q <= sgdma_dma_cnt_sgdma_dma_cnt_next;
        end
        // Software write
        else if (sgdma_dma_cnt_sw_wr) begin
            sgdma_dma_cnt_sgdma_dma_cnt_q <= ~sw_masked_data[31: 0] &  sgdma_dma_cnt_sgdma_dma_cnt_q;
        end
    end
            
        
    // ============================================================
    // Register: SGDMA_BEQ_CNT
    //    [31: 0]        sgdma_beq_cnt: hw=rw    sw=rw    reset=0x0
    // ============================================================
    logic                  sgdma_beq_cnt_decode;
    logic                  sgdma_beq_cnt_sw_wr;
    logic                  sgdma_beq_cnt_sw_rd;
    logic [DATA_WIDTH-1:0] sgdma_beq_cnt_q;

    assign sgdma_beq_cnt_decode = (addr == (ADDR_OFFSET+'h0+'h208));
    assign sgdma_beq_cnt_sw_wr = sw_wr && sgdma_beq_cnt_decode;
    assign sgdma_beq_cnt_sw_rd = sw_rd && sgdma_beq_cnt_decode;

    always_comb begin
        sgdma_beq_cnt_q = '0;
        sgdma_beq_cnt_q[31: 0] = sgdma_beq_cnt_sgdma_beq_cnt_q;
    end

    // masked version of return data
    assign sgdma_beq_cnt_rdata = sgdma_beq_cnt_sw_rd ? sgdma_beq_cnt_q : 'b0;

    // ------------------------------------------------------------
    // Field: sgdma_beq_cnt
    // ------------------------------------------------------------
    assign sgdma_beq_cnt_sgdma_beq_cnt_anded = & sgdma_beq_cnt_sgdma_beq_cnt_q;
    assign sgdma_beq_cnt_sgdma_beq_cnt_ored  = | sgdma_beq_cnt_sgdma_beq_cnt_q;
    assign sgdma_beq_cnt_sgdma_beq_cnt_xored = ^ sgdma_beq_cnt_sgdma_beq_cnt_q;

    // next hardware value
    assign sgdma_beq_cnt_sgdma_beq_cnt_next = sgdma_beq_cnt_sgdma_beq_cnt_wdata;

    //! main storage
    always_ff @ (posedge clk)
    if (rst) begin
        sgdma_beq_cnt_sgdma_beq_cnt_q <= 0;
    end else begin
        // Hardware Write
        if (sgdma_beq_cnt_sgdma_beq_cnt_we) begin
            sgdma_beq_cnt_sgdma_beq_cnt_q <= sgdma_beq_cnt_sgdma_beq_cnt_next;
        end
        // Software write
        else if (sgdma_beq_cnt_sw_wr) begin
            sgdma_beq_cnt_sgdma_beq_cnt_q <= ~sw_masked_data[31: 0] &  sgdma_beq_cnt_sgdma_beq_cnt_q;
        end
    end

endmodule: sgdma_dfx
